caicloud/cyclone

notify/interface.go
notify/manager.go
notify/manager_test.go
notify/provider/email.go
notify/provider/email_test.go
notify/provider/error.html
notify/provider/errorchinese.html
notify/provider/success.html
notify/provider/successchinese.html
pkg/executil/executil.go
pkg/executil/executil_test.go
pkg/filebuffer/buffer.go
pkg/log/logutil.go
pkg/osutil/osutil.go
pkg/osutil/osutil_test.go
pkg/pathutil/pathutil.go
pkg/pathutil/pathutil_test.go
pkg/wait/wait.go
pkg/wait/wait_test.go

add  notify and pkg

---

README.md
README_zh-CN.md

PTAL
[preview](https://github.com/gaocegege/cyclone/blob/dd391f866920e6dcae45f793aef2c953a46c8699/README.md)

add the badge

---

README.md
docs/caicloud-yml-reference.md
docs/caicloud-yml-reference_zh-CN.md
docs/principle.md
docs/principle_zh-CN.md
docs/quick-start.md
docs/quick-start_zh-CN.md
docs/setup.md
docs/setup_zh-CN.md

update the doc to latest version

---

api/rest/service.go
api/types.go
docs/principle.md
main.go
notify/manager_test.go
resource/resource.go
tests/common/log.go
tests/project/project_test.go
tests/service/service_test.go
tests/version/version_test.go
utils/utils_test.go
websocket/protocol.go
websocket/websocket_test.go
worker/ci/parser/parser.go
worker/ci/yaml/yaml.go
worker/helper/helper.go
worker/log/log.go

code optimization by go report

---

node_modules/swagger-ui/dist/index.html

change the default url

---

README.md
README_zh-CN.md
docs/caicloud-yml-introduction_zh-CN.md
docs/developer-guide.md
docs/developer-guide_zh-CN.md

add developer documention

---

scripts/tools/create-service-version.sh
scripts/tools/create-service.sh
scripts/tools/create-version.sh
scripts/tools/get-service.sh
scripts/tools/get-version.sh

add scripts

---

event/event.go

delete the repeated code to avoid sending email twice

delete the repeated code

---

README.md
README_zh-CN.md

update preview feature

---

docs/setup.md
docs/setup_zh-CN.md

optimize documentation

---

pkg/log/logutil.go

fix log debug

---

api/types.go
scripts/tools/create-service.sh
worker/ci/manager.go

Support for customization caicloud.yml file

support the customization yaml file

---

scripts/build-image.sh
scripts/lib/common.sh

fix  https://github.com/caicloud/cyclone/issues/53

 disable the selinux before build the image

---

docker/auth.go

make the error message more human readable

---

api/rest/worker_node.go
cyclone-unit-test.yml
tests/run-unit-test.sh

cyclone run unit tests in cyclone

---

api/types.go
docker/manager.go
pkg/osutil/osutil.go
worker/ci/runner/docker.go
worker/ci/runner/runner.go
worker/clair/clair.go
worker/cyclone-worker.go
worker/helper/helper.go
worker/helper/helper_test.go
worker/helper/output.go
worker/log/log.go
worker/vcs/provider/git.go
worker/vcs/provider/svn.go

optimize log operation

---

.travis.yml
tests/run-unit-test.sh
worker/helper/helper_test.go
worker/helper/output.go
worker/helper/output_test.go
worker/log/log_test.go

fix unit test cases

---

scripts/build-image.sh
scripts/build-in-docker.sh
scripts/build-worker-image.sh
scripts/local-up.sh

use set -e and -u instead of -o

fix: docker tag dose not have -f flag

---

docker/manager.go
websocket/websocket_test.go
worker/ci/runner/docker.go
worker/ci/runner/docker_test.go
worker/ci/runner/runner.go

remove docker network

---

api/rest/deploy.go
api/rest/init.go
api/types.go
store/deploy.go
store/store.go

support new deploy api for Ui to Implement a new deployment scenario

new deploy api

---

notify/provider/email_test.go

@gaocegege  @superxi911  PTAL. Thanks.

isolate test cases for email notify

---

api/rest/version.go
api/types.go
event/event.go
event/manager.go
event/worker.go
tests/service/service_test.go
websocket/application.go

make changes to support cancel building job manually
Also fix issue https://github.com/caicloud/cyclone/issues/83

support cancel building job

---

api/rest/init.go
api/rest/service.go
store/version.go

add badge for service

---

README.md
README_zh-CN.md
worker/vcs/manager.go

add badges and fix typos

---

README.md
README_zh-CN.md

Reformat badges by @superxi911 's idea.

reformat badges

---

worker/log/log.go

fix [#73](https://github.com/caicloud/cyclone/issues/73)

fix: redail when worker disconnect from log server

---

pkg/kubefaker/factory.go
pkg/kubefaker/faker.go
worker/helper/helper.go

ISSUE https://github.com/caicloud/cyclone/issues/97

[WIP] Support cyclone create a new k8s  deployment

---

docs/caicloud-yml-reference_zh-CN.md

rename "depoly" to "deploy"

---

docs/developer-guide.md
docs/developer-guide_zh-CN.md

**Changes**
**Reviewers**
**Checklist**

docs: modify online api doc url

---

caicloud_unit-test.yml

change unit test build image, add gcc

build(unittest): change unit test build image

---

api/rest/event.go
api/rest/service.go
api/rest/version.go
api/rest/webhook.go
api/types.go
etcd/etcd_client.go
event/event.go
event/manager.go
event/operations.go
store/service.go
store/version.go
tests/service/service_test.go
worker/cyclone-worker.go
worker/vcs/interface.go
worker/vcs/manager.go
worker/vcs/manager_test.go
worker/vcs/provider/fake.go
worker/vcs/provider/git.go
worker/vcs/provider/svn.go

feat: Support building a new version after creating a service automatically
perf: add vcs ping function to accelerate service creation
refactor: change service and version id to mongodb objectId
**Changes**
- feat: Support building a new version after creating a service automatically
- perf: add vcs ping function to accelerate service creation
- refactor: change service and version id to mongodb objectId
**Reviewers**
**Checklist**

Support building a new version after creating a service automatically

---

docs/caicloud-yml-reference.md
docs/caicloud-yml-reference_zh-CN.md

Closes https://github.com/caicloud/cyclone/issues/89
Ref https://github.com/caicloud/cyclone/pull/74
**Changes**
**Checklist**

reference.md: Update network mode

---

Dockerfile.server
api/server/options.go

**Changes**
**Reviewers**
**Checklist**

fix(apidocs): show api docs url by default

---

docs/setup.md
docs/setup_zh-CN.md

fix doc mistakes https://github.com/caicloud/cyclone/issues/151

---

docs/setup.md
docs/setup_zh-CN.md

Fix error in setup doc

---

pkg/api/types.go
store/project.go
store/store.go

**Changes**
- Add project data structure
- Support project CRUD

Add project data structure and support project CRUD

---

pkg/api/types.go
store/pipeline.go
store/store.go

add pipeline data structure and CRUD

---

pkg/api/types.go
store/pipelineRecord.go
store/store.go

Fixes #160 
Changes
-  Add pipelineRecord data structure
-  Add pipelineRecord CRUD

add pipelineRecord data structure and CRUD

---

api/server/server.go
pkg/server/manager/pipeline.go
pkg/server/manager/project.go
pkg/server/router/project.go
pkg/server/router/router.go
pkg/util/http/http.go
store/project.go

Add project rest apis

---

pkg/api/types.go

Fix typos for apis

---

pkg/server/manager/pipeline.go
pkg/server/manager/project.go
pkg/server/router/pipeline.go
pkg/server/router/router.go
store/pipeline.go

Add pipeline rest APIs

---

worker/worker.go

refactor(woker): add function to set fail status for event

---

pkg/api/types.go
pkg/server/manager/pipeline.go
pkg/server/manager/project.go
pkg/server/router/pipeline.go
pkg/server/router/project.go
pkg/util/http/http.go
store/pipeline.go
store/project.go

add list metadata and method, move struct error response to tpyes.go

---

pkg/server/manager/pipeline.go
pkg/server/manager/pipelineRecord.go
pkg/server/router/pipelineRecord.go
pkg/server/router/router.go
store/pipelineRecord.go

add pipeline record Restful API

---

store/project.go

so sorry, It's my mistake that hasn't checked the code enough.

fix the bug with wrong collection name

---

api/conversion/conversion.go
api/conversion/converstion_test.go
api/conversion/types.go
pkg/server/manager/pipeline.go
pkg/server/router/pipeline.go

feat(server): relate pipeline with service

---

pkg/server/manager/pipeline.go
pkg/server/manager/pipelineRecord.go
pkg/server/router/pipelineRecord.go
pkg/server/router/router.go
store/pipelineRecord.go

Cherry pick #175 into v1-preview

---

store/project.go

Cherry pick #177 into v1-preview

---

api/conversion/conversion.go
api/conversion/converstion_test.go
api/conversion/types.go
pkg/server/manager/pipeline.go
pkg/server/manager/project.go
pkg/server/router/pipeline.go

Relate pipeline with service

---

api/conversion/conversion.go
pkg/api/types.go
pkg/server/manager/pipeline.go
pkg/server/router/pipeline.go
pkg/server/router/router.go

Support performing pipeline

---

docs/api/v1/api.md

add api.md of v1

---

pkg/api/types.go
pkg/server/router/pipeline.go
pkg/server/router/pipelineRecord.go
pkg/server/router/project.go
pkg/util/http/http.go

remove items length to suit API standard

---

pkg/api/types.go
pkg/server/router/pipeline.go
pkg/server/router/pipelineRecord.go
pkg/server/router/project.go
pkg/util/http/http.go

Cherry pick #193 into v1-preview

---

pkg/api/types.go
pkg/server/manager/pipeline.go
pkg/server/manager/pipelineRecord.go
pkg/server/manager/project.go
pkg/server/router/pipeline.go
pkg/server/router/pipelineRecord.go
pkg/server/router/project.go
pkg/util/http/errors/errors.go
pkg/util/http/errors/format.go
pkg/util/http/http.go
store/pipeline.go
store/pipelineRecord.go
store/project.go

Enhancement<server>: normalize the REST APIs

---

api/rest/log.go
api/rest/version.go

Enhancement<server>: Return 404 for versions and their logs when they are not found

---

api/conversion/conversion.go
api/types.go
pkg/server/manager/pipeline.go
worker/worker.go

fix Image name to match new requirement

---

cloud/controller.go

fix(#200): fix panic error when create service if no cloud is registered

---

cloud/controller.go

Cherry pick #201 into v1-preview 

---

api/conversion/types.go
pkg/server/manager/pipeline.go
pkg/server/router/pipeline.go
pkg/server/router/pipelineRecord.go
pkg/server/router/project.go
pkg/util/http/http.go

refact(server): remove useless status code parameter

---

pkg/server/manager/pipeline.go

fix(#208): update related service when update pipeline

---

worker/worker.go

fix(214): fix panice error when dial websocket gets error

---

api/conversion/conversion.go
api/conversion/converstion_test.go
pkg/api/types.go
pkg/server/manager/pipeline.go
pkg/server/manager/pipelineRecord.go
pkg/server/router/pipeline.go
pkg/server/router/pipelineRecord.go
pkg/server/router/router.go
pkg/util/http/http.go
store/version.go

feat(api): Update apis

---

worker/worker.go

Cherry pick #215 into v1-preview

---

pkg/server/router/router.go

fix(server): correct the HTTP method to abort pipeline record

---

pkg/api/types.go
pkg/scm/provider/github.go
pkg/scm/provider/gitlab.go
pkg/scm/provider/helper.go
pkg/scm/scm.go
pkg/server/router/router.go
pkg/server/router/scm.go
store/scm.go
store/store.go

feat(216): add new implement of git oauth

---

pkg/api/types.go
pkg/server/manager/pipelineRecord.go
pkg/util/http/http.go
store/version.go

feat(server): support to filter pipeline record

---

docs/api/v1/api.md

docs(#211): add more details to API document of v1

---

api/conversion/conversion.go

fix(server): exec image release stage when perform pipeline

---

api/conversion/conversion.go
api/types.go
event/event.go

feat(#225): add end time of pipeline record

---

pkg/server/router/pipelineRecord.go

fix(server): return body for path pipeline record status

---

pkg/api/types.go
pkg/server/manager/pipelineRecord.go
pkg/server/router/pipelineRecord.go
pkg/server/router/router.go
pkg/util/http/http.go

**Changes**
1. support API to get pipeline record log
2. support API to download pipeline record log

feat(server): support pipeline record log API

---

api/conversion/conversion.go
api/conversion/converstion_test.go
pkg/api/types.go

fix(#233): add perform stages into record

---

cmd/server/server.go
event/operations.go
pkg/api/types.go
pkg/scm/provider/github.go
pkg/scm/provider/gitlab.go
pkg/scm/scm.go
pkg/server/manager/pipeline.go
pkg/server/manager/project.go
pkg/server/router/project.go
pkg/server/router/router.go
store/pipeline.go
store/project.go

feat(scm): support scm config for project

---

pkg/scm/provider/github.go
pkg/scm/scm.go
pkg/server/manager/project.go

feat(scm): support github

---

pkg/server/manager/pipeline.go

fix(pipeline): fix pipeline alias update

---

event/event.go

feat(server): add aborted state in log for aborted log

---

docs/api/v1/api.md

feat(doc): fix errors in api doc

---

api/conversion/conversion.go
api/types.go
worker/log/log.go
worker/vcs/manager.go

feat: Support the branch in pipeline perform params
**Changes**
**Reviewers**
**Checklist**

Feature [ISSUE-#246] Support the branch in pipeline perform params

---

pkg/server/router/pipelineRecord.go

**Changes**
**Reviewers**
**Checklist**

fix(logserver )：stop loading log from kafka when socket closed

---

worker/ci/runner/docker.go

fix(server): output path is relative path instead of absolute path

---

worker/worker.go

feat(#267): image build can be skipped when perform pipeline

---

api/server/server.go
store/store.go

refact(stability): retry to connect MongoDB

---

api/conversion/conversion.go

**Changes**
**Reviewers**
**Checklist**

Fix: UT command

---

store/store.go

fix(mongodb): change mongodb session mode to fix session closed explicitly

---

store/store.go

Cherry pick #271 to release-0.1.1

---

api/types.go
cloud/k8s.go
cloud/worker.go
event/manager.go

fix(cloud): fix error for worker location

---

.travis.yml

**Changes**
`travis_wait 20 mvn install`
**Reviewers**
**Checklist**

chore(issue#257): approve stability for Go 1.7 build

---

pkg/scm/provider/github.go
pkg/scm/provider/gitlab.go
pkg/scm/scm.go

Cherry pick #280 to release-0.3

---

.gitignore

feat(git): update git ignore

---

Jenkinsfile
Makefile
build/server/Dockerfile
build/worker/Dockerfile
scripts/build-server.sh
scripts/build-worker.sh

**Changes**
**Reviewers**
/cc @bbbmj

feat(repo): repo convention

---

build/worker/Dockerfile
scripts/worker_image/Dockerfile

**Changes**
**Reviewers**
**Checklist**

feat(cyclone): add base docker image to worker

---

Jenkinsfile
Makefile
build/server/Dockerfile
build/worker/Dockerfile
scripts/build-server.sh
scripts/build-worker.sh
scripts/worker_image/Dockerfile

**Changes**
**Reviewers**
@bbbmj

Cherry pick #281 and #287 into release-0.3

---

api/conversion/conversion.go

fix(294): add default Dockerfile path for build stage

---

build/worker/Dockerfile
build/worker/daemon.json

fix(#296): add registry mirror for Docker hub images

---

api/conversion/conversion.go

Cherry pick #295 into release-0.3 

---

build/worker/Dockerfile
build/worker/daemon.json

Cherry pick #297 into release-0.3 

---

api/conversion/conversion.go
api/conversion/types.go
scripts/build-server.sh
scripts/build-worker.sh
worker/ci/parser/node.go
worker/ci/parser/parser.go
worker/ci/runner/runner.go

**Changes**
integration test skipped without image
**Reviewers**
**Checklist**

Fix: integration test skipped 

---

docs/api/v1/api.md

feat(doc): update api doc

---

api/conversion/conversion.go
api/conversion/types.go
scripts/build-server.sh
scripts/build-worker.sh
worker/ci/parser/node.go
worker/ci/parser/parser.go
worker/ci/runner/runner.go

**Changes**
**Reviewers**
/cc @LiangXugang

Cherry pick #301 into release-0.3

---

store/version.go
worker/worker.go

default name when codeCheckout failed
**Changes**
**Reviewers**
**Checklist**

fix: add default version.name(version.versionID)

---

store/version.go
worker/worker.go

default name when codeCheckout failed
**Changes**

Cherry pick #303 into release-0.3 

---

docs/api/v1/api.md

feat(docs): update api doc

---

pkg/server/manager/pipeline.go

fix(server): fix the count for recent success and failed records

---

Jenkinsfile
Makefile
build/server/Dockerfile
build/worker/Dockerfile
scripts/build-server.sh
scripts/build-worker.sh
scripts/worker_image/Dockerfile

Cherry pick #281 and #287 into master

---

.travis.yml

fix(#257): fix travis timeout

---

cmd/server/server.go
cmd/worker/worker.go
pkg/server/router/router.go

fix(log): print glog logs to std

---

pkg/event/manager.go

Fix the hang of event manager

---

pkg/docker/client.go

feat(docker): add docker manager

---

pkg/event/event.go
pkg/event/manager.go
pkg/server/manager/pipelineRecord.go

fix(327): delete the event and worker for running pipeline record

---

pkg/event/event.go

fix(#330): fix panic error when abort pipeline which has no log

---

pkg/api/types.go
pkg/server/manager/pipelineRecord.go
pkg/server/router/pipelineRecord.go
pkg/server/router/router.go
pkg/util/file/file.go
pkg/util/file/file_test.go

Implement the log server

---

docs/api/v1/api.md
pkg/server/router/pipelineRecord.go
pkg/server/router/router.go

Normalize the api path placeholder to be lowercase.
Fixes #333
```release-note
NONE
```

refact(api): normalize the api path placeholder

---

cloud/k8s.go
cloud/worker.go
pkg/event/manager.go

feat(#255): add namespace for workers in k8s

---

pkg/server/manager/pipelineRecord.go
pkg/server/router/pipelineRecord.go
pkg/util/websocket/websocket.go

Implement the log server.
Fixes partially #307
/cc @bbbmj 
```release-note
NONE
```

feat(log): refactor log server

---

pkg/server/manager/cloud.go
pkg/server/router/cloud.go
pkg/server/router/router.go

xref: #343
Add the cloud apis in v1.
Fixes #
```release-note
NONE
```

feat(#342): add the cloud apis in v1

---

pkg/server/router/health_check.go
pkg/server/router/router.go

xref: #343
Add health check api in v1.
Fixes #
/cc @bbbmj 
```release-note
NONE
```

feat(#342): add health check api in v1

---

cloud/k8s.go

When the volume has error, still let the pipeline to run, but in non-cache mode.
Fixes #346
/cc @bbbmj 
```release-note
NONE
```

fix(#346): let the pipeline to run in non-cache mode when volume has error

---

event/event.go

Manually cherry pick #331 into release-0.3:
#331: fix(#330): fix panic error when abort pipeline which has no log
Fixes #330
/cc @zhujian7 
```release-note
NONE
```

Cherry pick #331 into release-0.3

---

pkg/server/router/health_check.go

Add health check for cloud provider
Fixes #338
/cc @zhujian7 
```release-note
NONE
```

fix(#338): add health check for cloud provider

---

pkg/scm/provider/github.go
pkg/scm/provider/gitlab.go
pkg/scm/scm.go
pkg/server/manager/project.go
pkg/server/router/project.go
pkg/server/router/router.go

Manually trigger pipeline by tag
Fixes #355 
```release-note
NONE
```

feat(server):trigger pipeline by tag

---

pkg/api/types.go
pkg/event/manager.go
pkg/server/manager/event.go
pkg/server/manager/pipelineRecord.go
pkg/server/router/pipelineRecord.go
pkg/worker/cycloneserver/client.go
pkg/worker/scm/manager.go
pkg/worker/scm/provider/git.go
pkg/worker/stage/stage.go
pkg/worker/worker.go

pipelines only report status when they finish
report real-time build status while the pipelines are running
Fixes #361 
```release-note
NONE
```

feat(#361):report real-time build status while the pipelines are running

---

pkg/worker/stage/stage.go

support context to build image
Fixes #356 
```release-note
NONE
```

feat(#356):support context to build image

---

cloud/k8s.go
cloud/worker.go
pkg/api/types.go
pkg/event/manager.go
pkg/worker/stage/stage.go
pkg/worker/worker.go

Use cache volume to speed up pipeline
Fixes #346
/cc @zhujian7 
```release-note
Use cache volume to speed up pipeline
```

feat(#346): use cache volume to speed up pipeline

---

pkg/api/types.go
pkg/scm/provider/github.go
pkg/scm/provider/gitlab.go
pkg/scm/scm.go
pkg/worker/scm/manager.go
pkg/worker/stage/stage.go
pkg/worker/worker.go

support creating tag when perform pipeline
Fixes #369 
```release-note
NONE
```

feat(pipeline):support creating tag when perform pipeline

---

pkg/worker/stage/stage.go

support to build multiple images
Fixes #354 
```release-note
NONE
```

feat(pipeline):support to build multiple images

---

cloud/worker.go
pkg/api/helper.go
pkg/api/types.go
pkg/scm/provider/github.go
pkg/scm/provider/gitlab.go
pkg/scm/provider/helper.go
pkg/scm/scm.go
pkg/server/manager/pipeline.go
pkg/server/router/router.go
pkg/server/router/webhook.go
pkg/store/pipeline.go
pkg/util/gitlab/gitlab.go
pkg/worker/scm/manager.go

Fixes #
```release-note
NONE
```

support webhook

---

pkg/store/pipeline.go

Fixes #
```release-note
NONE
```

fix(store): fix error for pipeline

---

pkg/docker/client.go
pkg/worker/stage/stage.go

Fixes #373
/cc @zhujian7 
```release-note
NONE
```

fix(#373): fix error for integration test

---

pkg/worker/stage/stage.go

Fixes #
```release-note
NONE
```

support customized dockerfile

---

pkg/worker/stage/stage.go

Fixes #385 
/cc @zhujian7 
```release-note
NONE
```

fix(#385): support multiple format for outputs

---

pkg/server/router/webhook.go
pkg/worker/scm/manager.go
pkg/worker/scm/provider/git.go
pkg/worker/stage/stage.go
pkg/worker/worker.go

Fixes #283
/cc @zhujian7 
```release-note
NONE
```

refact(webhook): enhancements and fix error

---

pkg/worker/stage/stage.go

Fixes #
/cc @zhujian7 
```release-note
NONE
```

refact(worker): use unify Docker client

---

pkg/api/types.go
pkg/docker/client.go
pkg/server/manager/project.go
pkg/worker/stage/stage.go
pkg/worker/worker.go

Fixes #352
/cc @zhujian7 
```release-note
Support registry auth config for projects
```

fix(#352): support registry auth config for projects

---

pkg/worker/scm/manager.go
pkg/worker/scm/manager_test.go

support SCM server with ip
Fixes #384 
```release-note
NONE
```

fix(pipeline): support SCM server with ip

---

pkg/api/types.go
pkg/server/manager/pipeline.go
pkg/server/manager/pipeline_test.go
pkg/server/manager/project.go
pkg/server/router/pipeline.go
pkg/server/router/project.go
pkg/server/router/router.go
pkg/store/pipelineRecord.go

support pipeline record status statistics
Fixes #377 
```release-note
NONE
```

feat(server):support pipeline record status statistics

---

pkg/scm/provider/gitlab.go

list all repos from gitlab
Fixes #404 
```release-note
NONE
```

fix(scmgitlab):list all repos from gitlab

---

pkg/scm/provider/gitlab.go

list all repos from gitlab(cherry-pick)
Fixes #404 
```release-note
NONE
```

fix(scmgitlab):list all repos from gitlab (#405)

---

.travis.yml
pkg/worker/cycloneserver/fake.go
pkg/worker/scm/manager.go
pkg/worker/stage/stage_test.go

Fixes #
```release-note
NONE
```

Add test case for stage manager

---

api/server/options.go
api/server/server.go
cmd/server/options.go
cmd/server/server.go
pkg/store/helper.go
pkg/store/helper_test.go
pkg/store/project.go
pkg/store/store.go
pkg/util/encrypt/encrypt.go
pkg/util/encrypt/encrypt_test.go

Fixes #411 
/cc @zhujian7 
```release-note
Encrypt password for projects
```

feat(#411): Encrypt password for projects

---

pkg/store/pipeline.go
pkg/store/project.go

Fixes #
/cc @zhujian7 
```release-note
NONE
```

clean up useless code about service

---

pkg/api/types.go
pkg/scm/scm.go
pkg/server/manager/pipeline.go
pkg/server/router/pipelineRecord.go
pkg/server/router/webhook.go
pkg/worker/scm/manager.go
pkg/worker/scm/provider/git.go
pkg/worker/stage/stage.go
pkg/worker/stage/stage_test.go
pkg/worker/worker.go

enrich pipeline record infos AND update codesources struct for code checkout stage.
Fixes #357 
```release-note
NONE
```

enrich pipeline record infos

---

pkg/api/types.go
pkg/server/manager/pipeline.go
pkg/worker/scm/manager.go
pkg/worker/stage/stage.go
pkg/worker/stage/stage_test.go
pkg/worker/worker.go

fix CodeCheckoutStage struct
Fixes #
```release-note
NONE
```

fix CodeCheckoutStage struct

---

Gopkg.lock
Gopkg.toml
vendor/github.com/golang/glog/README
vendor/github.com/golang/glog/glog.go

Fixes #401
/cc @zhujian7 
```release-note
NONE
```

fix(#401): fix glog version

---

pkg/api/types.go

Fixes #
/cc @zhujian7 
```release-note
NONE
```

feat(api): make data inline

---

pkg/server/router/pipeline.go
pkg/server/router/pipelineRecord.go
pkg/server/router/project.go
pkg/util/http/http.go

enrich pipeline infon add trigger and owner
Fixes #
```release-note
NONE
```

fix:enrich pipeline infon add trigger and owner

---

pkg/api/types.go
pkg/server/manager/pipelineRecord.go
pkg/server/router/pipelineRecord.go
pkg/server/router/router.go
pkg/worker/cycloneserver/client.go
pkg/worker/cycloneserver/fake.go
pkg/worker/scm/provider/git.go
pkg/worker/stage/helper.go
pkg/worker/stage/helper_test.go
pkg/worker/stage/stage.go
pkg/worker/stage/stage_test.go

Fixes #409
```release-note
NONE
```

fix(#409): Support subtask in image build stage

---

pkg/api/helper.go
pkg/api/types.go
pkg/scm/provider/svn.go
pkg/scm/scm.go
pkg/store/helper.go
pkg/worker/scm/manager.go
pkg/worker/scm/provider/git.go
pkg/worker/scm/provider/svn.go
pkg/worker/stage/stage.go
pkg/worker/stage/stage_test.go

cyclone support svn
Fixes #353 
```release-note
NONE
```

feat(svn):cyclone support svn

---

Makefile
pkg/api/helper.go
pkg/api/types.go
pkg/scm/provider/github.go
pkg/scm/provider/gitlab.go
pkg/scm/scm.go
pkg/store/helper.go
pkg/store/helper_test.go
pkg/worker/scm/manager.go
pkg/worker/scm/provider/git.go
pkg/worker/stage/stage_test.go

Fixes #
/cc @zhujian7 
```release-note
NONE
```

refact(scm): rename scm type

---

pkg/server/manager/pipelineRecord.go

can not delete pipeline
Fixes #
```release-note
NONE
```

fix(pipeline):can not delete pipeline

---

pkg/worker/stage/stage.go

Fixes #
/cc @zhujian7 
```release-note
NONE
```

fix(log): fix log for image release stage

---

pkg/api/types.go
pkg/server/manager/pipeline.go
pkg/store/pipelineRecord.go

fix  incorrect format of timestamp 
Fixes #
```release-note
NONE
```

fix(stats):timestamp had an incorrect format

---

pkg/store/helper.go

Fixes #
```release-note
NONE
```

fix(svn):password is needed when updating project

---

pkg/server/manager/pipelineRecord.go
pkg/worker/cycloneserver/client.go

Fixes #
```release-note
NONE
```

fix(log): enhance log stream

---

pkg/server/router/webhook.go

Fixes #
/cc @zhujian7 
```release-note
NONE
```

fix(webhook): fix pipeline record name for webhook trigger

---

pkg/server/router/pipelineRecord.go
pkg/store/pipelineRecord.go
pkg/worker/cycloneserver/client.go
pkg/worker/stage/helper.go
pkg/worker/stage/helper_test.go
pkg/worker/stage/stage.go
pkg/worker/worker.go

Fixes #
```release-note
NONE
```

refact(log): refact the collection of stage logs

---

pkg/event/manager.go
pkg/worker/scm/provider/svn.go

Fixes #
```release-note
NONE
```

fix(worker):add pipeline record endtime

---

pkg/util/http/http.go

Fixes #446
```release-note
NONE
```

fix(#446): support filtering multiple fields when list pipeline records

---

pkg/scm/provider/github.go
pkg/server/manager/pipeline.go

Fixes #441 
/cc @zhujian7 
```release-note
NONE
```

fix(#441): Fail to create Github webhook when create and update pipeline

---

cloud/k8s.go

change restartPolicy from Always to Never
Fixes #
```release-note
NONE
```

fix:change restartPolicy from Always to Never

---

cloud/k8s.go
cloud/worker.go
pkg/event/manager.go

Fixes #440,  caicloud/quality#370
/cc @zhujian7 
```release-note
NONE
```

fix(#440): delete worker after pipeline finish

---

pkg/api/helper_test.go
pkg/api/types.go
pkg/worker/stage/stage.go

Fixes #
```release-note
NONE
```

fix(api):update api

---

Makefile

Fixes #
```release-note
NONE
```

fix(Makefile):disable cgo of local-build

---

pkg/worker/stage/stage.go

Fixes #
```release-note
NONE
```

fix(pipeline):logs are not display at integration test stage

---

cloud/k8s.go
cloud/quota.go
cloud/worker.go

Fixes #391 
```release-note
NONE
```

feat(quota):separate resource request and limit config for worker

---

api/conversion/conversion.go
worker/worker.go

Fixes #
/cc @zhujian7 
/cc @wzqnls 
```release-note
NONE
```

feat(stage): support to skip package stage

---

OWNERS

Fixes #
/cc @zhujian7 
```release-note
NONE
```

chore(*): add zhujian into owner

---

pkg/server/router/router.go

Fixes #463 
```release-note
NONE
```

fix(#463): add log for each request

---

pkg/api/types.go
pkg/worker/stage/stage.go
pkg/worker/stage/stage_test.go

Fixes #
```release-note
NONE
```

fix:add 'repository' to support update image registry

---

cloud/controller.go
cloud/docker.go
cloud/k8s.go
cloud/types.go
pkg/event/manager.go
pkg/server/manager/cloud.go
pkg/server/router/cloud.go
pkg/store/cloud.go

Fixes partially #464
```release-note
NONE
```

fix(#464): refactor cloud type

---

docs/api/v1/api.md

Update the log API for stage log
Fixes #358
/cc @zhujian7 
```release-note
NONE
```

feat(docs): update the log API for stage log

---

.gitignore
pkg/api/types.go
pkg/scm/provider/github.go
pkg/scm/provider/gitlab.go
pkg/scm/provider/helper.go
pkg/scm/scm.go
pkg/server/router/router.go
pkg/server/router/scm.go
store/scm.go
store/store.go

init oauth
feat: add oauth api for creating project
feat: add oauth api for creating project
Fixes #
/cc @keontang @supereagle 
```release-note
NONE
```

feat: add oauth api for creating project

---

pkg/scm/provider/gitlab.go

fix(oauth): fix the bug of returning wrong gitlab server url
Fixes #
/cc @keontang @supereagle 
```release-note
NONE
```

fix(oauth): fix the bug of returning wrong gitlab server url

---

pkg/store/cloud.go

Fixes #
/cc @zhujian7 
```release-note
NONE
```

fix(store): fix id of cloud

---

docs/api/v1/api.md

Fixes #
/cc @zhujian7 
```release-note
NONE
```

feat(api): add cloud api doc

---

pkg/store/store.go

Fixes #
/cc @supereagle
```release-note
NONE
```

chore(typo): fix typo

---

store/pipeline.go
store/project.go
store/scm.go

Fixes #
```release-note
NONE
```

fix(mongo):can not get data from mongo while there are two pieces of data

---

pkg/docker/client.go
pkg/worker/stage/stage_test.go

Fixes #388 
```release-note
NONE
```

feat(docker):support builder images from docker hub

---

pkg/server/manager/pipeline.go
pkg/server/manager/project.go
pkg/util/slugify/slugify.go
pkg/util/slugify/slugify_test.go

Fixes #403 
```release-note
NONE
```

fix(name conflict):avoid name conflict when generate it from alias

---

pkg/server/manager/pipeline.go
pkg/server/manager/pipelineRecord.go
pkg/server/manager/project.go

Fixes #
Reference to #
/cc @supereagle
```release-note
NONE
```

fix:logs are not deleted while deleting related resource

---

api/server/options.go
api/server/server.go
pkg/server/manager/pipelineRecord.go
pkg/server/router/router.go
pkg/store/pipelineRecord.go

Fixes #
Reference to #
```release-note
NONE
```

feat:support pipeline record rotation

---

pkg/docker/client.go
pkg/docker/helper.go

Fixes #
Reference to #
```release-note
NONE
```

fix(worker):change container start entrypoint

---

pkg/scm/provider/github.go
pkg/scm/provider/gitlab.go
pkg/scm/scm.go

Fixes #
Reference to #
```release-note
NONE
```

perf(project):validate token from getting repos just for once

---

pkg/api/types.go
pkg/server/manager/pipeline.go
pkg/server/router/pipeline.go
pkg/server/router/pipelineRecord.go

Fixes #
Reference to #
```release-note
NONE
```

feat(api):add recent record info while getting pipeline

---

pkg/scm/provider/github.go
pkg/server/router/webhook.go
pkg/util/gitlab/gitlab.go
pkg/util/gitlab/helper.go

Fixes #
Reference to #
```release-note
NONE
```

feat:support push event type webhook

---

pkg/worker/worker.go

feat: support to skip package stage
Fixes #
Reference to [CI模板迁移](https://github.com/caicloud/service/issues/284)
/cc 
@supereagle 
```release-note
NONE
```

feat: support to skip package stage

---

notify/provider/email.go
scripts/e2e-docker.sh
scripts/e2e-k8s.sh
tests/common/setup.go
tests/project/project_test.go

Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

fix(*): e2e test failure

---

build/server/Dockerfile

Fixes #
Reference to #
```release-note
NONE
```

fix(Dockerfile):remove http/web

---

docs/api/v1/api.md
pkg/api/helper_test.go
pkg/api/types.go
pkg/cloud/docker/docker.go
pkg/cloud/kubernetes/kubernetes.go
pkg/server/manager/cloud.go

Fixes #
Reference to #
```release-note
NONE
```

feat:support username/password auth for k8s cluster

---

pkg/worker/scm/provider/git.go

Fixes #519 
Reference to #
```release-note
NONE
```

fix(worker):submodules can not be checkout while cloning repo

---

pkg/api/types.go
pkg/scm/provider/github.go
pkg/scm/provider/gitlab.go
pkg/scm/provider/helper.go
pkg/scm/provider/svn.go
pkg/scm/scm.go
pkg/server/router/oauth.go
pkg/server/router/router.go

Fixes 
Reference to #
@wzqnls @supereagle  @zhujian7 
```release-note
NONE
```

feat: add oauth api for gitlab

---

docs/quick-start.md
docs/quick-start_zh-CN.md
pkg/worker/stage/stage.go

Fixes partially #461 
Reference to #
/cc @cd1989 
```release-note
NONE
```

docs:update quick-start document

---

pkg/api/types.go
pkg/event/manager.go
pkg/worker/stage/stage.go

Fixes #
Reference to #
```release-note
NONE
```

feat:support build speedup for gradle

---

cmd/worker/worker.go

Fixes #
Reference to #
```release-note
NONE
```

fix(worker): worker create tag failed

---

docs/api/v1/api.md
pkg/api/types.go
pkg/cloud/kubernetes/kubernetes.go
pkg/event/manager.go
pkg/event/manager_test.go

Fixes #
Reference to #
```release-note
NONE
```

feat:support configuring resource quota for cyclone worker

---

pkg/api/types.go
pkg/docker/client.go
pkg/event/manager.go
pkg/event/manager_test.go

Fixes #
Reference to #
```release-note
NONE
```

chore:change WorkerConfig.Quota's type from struct to pointer

---

build/worker/start.sh

Fixes #
Reference to #
```release-note
NONE
```

feat(worker):update worker storage driver from vfs to overlay

---

build/worker/Dockerfile

Fixes #
Reference to #
```release-note
NONE
```

feat(worker):update dind version from 1.13.1 to 17.03.1-ce

---

pkg/server/router/webhook.go

Fixes #
Reference to #
```release-note
NONE
```

feat:push event webhook support configuring target branches

---

api/server/server.go

router.InitRouters() must be called before InstallSwaggerService, otherwise Swagger can't get the RegisteredWebServices.
Fixes #
Reference to #
/cc @supereagle
```release-note
NONE
```

fix(docs):router.InitRouters() must be called before InstallSwaggerService

---

pkg/docker/client.go
pkg/worker/stage/stage.go

Fixes #
Reference to #
```release-note
NONE
```

fix(worker):integration does not work because server start failed

---

pkg/worker/stage/stage.go
pkg/worker/stage/stage_test.go

Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

fix(#544): fix Dockerfile overwritten

---

pkg/event/manager.go

Fixes #528 
Reference to #
/cc @supereagle @bbbmj 
```release-note
NONE
```

fix: retry logic does not work

---

pkg/api/types.go
pkg/scm/provider/github/github.go
pkg/scm/provider/gitlab/gitlabv3.go
pkg/scm/provider/gitlab/gitlabv4.go
pkg/scm/provider/gitlab/helper.go
pkg/scm/provider/svn/svn.go
pkg/scm/scm.go
pkg/server/router/oauth.go
pkg/server/router/router.go

Fixes #
Reference to #
@wzqnls @zhujian7 @supereagle 
```release-note
NONE
```

feat(hr): add oauth api for gitlab

---

pkg/cloud/kubernetes/kubernetes.go
pkg/event/manager.go

Fixes #
Reference to #
```release-note
NONE
```

fix:delete related worker pod failed

---

pkg/worker/worker.go

Fixes #
Reference to #
@wzqnls @zhujian7 @supereagle 
```release-note
NONE
```

feat(hr): support to skip package stage

---

cmd/worker/options/options.go
pkg/api/types.go
pkg/cloud/docker/docker.go
pkg/cloud/kubernetes/kubernetes.go
pkg/event/manager.go
pkg/server/router/cloud.go

Fixes #
Reference to #
```release-note
NONE
```

feat: add project name and pipeline name while listing workers

---

docs/quick-start.md
docs/quick-start_zh-CN.md
pkg/worker/worker.go

Fixes #
Reference to #
```release-note
NONE
```

feat(worker): make package stage optional

---

pkg/worker/worker.go

Fixes #
Reference to #
```release-note
NONE
```

fix: add some prompt message when create scm tag failed

---

pkg/worker/scm/manager.go

Fixes #
Reference to #
/cc @supereagle @bbbmj 
```release-note
NONE
```

feat: add retry logic for code checkout

---

release/cyclone-server.yaml

Fixes #
Reference to #
```release-note
NONE
```

feat: add value charts

---

pkg/api/types.go
pkg/cloud/kubernetes/kubernetes.go
pkg/event/manager.go
pkg/scm/provider/github/github.go
pkg/scm/provider/gitlab/gitlabv3.go
pkg/scm/provider/gitlab/gitlabv4.go
pkg/scm/provider/gitlab/helper.go
pkg/scm/provider/svn/svn.go
pkg/scm/scm.go
pkg/server/router/oauth.go
pkg/server/router/router.go
pkg/worker/worker.go

I used cherry-pick after the previous rebase, causing some PR to have no rebase. So, re fix the previous rebase.
Fixes #
Reference to #
@wzqnls @zhujian7 @supereagle 
```release-note
NONE
```

feat(hr): fix rebase 

---

pkg/scm/provider/gitlab/gitlab.go
pkg/worker/cycloneserver/client.go

This is the official example:  https://golang.org/pkg/net/http/
```
resp, err := http.Get("http://example.com/")
if err != nil {
// handle error
}
defer resp.Body.Close()
body, err := ioutil.ReadAll(resp.Body)
// ...
```
Fixes #
Reference to #
```release-note
NONE
```

fix: close response body earlier

---

docs/api/v1/api.md
pkg/api/v1/descriptor/template.go
pkg/api/v1/handler/template.go
pkg/api/v1/handler/template_test.go

Fixes #
Reference to #
```release-note
NONE
```

fix: change the url path pipelinetemplates to configtemplates

---

pkg/server/manager/pipeline.go

Fixes #
Reference to #
```release-note
NONE
```

fix: delete notification config failed while updating pipeline

---

release/README.md
release/cyclone-server.yaml

Fixes #
Reference to #
```release-note
NONE
```

chore: change service type from NodePort to ClusterIP

---

pkg/server/manager/pipeline.go

Fixes #
Reference to #
```release-note
NONE
```

fix: can not delete pipeline while scm server is unavailable

---

docs/api/v1/api.md
docs/setup.md
docs/setup_zh-CN.md
pkg/api/types.go
pkg/api/v1/handler/webhook.go
pkg/api/v1/handler/webhook_test.go
pkg/event/manager.go
pkg/event/manager_test.go
pkg/scm/provider/github/github.go
pkg/scm/provider/gitlab/gitlab.go
pkg/scm/provider/gitlab/gitlabv3.go
pkg/scm/provider/gitlab/gitlabv4.go
pkg/scm/provider/svn/svn.go
pkg/scm/scm.go
pkg/server/manager/pipeline.go
pkg/server/options.go
pkg/server/server.go
pkg/util/http/errors/format.go
release/cyclone-server.yaml

Fixes #
Reference to #
```release-note
pr webhook supports display commit statuses
```

feature(webhook-pr):pr webhook support display commit statuses

---

pkg/api/types.go
pkg/event/manager.go
pkg/event/manager_test.go

Fixes #
Reference to #
```release-note
NONE
```

feat: add pipeline record web url for notification

---

pkg/worker/junit/report_test.go

Fixes #
Reference to #
```release-note
NONE
```

test: add test cases for collect JUnit test

---

release/cyclone-server.yaml

Fixes #
Reference to #
```release-note
NONE
```

chore(release): update release yaml typo

---

config/templates/templates.yaml

Fixes #
Reference to #
```release-note
NONE
```

chore(templates): add commands for collecting golang JUnit test reports

---

release/cyclone-server.yaml

Fixes #
Reference to #
/cc @liwandaniel 
```release-note
NONE
```

chore(release): update release yaml

---

pkg/docker/client.go

Fixes #
Reference to #
```release-note
NONE
```

fix(nit): delete encoded/unreabable commands in error message

---

pkg/api/v1/handler/webhook.go

webhook triggered multi times, because gitlab webhook response body is invalid.
Fixes #
Reference to #
```release-note
NONE
```

fix: gitlab webhook response body is invalid

---

pkg/api/v1/handler/webhook.go
pkg/event/manager.go
pkg/scm/provider/github/github.go
pkg/scm/provider/gitlab/gitlabv3.go
pkg/scm/provider/gitlab/gitlabv4.go
pkg/scm/provider/svn/svn.go
pkg/scm/scm.go
pkg/server/manager/project.go
pkg/util/gitlab/helper.go

Fixes #
Reference to #
```release-note
NONE
```

feature(webhook):pr comment webhook supports display commit statuses

---

pkg/server/manager/pipeline.go
pkg/server/manager/project.go

Fixes #
Reference to #
```release-note
NONE
```

fix: alias and description can not be updated to empty

---

README.md
README_zh-CN.md

add community information
Fixes #
Reference to #
```release-note
NONE
```

docs(README): add community information

---

build/worker/Dockerfile

Fixes #
Reference to #
```release-note
NONE
```

feat(dind) change dind verdion from 17.03.1-ce to 18.03.1-ce

---

build/server/Dockerfile
docs/api/v1/api.md
pkg/api/types.go
pkg/api/v1/descriptor/webhook.go
pkg/api/v1/handler/webhook.go
pkg/api/v1/handler/webhook_test.go
pkg/scm/provider/github/github.go
pkg/scm/provider/gitlab/gitlabv3.go
pkg/scm/provider/gitlab/gitlabv4.go
pkg/scm/provider/svn/svn.go
pkg/scm/scm.go
pkg/server/manager/pipeline.go
pkg/store/pipeline.go
pkg/util/http/http.go
pkg/worker/scm/provider/svn.go

Fixes #
Reference to #
/cc @supereagle @cd1989 @qiuxiaolian 
```release-note
NONE
```

feat(svn): support svn post-commit hook

---

pkg/api/helper.go
pkg/api/helper_test.go
pkg/event/manager.go
pkg/scm/provider/github/github.go
pkg/scm/provider/gitlab/gitlab.go
pkg/scm/provider/gitlab/gitlabv3.go
pkg/scm/provider/gitlab/gitlabv4.go
pkg/scm/provider/svn/svn.go
pkg/scm/scm.go
pkg/server/manager/pipelineRecord.go
pkg/util/http/errors/format.go
pkg/util/regex/regex.go
pkg/util/regex/regex_test.go
pkg/worker/scm/manager.go
pkg/worker/scm/manager_test.go

Support trigger pipeline manually by GitHub pull requests or GitLab merge requests.
How to use it:
When creating pipeline record, you should deliver your pr/mr ID by 'ref' field using the following format:
- GitHub: `refs/pull/{id}/merge`
- GitLab: `refs/merge-requests/{iid}/head`
Fixes #
Reference to #
/cc @supereagle @cd1989 @qiuxiaolian 
```release-note
NONE
```

feat: support trigger pipeline manually by pr

---

build/workflow/resolver/git/Dockerfile
build/workflow/resolver/git/entrypoint.sh
build/workflow/resolver/image/Dockerfile
build/workflow/resolver/image/entrypoint.sh
build/workflow/resolver/kv/Dockerfile
build/workflow/resolver/kv/entrypoint.sh

Implements basic resource resolvers.
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

Resource resolvers

---

Makefile
build/workflow/coordinator/Dockerfile
cmd/workflow/coordinator/main.go
pkg/apis/cyclone/v1alpha1/common.go
pkg/apis/cyclone/v1alpha1/stage_template.go
pkg/common/constants/constant.go
pkg/workflow/coordinator/common/types.go
pkg/workflow/coordinator/coordinator.go
pkg/workflow/coordinator/helper.go
pkg/workflow/coordinator/k8sapi/k8sapi.go

add coordinator sidecar to:
- collect logs
- wait for all workload containers completion
- notify output resolver to start to work
- collect artifacts
- copy resources
Fixes #
Reference to #
```release-note
NONE
```

feat(coordinator): add coordinator component

---

pkg/apis/cyclone/v1alpha1/workflow_trigger.go

Update for WorkflowTrigger
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

fix: update WorkflowTrigger crd

---

pkg/api/v1/handler/webhook.go

Fixes #
Reference to #
```release-note
NONE
```

feat: turn on cache dependency if pipeline configured it

---

Gopkg.lock
pkg/apis/cyclone/v1alpha1/workflow_trigger.go
pkg/workflow/workflowrun/operator.go
pkg/workflow/workflowrun/pod.go
pkg/workflow/workflowrun/utils.go

Set WorkflowRun's owner reference to Workflow.
Fixes #
Reference to #
```release-note
NONE
```

feat: add owner reference to Workflow

---

Gopkg.lock
Gopkg.toml
vendor/github.com/pkg/errors/.gitignore
vendor/github.com/pkg/errors/.travis.yml
vendor/github.com/pkg/errors/LICENSE
vendor/github.com/pkg/errors/README.md
vendor/github.com/pkg/errors/appveyor.yml
vendor/github.com/pkg/errors/bench_test.go
vendor/github.com/pkg/errors/errors.go
vendor/github.com/pkg/errors/errors_test.go
vendor/github.com/pkg/errors/example_test.go
vendor/github.com/pkg/errors/format_test.go
vendor/github.com/pkg/errors/stack.go
vendor/github.com/pkg/errors/stack_test.go
vendor/github.com/robfig/cron/.gitignore
vendor/github.com/robfig/cron/.travis.yml
vendor/github.com/robfig/cron/LICENSE
vendor/github.com/robfig/cron/README.md
vendor/github.com/robfig/cron/constantdelay.go
vendor/github.com/robfig/cron/constantdelay_test.go
vendor/github.com/robfig/cron/cron.go
vendor/github.com/robfig/cron/cron_test.go
vendor/github.com/robfig/cron/doc.go
vendor/github.com/robfig/cron/parser.go
vendor/github.com/robfig/cron/parser_test.go
vendor/github.com/robfig/cron/spec.go
vendor/github.com/robfig/cron/spec_test.go

Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

fix: update vendors

---

pkg/workflow/controller/controllers/configmap.go
pkg/workflow/controller/controllers/controller.go
pkg/workflow/controller/controllers/pod.go
pkg/workflow/controller/controllers/workflow_trigger.go
pkg/workflow/controller/controllers/workflowrun.go
pkg/workflow/controller/handlers/workflowTrigger/handler.go
pkg/workflow/controller/handlers/workflowtrigger/cron_job.go

- Rename packages to follow consistently styles
- Use informers generated
Fixes #
Reference to #
```release-note
NONE
```

Code improve

---

pkg/workflow/controller/controllers/configmap.go
pkg/workflow/controller/controllers/pod.go
pkg/workflow/controller/controllers/workflow_trigger.go
pkg/workflow/controller/controllers/workflowrun.go

Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

chore: adjust default resync period

---

.travis.yml
pkg/workflow/controller/controllers/pod.go
pkg/workflow/controller/controllers/workflowrun.go

Fixes #
Reference to #
```release-note
NONE
```

chore: add travis yaml

---

pkg/server/apis/v1alpha1/descriptor/workflowrun.go
pkg/server/apis/v1alpha1/descriptor/workflowtrigger.go
pkg/server/apis/v1alpha1/handler/stage.go

Fixes #
Reference to #
/cc @cd1989 @cd1989 
```release-note
NONE
```

fix(server): fix URL for workflowrun and workflowtrigger

---

Makefile

Fixes #
Reference to #
```release-note
NONE
```

chore(Makefile): add target 'container-local' for Makefile

---

build/workflow/resolver/git/entrypoint.sh
build/workflow/resolver/image/entrypoint.sh
build/workflow/resolver/kv/entrypoint.sh
manifests/cyclone.yaml
manifests/examples/ci.yaml
manifests/examples/secrets.yaml
manifests/examples/wfr.yaml
pkg/apis/cyclone/v1alpha1/resource.go
pkg/workflow/controller/handlers/pod/handler.go
pkg/workflow/workflowrun/pod.go

- Resolve resources conflict problem. In one WorkflowRun, if multiple stages want to pull the same resources, at last only one stage would get the chance to execute the pulling, others would wait for the resource to be ready.
- Fix problems when create volumes from different input resources with same PVC. Can't create different volumes for the same PVC.
- Fix pod processing when controller restarted.
Fixes #
Reference to #
```release-note
NONE
```

fix: resolve images problems

---

pkg/workflow/workflowrun/pod.go

Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

fix: inject envs to stage pod

---

docs/api/v1/api.md
pkg/api/v1/descriptor/project.go
pkg/api/v1/handler/project.go
pkg/scm/provider/github/github.go
pkg/scm/provider/gitlab/gitlabv3.go
pkg/scm/provider/gitlab/gitlabv4.go
pkg/scm/provider/svn/svn.go
pkg/scm/scm.go
pkg/server/manager/project.go
pkg/worker/stage/helper_test.go
pkg/worker/stage/stage_test.go

Add API to support list Dockerfiles in the repo.
Implemented:
- GitHub
- GitLab v4 API
Not Implemented:
- **GitLab v3 API**
- SVN
Fixes #
Reference to #
```release-note
NONE
```

feat(api): add api to support list Dockerfiles in the repo

---

build/worker/start.sh
pkg/cloud/docker/docker.go
pkg/cloud/kubernetes/kubernetes.go
pkg/cloud/provider.go
release/cyclone-server.yaml

Fixes #
Reference to #
/cc @cd1989 @liwandaniel @supereagle 
```release-note
NONE
```

feat: support adding registry cert files to cyclone worker

---

manifests/cyclone.yaml
pkg/workflow/controller/config.go
pkg/workflow/controller/handlers/pod/operation.go
pkg/workflow/workflowrun/pod.go

Configure quota in Workflow Controller, then apply them if pod containers have no quota specified.
If you don't want to apply default quota, just remove the quota configure in Workflow Controller.
Fixes #
Reference to #
```release-note
NONE
```

feat: configure and apply default quota to pod containers

---

cmd/worker/worker.go
pkg/cloud/docker/docker.go
pkg/cloud/provider.go
pkg/scm/provider/github/github.go
pkg/util/os/os.go
pkg/worker/scm/provider/svn.go
pkg/worker/worker.go

Fixes #
Reference to #
```release-note
NONE
```

chore: fix typo

---

manifests/cyclone.yaml

`Mi` or `M` for memory unit, refer to https://github.com/kubernetes/kubernetes/issues/49442
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

fix: use correct memory unit in quota

---

build/workflow/resolver/git/entrypoint.sh
build/workflow/resolver/image/entrypoint.sh
manifests/examples/ci.yaml

Some problems left in the resource resolvers, fix them.
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

fix: resovlers

---

pkg/worker/worker.go

Fixes #642 
Reference to #
/cc @C0reFast @cd1989 
```release-note
NONE
```

fix: pipeline is stuck when package step execution successfully

---

pkg/integrate/manager.go
pkg/integrate/provider/sonar/sonar.go
pkg/server/manager/pipeline.go

Fixes #
Reference to #
```release-note
NONE
```

feat: delete sonar project while deleting associated pipeline

---

pkg/event/manager.go
pkg/integrate/manager.go
pkg/server/manager/pipeline.go

Fixes #
Reference to #
```release-note
NONE
```

fix(sonarqube): create sonar project failed since pipeline id is empty

---

manifests/cyclone.yaml
manifests/examples/simple.yaml
pkg/workflow/common/const.go
pkg/workflow/controller/config.go
pkg/workflow/workflowrun/pod.go
pkg/workflow/workflowrun/utils.go

Make default PVC and secret optional. When PVC is missing, resource won't be shared among stages, and artifact is unsupported.
When secret is missing, no docker registry auth is available, so push image is unsupported.
Cyclone will manage PVC and secrets in the future when manage namespaces, or tenants.
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

improve: make pv and secret optional

---

pkg/integrate/provider/fake/fake.go
pkg/integrate/provider/sonar/sonar_test.go
pkg/util/os/os_test.go
pkg/worker/stage/stage_test.go
pkg/worker/worker_test.go

Fixes #
Reference to #
```release-note
NONE
```

test: add some tests for code scanning

---

pkg/worker/scm/manager.go
pkg/worker/scm/provider/git.go

Git cloning code is usually stuck by the network problem, add timeout mechanism for the git clone.
More info:
- https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables
- https://stackoverflow.com/questions/6458790/is-there-a-way-to-make-git-over-http-timeout
Fixes #
Reference to #
```release-note
NONE
```

feat: controll timeout of git clone

---

config/templates/templates.yaml
pkg/api/types.go
release/cyclone-server.yaml

Fixes #
Reference to #https://github.com/caicloud/platform-requirements/issues/73
```release-note
NONE
```

fix: support multi dockerfiles for one template

---

manifests/cyclone.yaml

Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

chore: map timezone of host

---

pkg/server/manager/pipeline.go

Fixes #
Reference to #
```release-note
NONE
```

fix: should use new git resource url to create webhook

---

pkg/integrate/provider/sonar/sonar.go

Fixes #
Reference to #
```release-note
NONE
```

fix: change sonar link from measures to overview

---

.gitignore
pkg/cloud/kubernetes/kubernetes.go

cyclone support self-signed certificate by configuring 'CERT_DATA' environment, and the cert data value need to be base64 encoded.
Fixes #
Reference to #
```release-note
NONE
```

fix: use base64 encoded cert

---

pkg/workflow/controller/handlers/workflowtrigger/cron_job.go

- 接收一个前端传过来的时区信息做一下修正，使其按客户预期时间触发workflow
Fixes #
Reference to #
/cc @supereagle @cd1989  @zhujian7 
```release-note
NONE
```

fix(trigger): support timezone for workflowTrigger

---

Makefile
manifests/cyclone.yaml
pkg/workflow/common/const.go
pkg/workflow/coordinator/coordinator.go
pkg/workflow/coordinator/k8sapi/k8sapi.go
pkg/workflow/workflowrun/pod.go

Allow a user to specify PVC for output resource, so that Cyclone can mount the resource directly
Fixes #
Reference to #
```release-note
NONE
```

fix: allow user to configure pvc and path in output resource

---

pkg/api/types.go
pkg/worker/stage/helper.go
pkg/worker/worker.go

Fixes #
Reference to #
```release-note
NONE
```

fix: can not record error message for allow-failure stages

---

pkg/workflow/common/const.go
pkg/workflow/controller/handlers/workflowtrigger/cron_job.go

- 给trigger创建的wfr加上label，使之能被list请求到
- 相关issue: https://github.com/caicloud/clever-quality/issues/375
Fixes #
Reference to #
/assign @cd1989 
```release-note
NONE
```

fix(trigger): add label for workflowRun created by trigger

---

manifests/cyclone.yaml

Access to Cyclone Server from different namespaces.
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

fix: cyclone server address for pod in different ns

---

web/src/components/project/component/ProjectDetail.js
web/src/components/workflow/component/list.js
web/src/layout/Breadcrumb.js
web/src/layout/index.js
web/src/store/workflow.js

- bread crunmb nav
Fixes #
Reference to #
/cc @cd1989 @caosm 
```release-note
NONE
```

feat(*): add breadcrumb

---

web/config/middleware/mockServerMiddleware.js
web/config/webpackDevServer.config.js
web/mock/example.js
web/package.json
web/src/api/http.js

add mockServer middleware
example:
```
'GET /api/example': (req, res) => {
res.json({
query: req.query,
});
},
```
priority: `mock` > `proxy`
Fixes #
Reference to https://github.com/caicloud/cyclone/issues/684  (set proxy to solve cors)
/cc @qiuxiaolian @artecher @huxiangtao 
```release-note
NONE
```

feat(web): add mockServerMiddleware & set api-proxy

---

Makefile
build/web/Dockerfile
build/web/Dockerfile.multistage
release/README.md
release/cyclone-server.yaml
release/cyclone-web.yaml
release/workflow-controller.yaml

Fixes #
Reference to #
```release-note
NONE
```

chore: add release yaml file

---

release/cyclone-web.yaml
release/workflow-controller.yaml

Fixes #
Reference to #
```release-note
NONE
```

fix(release): fix cyclone web release

---

release/cyclone-server.yaml
release/workflow-controller.yaml

* default_resource_quota： Without default_resource_quota can't start pod
* native-cyclone-server：This causes the pv name to be created too long
Fixes #
Reference to #
```release-note
NONE
```

fix: fix bug of release chart

---

pkg/workflow/controller/handlers/workflowtrigger/cron_job.go

Fixes #
Reference to #
/assign @cd1989 
```release-note
NONE
```

fix(trigger): break on success or failed

---

pkg/workflow/controller/handlers/workflowtrigger/cron_job.go

Fixes #
Reference to #
/assign @cd1989 @zhujian7 
```release-note
NONE
```

fix(trigger): fix import error

---

web/src/components/project/component/ProjectDetail.js
web/src/components/public/detail/Action.js
web/src/components/public/detail/index.js
web/src/components/public/detail/index.md
web/src/layout/index.js
web/src/less/inc.var.less
web/src/less/index.less
web/src/less/u-detail.less

- 
Fixes #
Reference to #
/cc @cd1989 
```release-note
NONE
```

feat(*): sideNav add collapsible prop and detail component add action

---

web/src/components/integration/component/DataForm.js
web/src/components/integration/component/List.js
web/src/components/integration/index.js
web/src/layout/index.js
web/src/locale/en-US.json
web/src/locale/zh-CN.json
web/src/routes/index.js
web/src/store/index.js
web/src/store/integration.js

add web ui for integration center
Fixes #
Reference to #
/cc @qiuxiaolian @caosm @artecher 
```release-note
NONE
```

feat(integrationCenter): add integration center module

---

CONTRIBUTING.md
README.md

R.T
Fixes #
Reference to #
/cc @cd1989 
```release-note
NONE
```

chore: update README

---

web/src/components/integration/component/List.js
web/src/locale/en-US.json
web/src/locale/zh-CN.json

Fixes #
Reference to #
/cc @qiuxiaolian @caosm 
```release-note
NONE
```

fix(inteigrationCenter): fix bug for removing ref Deprecated feature

---

pkg/api/types.go
pkg/scm/scm.go

Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

feat:add OAuth authType for Oauth way to create project

---

docs/ROADMAP.md

Fixes #
Reference to #
/cc @supereagle @zhujian7 @qiuxiaolian @artecher 
```release-note
NONE
```

docs: add roadmap

---

CONTRIBUTING.md

Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

docs: update CONTRIBUTING docs to add go lint

---

pkg/workflow/controller/handlers/pod/operation.go

Fixes #
Reference to #
```release-note
NONE
```

Enhance the update of stage status

---

manifests/cyclone.yaml
release/cyclone-server.yaml
release/workflow-controller.yaml

- unify port of cyclone server to 7099
Fixes #
Reference to #
/cc @cd1989 
```release-note
NONE
```

fix: fix coordinator can not connect to cyclone server

---

pkg/server/apis/v1alpha1/descriptors/integration.go
pkg/server/apis/v1alpha1/types.go
pkg/server/common/cluster.go
pkg/server/common/const.go
pkg/server/common/utils.go
pkg/server/handler/v1alpha1/integration.go
pkg/server/handler/v1alpha1/tenant.go

- integration CRUD
Fixes #
Reference to #671 
```release-note
NONE
```

feat(api): add api for integration

---

Makefile

Fixes #
Reference to #
https://github.com/caicloud/cyclone/issues/741
/cc @zhujian7 
```release-note
NONE
```

fix: use docker hub in Makefile

---

manifests/cyclone.yaml
pkg/workflow/controller/config.go
pkg/workflow/workflowrun/pod.go

Add dev mode to workflow controller, in dev mode, image pull policy is always.
Fixes #
Reference to #
```release-note
NONE
```

chore: add dev mode to workflow controller

---

Makefile

Makefile use some bash syntax, in Ubuntu, the default shell used in make is sh, this make the `make` tool not work.
Fixes #
Reference to #
https://github.com/caicloud/cyclone/issues/741
/cc @zhujian7 
```release-note
NONE
```

fix: use bash in make

---

.dockerignore
Makefile
README.md
manifests/cyclone.yaml.template

To correct the *Quick Start* by use make tool to deploy.
Fixes #
Reference to #
```release-note
NONE
```

chores: update Makefile for deploy and undeploy

---

web/src/components/project/component/addProject/IntegrationSelect.js
web/src/less/inc.var.less
web/src/store/stageTemplate.js

Fixes #
Reference to #
/cc @caosm 
```release-note
NONE
```

fix(*): fix mobx does not contain an export named useStrict error

---

web/package.json
web/src/components/integration/component/List.js
web/src/store/integration.js

- connect backend-end
Fixes #
Reference to #
/cc @caosm @cd1989 
```release-note
NONE
```

feat(*): connect back-end

---

web/config/webpack.config.prod.js

ProvidePlugin: add React same as [config.dev](https://github.com/caicloud/cyclone/blob/master/web/config/webpack.config.dev.js#L288)
so that it's not necessary `import React from 'react'` in all files
Fixes #
Reference to #
```release-note
NONE
```

chore: add React into ProvidePlugin

---

build/web/nginx.conf
web/package.json

- Fix Nginx config for Cyclone Web, use `apis` instead of `api`.
- Add env `REACT_APP_API_BASE_URL=/apis/v1alpha1` to `npm build`
Fixes #
Reference to #
/cc @zhujian7 @qiuxiaolian 
```release-note
NONE
```

Fix Cyclone Web connect back-end problem in production mode

---

web/src/api/index.js
web/src/components/project/component/List.js
web/src/components/project/component/ProjectDetail.js
web/src/components/project/component/addProject/FormContent.js
web/src/components/project/component/addProject/FormWrap.js
web/src/components/project/component/addProject/IntegrationSelect.js
web/src/components/project/index.js
web/src/components/public/inputWithUnit/InputWithUnit.js
web/src/components/public/quota/QuotaSetting.js
web/src/consts/validate.js
web/src/store/integration.js
web/src/store/project.js

- update project，
- quota Initialize
Fixes #
Reference to #
/cc @cd1989 @huxiangtao 
```release-note
NONE
```

feat(*): project update

---

web/src/components/project/component/List.js
web/src/components/project/component/MenuAction.js
web/src/components/project/component/ProjectDetail.js
web/src/components/project/component/addProject/FormWrap.js
web/src/components/project/index.js
web/src/components/public/ellipsisMenu/index.js
web/src/store/project.js

- extract project menu action as a compoennt
- change project route params projectId to projectName
Fixes #
Reference to #
```release-note
NONE
```

perf(*): extract menu actions as a component

---

web/src/api/index.js
web/src/components/integration/component/DataForm.js
web/src/components/integration/component/List.js
web/src/components/project/component/addProject/IntegrationSelect.js
web/src/components/project/component/detail/index.js
web/src/components/project/component/detail/resource.js
web/src/components/project/component/detail/stage.js
web/src/components/project/index.js
web/src/locale/en-US.yaml
web/src/locale/zh-CN.yaml
web/src/store/project.js

- list project detail resource and stage
Fixes #
Reference to #
```release-note
NONE
```

feat(*): add resource list and stage list

---

web/src/components/project/component/List.js
web/src/components/project/component/MenuAction.js
web/src/components/project/component/addProject/FormContent.js
web/src/components/project/component/addProject/FormWrap.js

- modify project field name to alias
- fix some proptypes warning
Fixes #
Reference to #
```release-note
NONE
```

feat(*): modify project name to  alias and fix some proptypes warning

---

web/src/locale/en-US.yaml
web/src/locale/zh-CN.yaml

- quota validate text
Fixes #
Reference to #
/cc @cd1989 @huxiangtao 
```release-note
NONE
```

feat(*): perfect quota validate text

---

pkg/server/apis/v1alpha1/types.go
pkg/server/common/cluster.go
pkg/server/common/const.go
pkg/server/common/utils.go
pkg/server/handler/v1alpha1/helper.go
pkg/server/handler/v1alpha1/integration.go
pkg/server/handler/v1alpha1/project.go
pkg/server/handler/v1alpha1/resource.go
pkg/server/handler/v1alpha1/stage.go
pkg/server/handler/v1alpha1/template.go
pkg/server/handler/v1alpha1/tenant.go
pkg/server/handler/v1alpha1/workflow.go
pkg/server/handler/v1alpha1/workflowrun.go
pkg/server/handler/v1alpha1/workflowtrigger.go

unify metadata of cyclone resources
Fixes #
Reference to #
/cc @cd1989 @supereagle @qiuxiaolian @huxiangtao @caosm 
```release-note
NONE
```

fix(api): unify metadata of cyclone resources

---

web/src/routes/index.js

Remove resource route as it's not necessary now.
Fixes #
Reference to #
```release-note
NONE
```

fix: remove resource route

---

README.md

Fixes #
Reference to #
```release-note
NONE
```

fix: tyo in readme

---

examples/cicd/generate.sh
examples/cicd/golang/manifests.yaml.template
examples/cicd/java/manifests.yaml.template
examples/cicd/nodejs/manifests.yaml.template

Add new ci examples, nodejs, java
Fixes #
Reference to #
```release-note
NONE
```

chores: add ci examples for nodejs, java

---

pkg/server/handler/v1alpha1/integration.go

When update integration, label doesn't be updated.
Fixes #780
Reference to #
```release-note
NONE
```

fix: update label when change integration type

---

web/src/components/public/KeyValue/README.md
web/src/components/public/KeyValue/index.js
web/src/components/public/KeyValue/keyValue.module.less

K-V component
example:
Fixes #
Reference to #
/cc @qiuxiaolian @huxiangtao 
```release-note
NONE
```

feat(web): add component to display K-V

---

pkg/server/handler/v1alpha1/tenant.go

add description and alias for default tenant and cluster
Fixes #
Reference to #
```release-note
NONE
```

chore: add description and alias for default tenant and cluster

---

cmd/server/main.go
manifests/cyclone.yaml.template
pkg/server/config/config.go
pkg/server/handler/v1alpha1/tenant.go
release/cyclone-server.yaml

configure cyclone server by configmap instead of flags
Fixes #
Reference to #
```release-note
NONE
```

refactor(server): configure cyclone server by configmap

---

docs/design.md

Fixes #
Reference to #
```release-note
NONE
```

docs(design): add functional modules

---

web/src/components/integration/component/createIntegration/FormContent.js
web/src/components/integration/component/createIntegration/FormWrap.js
web/src/components/integration/component/createIntegration/SelectSourceType.js
web/src/components/integration/component/createIntegration/validate.js

replace integration data source type key to Camel-Case format
Fixes #
Reference to #
/cc @caosm @cd1989 @qiuxiaolian 
```release-note
NONE
```

chore(integrationCenter):modify integration data source type key 

---

pkg/server/config/config.go
pkg/server/handler/v1alpha1/integration.go
pkg/server/handler/v1alpha1/tenant.go
pkg/util/cerr/error.go

- return success if ns,quota,pvc exist while open worker cluster
- return a specific error to indicate creating control cluster integration error while creating tenant
- do not open the control cluster to run workflow while creating tenant
- some refactor about give default value to cyclone server config
Fixes #
Reference to #
```release-note
NONE
```

fix: return success if ns,quota,pvc exist while open worker cluster

---

manifests/cyclone.yaml.template
release/cyclone-server.yaml

Fixes #
Reference to #
```release-note
NONE
```

fix: fix default pvc size unit

---

web/src/components/integration/component/createIntegration/FormContent.js
web/src/components/integration/component/createIntegration/FormWrap.js
web/src/components/integration/component/createIntegration/SelectSourceType.js
web/src/components/integration/component/createIntegration/validate.js
web/src/components/integration/component/formGroup/Cluster/IsWorkerCluster.js
web/src/components/integration/component/formGroup/Cluster/SwitchField.js
web/src/components/integration/component/formGroup/Cluster/ValidateSelect.js
web/src/components/integration/component/formGroup/Cluster/WorkerCluster.js
web/src/components/integration/component/formGroup/Cluster/index.js
web/src/components/integration/component/formGroup/ScmGroup/Forms/SVN.js
web/src/components/integration/component/formGroup/ScmGroup/Forms/ValidateSelect.js
web/src/consts/const.js
web/src/less/u.integrationCenter.less
web/src/locale/en-US.yaml
web/src/locale/zh-CN.yaml
web/src/store/integration.js

外部系统来源 新增集群类型
Fixes #
Reference to #
/cc @caosm @qiuxiaolian @dd1989 
```release-note
NONE
```

feat(integrationCenter): add cluster type for data source

---

pkg/server/handler/v1alpha1/helper.go

Fixes #
Reference to #
```release-note
NONE
```

fix: return code should be 409 while creating resource conflict

---

pkg/server/apis/v1alpha1/types.go

Fixes #
Reference to #
```release-note
NONE
```

chore: add authType field in SCMSource

---

manifests/templates/cicd/build.yaml
manifests/templates/cicd/code-scan.yaml
manifests/templates/cicd/image-build.yaml
manifests/templates/cicd/unit-test.yaml
pkg/server/apis/v1alpha1/descriptors/template.go
pkg/server/common/const.go
pkg/server/common/utils.go
pkg/server/handler/v1alpha1/helper.go
pkg/server/handler/v1alpha1/integration.go
pkg/server/handler/v1alpha1/project.go
pkg/server/handler/v1alpha1/template.go

fix bug that can not get built in stage template
Fixes #
Reference to #
```release-note
NONE
```

fix(server): can not get built in stage template

---

manifests/templates/cicd/build.yaml
manifests/templates/cicd/code-scan.yaml
manifests/templates/cicd/image-build.yaml
manifests/templates/cicd/unit-test.yaml

Fixes #
Reference to #
/cc @cd1989 
```release-note
NONE
```

fix: add semicolon at end of line for template

---

build/web/nginx.conf
manifests/cyclone.yaml.template
pkg/workflow/common/const.go
release/cyclone-server.yaml
release/workflow-controller.yaml

change cyclone server name to `cyclone-server`
Fixes #
Reference to #
```release-note
NONE
```

fix: change cyclone server name to cyclone-server

---

docs/design.md
docs/swagger-api-docs.md

More low-level language fixes
Fixes #
Reference to #
```release-note
NONE
```

More low-level language fixes

---

docs/ROADMAP.md

as suggested in title
Fixes #
Reference to #
```release-note
NONE
```

minor low-level language fixes

---

Makefile
build/web/Dockerfile.local
release/cyclone-web.yaml

Building cyclone-web image from local  is not convenient, add Make target `container-web-local` to simplify it.
Fixes #
Reference to #
```release-note
NONE
```

chore: build cyclone-web from local

---

build/resolver/image/entrypoint.sh

Support give image by (registry, repo, tag), and allow pass basic authentication information in the image resolver.
Fixes #
Reference to #
```release-note
NONE
```

feat: flexible image resolver and allow pass credential

---

cmd/server/main.go
pkg/server/handler/init.go
pkg/server/handler/v1alpha1/tenant.go

Some fix to code styles in cyclone server.
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

chore: improve code styles

---

pkg/server/apis/v1alpha1/types.go
pkg/server/handler/v1alpha1/integration.go
pkg/workflow/controller/handlers/workflowrun/handler.go
pkg/workflow/workflowrun/operator.go
pkg/workflow/workflowrun/pod.go

`startTime` is set to nil when update workflowrun, this PR will keep it unchanged
Fixes #
Reference to #
```release-note
NONE
```

fix: keep startTime of status unchanged

---

cmd/workflow/coordinator/main.go
pkg/workflow/common/const.go
pkg/workflow/common/event_recorder.go
pkg/workflow/coordinator/coordinator.go
pkg/workflow/coordinator/helper.go
pkg/workflow/coordinator/k8sapi/k8sapi.go
pkg/workflow/workflowrun/pod.go

coordinator cannot get cyclone resources(stage,workflowrun,resources) from a different namespace. This pr refactor coordinator make it get cyclone resources from env
Fixes #757 
Reference to #
```release-note
NONE
```

refactor(coordinator): coordinator get cyclone resources from env

---

build/resolver/image/entrypoint.sh

Separate AUTH argument to USER, PASSWORD in image resource resolver.
Fixes #
Reference to #
```release-note
NONE
```

refactor: seperate auth to user, password in image resolver

---

build/resolver/image/entrypoint.sh

Allow anonymously pull/push in image resolver.
Fixes #
Reference to #
```release-note
NONE
```

fix: allow anonymous user in image resolver

---

pkg/workflow/common/const.go
pkg/workflow/workflowrun/name.go
pkg/workflow/workflowrun/name_test.go
pkg/workflow/workflowrun/operator.go
pkg/workflow/workflowrun/pod.go
pkg/workflow/workflowrun/pod_test.go

Make pod names, container names shorter for easy use.
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

refactor: shorten names

---

pkg/workflow/controller/handlers/pod/operation.go

When a WorkflowRun has already been judged terminated, no need to handle pod update any more.
Fixes #
Reference to #
```release-note
NONE
```

fix: avoid handle pod when wfr terminated

---

pkg/workflow/controller/controllers/workflowrun.go
pkg/workflow/controller/handlers/pod/operation.go
pkg/workflow/controller/handlers/workflowrun/handler.go
pkg/workflow/workflowrun/gc.go
pkg/workflow/workflowrun/operator.go

Execute GC when on wfr is deleted: remove pods, clean pvc
Fixes #
Reference to #
```release-note
NONE
```

fix: gc when wfr deleted

---

pkg/server/common/const.go
pkg/server/common/utils.go
pkg/server/handler/v1alpha1/helper.go
pkg/server/handler/v1alpha1/integration.go
pkg/server/handler/v1alpha1/project.go
pkg/server/handler/v1alpha1/resource.go
pkg/server/handler/v1alpha1/stage.go
pkg/server/handler/v1alpha1/template.go
pkg/server/handler/v1alpha1/tenant.go
pkg/server/handler/v1alpha1/workflow.go
pkg/server/handler/v1alpha1/workflowrun.go
pkg/server/handler/v1alpha1/workflowtrigger.go
pkg/workflow/common/const.go
pkg/workflow/controller/handlers/workflowtrigger/cron_job.go

Add workflow label for workflowrun to restrict listing workflowrun
Fixes #
Reference to #
```release-note
NONE
```

feat: add workflow label for workflowrun

---

pkg/server/handler/v1alpha1/integration.go

Fixes #
Reference to #
```release-note
NONE
```

fix(server): fix integration update panic when it does not exist

---

.github/PULL_REQUEST_TEMPLATE.md

Fixes #
Reference to #
```release-note
NONE
```

chore(*): update pr template

---

release/workflow-controller.yaml

Fixes #
Reference to #
/cc @liwandaniel @cd1989 @supereagle 
```release-note
NONE
```

chore: update release yaml

---

Makefile
pkg/server/apis/v1alpha1/descriptors/workflowrun.go
pkg/server/handler/v1alpha1/helper.go
pkg/server/handler/v1alpha1/workflowrun.go
pkg/util/http/http.go
pkg/workflow/coordinator/coordinator.go
pkg/workflow/coordinator/cycloneserver/client.go
pkg/workflow/coordinator/k8sapi/k8sapi.go

The log collection API in cyclone server have changed, This PR aims to fix it.
Fixes #
Reference to #
```release-note
NONE
```

fix: fix coordinator collecting logs error

---

pkg/server/handler/v1alpha1/integration.go
pkg/server/handler/v1alpha1/project.go
pkg/server/handler/v1alpha1/resource.go
pkg/server/handler/v1alpha1/stage.go
pkg/server/handler/v1alpha1/template.go
pkg/server/handler/v1alpha1/tenant.go
pkg/server/handler/v1alpha1/workflow.go
pkg/server/handler/v1alpha1/workflowrun.go
pkg/server/handler/v1alpha1/workflowtrigger.go
pkg/util/cerr/error.go
pkg/util/cerr/error_test.go

If directly return k8s error, the http status code will be always `500`, and there is no detailed error messages. Need to convert k8s errors to Cyclone defined errors.
The implementation of this PR is not friendly for developers: have to check the returned errors of k8s API and convert it if it is not nil. Need to find a better way for this later.
Fixes #820
Reference to #
```release-note
NONE
```

feat(server): normalize status code for server apis

---

pkg/server/handler/v1alpha1/integration.go
pkg/server/handler/v1alpha1/tenant.go

delete tenant should close workload cluster (delete pvc and resourcequota created by cyclone) first
Fixes #
Reference to #
```release-note
NONE
```

fix: delete tenant should close workload cluster firstly

---

pkg/server/common/const.go
pkg/server/handler/v1alpha1/helper.go
pkg/server/handler/v1alpha1/integration.go
pkg/server/handler/v1alpha1/project.go
pkg/server/handler/v1alpha1/resource.go
pkg/server/handler/v1alpha1/stage.go
pkg/server/handler/v1alpha1/template.go
pkg/server/handler/v1alpha1/tenant.go
pkg/server/handler/v1alpha1/workflow.go
pkg/server/handler/v1alpha1/workflowrun.go
pkg/server/handler/v1alpha1/workflowtrigger.go

- change tenant prefix from `cyclone--` to `cyclone-`
- when creating tenant, if the relevant namespace, use it and not return error 
Fixes #
Reference to #
```release-note
NONE
```

fix: change tenant prefix

---

build/cicd/cd/Dockerfile
cmd/cicd/cd/config.json
cmd/cicd/cd/main.go
pkg/cicd/cd/config.go
pkg/cicd/cd/deployment.go

Add CD image for to update deployment.
Fixes #
Reference to #
```release-note
NONE
```

feat: add CD image for update deployment

---

manifests/templates/cicd/cd.yaml

Add a CD template.
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

chore: add cd template

---

examples/cicd/golang/manifests.yaml.template
examples/cicd/java/manifests.yaml.template
examples/cicd/nodejs/manifests.yaml.template
manifests/cyclone.yaml.template
pkg/workflow/common/const.go
pkg/workflow/controller/config.go
pkg/workflow/coordinator/coordinator.go
pkg/workflow/workflowrun/pod.go
pkg/workflow/workflowrun/pod_test.go
release/workflow-controller.yaml

Support dind as sidecar to build image and push image.
Fixes #
Reference to #
/cc @zhujian7
```release-note
NONE
```

improve: use dind for image build and push

---

manifests/templates/cicd/build.yaml
manifests/templates/cicd/code-scan.yaml
manifests/templates/cicd/image-build.yaml
manifests/templates/cicd/unit-test.yaml
pkg/workflow/common/const.go
pkg/workflow/common/selector.go
pkg/workflow/coordinator/coordinator.go
pkg/workflow/workflowrun/pod.go
release/workflow-controller.yaml

Cyclone has supported use resource parameters value from a secret(#817 ), this PR will support the same feature for stage parameters.
Fixes #
Reference to #
```release-note
NONE
```

feat: support ref value of stage parameters

---

pkg/apis/cyclone/v1alpha1/workflow_run.go
pkg/server/handler/init.go
pkg/workflow/controller/handlers/pod/operation.go
pkg/workflow/controller/handlers/workflowrun/handler.go
pkg/workflow/workflowrun/gc.go
pkg/workflow/workflowrun/gc_test.go
pkg/workflow/workflowrun/operator.go
pkg/workflow/workflowrun/operator_test.go
pkg/workflow/workflowrun/timeout.go
pkg/workflow/workflowrun/utils.go
pkg/workflow/workflowrun/utils_test.go

Fixes #
Reference to #
```release-note
NONE
```

refactor(api): define status phase type

---

pkg/server/apis/v1alpha1/descriptors/admin.go
pkg/server/handler/v1alpha1/admin.go
pkg/util/http/http.go

Add APIs to list resources (e.g. workflow) regardless of tenant and project. They are useful for admin or other auto tools.
Fixes #
Reference to #
```release-note
NONE
```

feat: add admin api for list all

---

pkg/server/apis/v1alpha1/descriptors/project.go
pkg/server/apis/v1alpha1/descriptors/workflow.go
pkg/server/apis/v1alpha1/types.go
pkg/server/biz/statistic/statistic.go
pkg/server/handler/v1alpha1/project.go
pkg/server/handler/v1alpha1/workflow.go
pkg/util/http/http.go

Add api to statistic  workflowruns
Fixes #
Reference to #
```release-note
NONE
```

feat(api): statistics of workflowruns belongs to workflow and project

---

pkg/apis/cyclone/v1alpha1/workflow_run.go
pkg/server/apis/v1alpha1/types.go
pkg/server/biz/statistic/statistic.go
pkg/workflow/controller/handlers/pod/operation.go
pkg/workflow/controller/handlers/workflowrun/handler.go
pkg/workflow/workflowrun/gc.go
pkg/workflow/workflowrun/gc_test.go
pkg/workflow/workflowrun/operator.go
pkg/workflow/workflowrun/operator_test.go
pkg/workflow/workflowrun/timeout.go
pkg/workflow/workflowrun/utils.go
pkg/workflow/workflowrun/utils_test.go

Refactor workflowrun status to make it clearer.
Fixes #
Reference to #
```release-note
NONE
```

refact(api): refact workflowrun status

---

pkg/server/apis/v1alpha1/descriptors/healthcheck.go
pkg/server/apis/v1alpha1/types.go
pkg/server/handler/v1alpha1/healthcheck.go

Add health check API to Cyclone Server.
Fixes #
Reference to #
```release-note
NONE
```

feat: add healthcheck api

---

cmd/server/main.go
manifests/templates/cicd/cd.yaml
pkg/server/biz/tenants/templates.go

Syntax error on cd template.
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

fix: load templates problem

---

manifests/templates/cicd/cd.yaml
pkg/workflow/workflowrun/pod.go

Escape argument value.
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

fix: escape argument value

---

pkg/workflow/workflowrun/workload.go

Fix event recorded in wfr.
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

fix: event recorded in wfr

---

build/resolver/git/entrypoint.sh

Add supports for Gitlab PR. It requires resolver to merge branches.
Fixes #
Reference to #
```release-note
NONE
```

feat: supports pull reqeusts and gitlab in git resolver

---

manifests/cyclone.yaml.template

Syntax error in deployment manifests.
Fixes #
Reference to #
/cc @zhujian7
```release-note
NONE
```

fix: remove redundent comma in config json

---

pkg/server/biz/accelerator/accelerate.go
pkg/server/biz/accelerator/accelerate_test.go
pkg/server/common/const.go
pkg/server/handler/v1alpha1/integration.go
pkg/server/handler/v1alpha1/workflowrun.go

support building acceleration for:
- maven
- gradle
- npm
cache the dependencies of these projects, and use caches when next building.
Fixes #
Reference to #
```release-note
NONE
```

feat: support building acceleration

---

pkg/server/biz/scm/scm.go
pkg/server/common/const.go
pkg/server/handler/v1alpha1/webhook.go
pkg/workflow/controller/handlers/workflowtrigger/cron_job.go

Fixes #
Reference to #
```release-note
NONE
```

feat(owner): support owner and trigger

---

pkg/server/biz/accelerator/accelerate.go
pkg/server/biz/accelerator/accelerate_test.go
pkg/server/biz/usage/usage.go
pkg/server/biz/usage/usage_test.go
pkg/server/biz/usage/watcher.go
pkg/server/handler/v1alpha1/integration.go
pkg/server/handler/v1alpha1/usage.go
pkg/server/handler/v1alpha1/workflowrun.go

Disable acceleration when PVC usage exceed limit.
Fixes #
Reference to #
```release-note
NONE
```

feat: disable wfr acceleration when pvc usage exceed limit

---

pkg/server/handler/v1alpha1/admin.go
pkg/server/handler/v1alpha1/integration.go
pkg/server/handler/v1alpha1/project.go
pkg/server/handler/v1alpha1/resource.go
pkg/server/handler/v1alpha1/stage.go
pkg/server/handler/v1alpha1/template.go
pkg/server/handler/v1alpha1/tenant.go
pkg/server/handler/v1alpha1/workflow.go
pkg/server/handler/v1alpha1/workflowrun.go
pkg/server/handler/v1alpha1/workflowtrigger.go
pkg/server/handler/v1alpha1/workload.go
pkg/server/types/common.go
pkg/util/cerr/error.go

Fixes #
Reference to #
```release-note
NONE
```

feat(api): support search and filter

---

release/cyclone-server.yaml
release/workflow-controller.yaml

Fixes #
Reference to #
```release-note
NONE
```

chore: update release

---

release/cyclone-server.yaml

Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

fix: fix typo in release file

---

pkg/workflow/controller/handlers/workflowtrigger/cron_job.go

Fixes #
Reference to #
/cc @cd1989 @zhujian7 
```release-note
NONE
```

fix(engine): fix cron trigger

---

manifests/cyclone.yaml.template
pkg/server/biz/templates/templates.go
pkg/server/config/config.go
release/cyclone-server.yaml

make builtin stage templates creation configurable
Fixes #
Reference to #
```release-note
NONE
```

chore: make builtin stage templates creation configurable

---

pkg/server/handler/v1alpha1/webhook.go
pkg/workflow/controller/handlers/workflowtrigger/cron_job.go
release/workflow-controller.yaml

Fixes #
Reference to #
```release-note
NONE
```

fix two small errors

---

cmd/workflow/coordinator/main.go
pkg/workflow/coordinator/coordinator.go

Some errors of coordinator are ignored by mistake. 
Fixes #
Reference to #
```release-note
NONE
```

fix: coordinator status

---

pkg/server/handler/v1alpha1/webhook.go

Fixes #
Reference to #
```release-note
NONE
```

fix workflowrun alias for tag release trigger

---

Makefile

Cyclone web is far from working with useful features, and the build also has some problem. Remove it from make file temporarily.
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

chore: remove web build from makefile

---

cmd/server/main.go
cmd/workflow/controller/main.go
cmd/workflow/coordinator/main.go
pkg/util/k8s/client.go

Separated from #848 to help rebase.
Fixes #
Reference to #
```release-note
NONE
```

refactor: remove kubehost option

---

web/package.json

Fixes #
Reference to #
```release-note
NONE
```

fix: add missing dependency to fix web build

---

pkg/scm/provider/github/github.go
pkg/worker/scm/provider/git.go

- skip ssl verify when use gitlab
- skip ssl verify when use git in worker
Fixes #
Reference to #
/cc @zhujian7 @wzqnls 
```release-note
NONE
```

feat: skip ssl verify

---

pkg/server/biz/accelerator/accelerate.go

Fix acceleration covered preset volumes
Fixes #
Reference to #
```release-note
NONE
```

fix: fix acceleration covered preset volumes

---

pkg/util/http/http.go
pkg/workflow/workload/delegation/delegate.go

In delegation workload, url provided may missing protocol scheme. We can added it if not exist in url.
Fixes #
Reference to #
```release-note
NONE
```

fix: ensure protocol scheme added in url

---

pkg/server/common/const.go

change system tenant name from 'admin' to 'system', so cyclone-server will create a namespace named `cyclone-system`, and in the future, we will install the Cyclone system components (`cyclone-server`, cyclone-workflow-controller) in the namespace(`cyclone-system`) instead of namespace `default`.
Fixes #
Reference to https://github.com/caicloud/cyclone/issues/885
```release-note
NONE
```

fix: change system tenant name from 'admin' to 'system'

---

pkg/workflow/controller/handlers/workflowtrigger/cron_job.go

Fixes #829
Reference to #
```release-note
NONE
```

feat(cron-trigger): support more types of cron expressions

---

cmd/server/main.go
manifests/cyclone.yaml.template
pkg/server/biz/templates/templates.go
pkg/server/common/const.go
pkg/server/config/config.go
pkg/server/handler/v1alpha1/template.go
release/cyclone-server.yaml

Stage templates should be installed in the namespace which is consistent with Cyclone system namespace.
Fixes #
Reference to #
```release-note
NONE
```

feat: keep stage templates in cyclone system namespace

---

cmd/server/main.go
manifests/cyclone.yaml.template
pkg/server/common/const.go
pkg/server/config/config.go
pkg/server/handler/v1alpha1/tenant.go
release/cyclone-server.yaml

make creating system tenant configurable
Fixes #
Reference to #
```release-note
NONE
```

feat: make creating default tenant configurable

---

pkg/server/handler/v1alpha1/template.go
pkg/server/handler/v1alpha1/workflow.go
pkg/server/handler/v1alpha1/workflowrun.go

Support to search and filter stage templates
Fixes #892
Reference to #
```release-note
NONE
```

feat(#892): search and filter stage templates

---

pkg/server/apis/v1alpha1/descriptors/integration.go
pkg/server/biz/scm/scm.go
pkg/server/handler/v1alpha1/helper.go
pkg/server/handler/v1alpha1/integration.go

Fixes #894
Reference to #
```release-note
NONE
```

feat(#894): add apis to list repos/branches/tags for integrated scms

---

pkg/server/apis/v1alpha1/descriptors/workflowtrigger.go
pkg/server/handler/v1alpha1/helper.go
pkg/server/handler/v1alpha1/workflowrun.go
pkg/server/handler/v1alpha1/workflowtrigger.go

make workflowtrigger as a sub-resource of workflow
Fixes #
Reference to #
```release-note
NONE
```

feat(trigger-api): make workflowtrigger as a sub-resource of workflow

---

release/cyclone-server.yaml
release/cyclone-web.yaml
release/workflow-controller.yaml

Fixes #
Reference to #
/cc @cd1989  @supereagle 
```release-note
NONE
```

chore: add pod resources

---

pkg/server/biz/scm/github/github.go
pkg/server/biz/scm/gitlab/gitlabv3.go
pkg/server/biz/scm/gitlab/gitlabv4.go
pkg/server/biz/scm/scm.go
pkg/server/biz/scm/svn/svn.go
pkg/util/cerr/error.go

As described in the title.
Fixes #
Reference to #
```release-note
NONE
```

feat: add precise error to indicate scm internal error

---

pkg/server/apis/v1alpha1/descriptors/workflowrun.go
pkg/server/handler/v1alpha1/workflowrun.go
pkg/workflow/controller/handlers/pod/operation.go
pkg/workflow/controller/handlers/workflowrun/handler.go
pkg/workflow/workflowrun/operator.go
pkg/workflow/workflowrun/utils.go

Support WorkflowRun cancel
Fixes #
Reference to #
```release-note
NONE
```

feat: support wfr cancel

---

pkg/server/handler/v1alpha1/workflowrun.go

Before cancel a wfr, check whether it's already in terminated state.
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

Fix: check wfr status before cancel

---

manifests/cyclone.yaml.template
pkg/meta/annotations.go
pkg/meta/labels.go
pkg/meta/labels_test.go
pkg/server/apis/v1alpha1/descriptors/notification.go
pkg/server/biz/scm/github/github.go
pkg/server/biz/scm/gitlab/gitlab.go
pkg/server/biz/scm/gitlab/gitlabv3.go
pkg/server/biz/scm/gitlab/gitlabv4.go
pkg/server/biz/scm/scm.go
pkg/server/biz/scm/svn/svn.go
pkg/server/config/config.go
pkg/server/config/config_test.go
pkg/server/handler/v1alpha1/helper.go
pkg/server/handler/v1alpha1/notification.go
pkg/server/handler/v1alpha1/webhook.go
pkg/util/http/http.go
pkg/workflow/controller/config.go
pkg/workflow/controller/controllers/configmap.go
pkg/workflow/controller/controllers/pod.go
pkg/workflow/controller/controllers/workflow_trigger.go
pkg/workflow/controller/controllers/workflowrun.go
pkg/workflow/controller/handlers/workflowrun/handler.go
release/cyclone-server.yaml
release/workflow-controller.yaml

Add notification handler to receive notifications from workflow engine
Fixes #
Reference to #
```release-note
NONE
```

feat: add notification handler

---

release/cyclone-server.yaml
release/cyclone-web.yaml
release/workflow-controller.yaml

Fixes #
Reference to #
```release-note
NONE
```

chore: mount hostpath timezone

---

README.md
docs/design.md

Fixes #
Reference to #
```release-note
NONE
```

fix: fix minor typos in docs

---

pkg/server/biz/scm/github/github.go
pkg/server/biz/scm/gitlab/gitlabv3.go
pkg/server/biz/scm/gitlab/gitlabv4.go

Fixes #923
Reference to #
```release-note
NONE
```

fix(#923): ensure there are no duplicated SCM webhooks

---

pkg/server/handler/v1alpha1/workflowrun.go

Support  filter workflowruns by trigger
Fixes #
Reference to #
```release-note
NONE
```

feat: filter workflowrun by trigger

---

manifests/templates/cicd/build.yaml
manifests/templates/cicd/code-scan.yaml
manifests/templates/cicd/image-build.yaml
manifests/templates/cicd/unit-test.yaml
pkg/apis/cyclone/v1alpha1/common.go

Add type to input/output resources, so that it describe stage better and stage template can works better
Fixes #
Reference to #
```release-note
NONE
```

feat: add type to input/output resources

---

pkg/server/biz/scm/github/github.go
pkg/server/biz/scm/gitlab/gitlabv3.go
pkg/server/biz/scm/gitlab/gitlabv4.go
pkg/util/cerr/error.go

* Uniformly handle SCM error
* Fix potential panic error when handle SCM error
Fixes #922
Reference to #
```release-note
NONE
```

fix(#922): enhancement for scm error handling

---

pkg/server/apis/v1alpha1/types.go
pkg/server/handler/v1alpha1/integration.go

Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

fix: cluster name problem

---

build/resolver/git/entrypoint.sh
pkg/server/handler/v1alpha1/notification.go
web/src/lib/const.js

- Support both <user>:<password> and <token> in git resolver
- URL encode token 
Fixes #
Reference to #
```release-note
NONE
```

fix: support different token format in git resolver

---

pkg/common/k8s.go
pkg/server/biz/pvc/pvc.go
pkg/server/biz/usage/watcher.go
pkg/server/common/cluster.go
pkg/server/handler/v1alpha1/integration.go
pkg/server/handler/v1alpha1/tenant.go
pkg/util/retry/retry.go

PVC size cannot be updated now, this PR will fix the problem.
Fixes #
Reference to #
```release-note
NONE
```

fix: update pvc size

---

docs/installation.md
docs/user_guide.md

Provide installation guide and user guide.
Fixes #
Reference to #
```release-note
NONE
```

docs: simple installation guide and user guide

---

pkg/server/apis/v1alpha1/descriptors/integration.go
pkg/server/common/cluster.go
pkg/server/handler/v1alpha1/integration.go
pkg/util/cerr/error.go

Add API to open/close cluster
Fixes #
Reference to #
```release-note
NONE
```

feat(api): add API to open/close cluster

---

manifests/cyclone.yaml.template
pkg/workflow/controller/config.go
pkg/workflow/workload/pod/builder.go

Secret for workflow controller not used any more.
Fixes #
Reference to #
```release-note
NONE
```

chore: remove secret config

---

Makefile
build/resolver/git/entrypoint.sh
build/resolver/image/entrypoint.sh
build/resolver/svn/Dockerfile
build/resolver/svn/entrypoint.sh
examples/cicd/golang/manifests.yaml.template
examples/cicd/java/manifests.yaml.template
examples/cicd/nodejs/manifests.yaml.template
manifests/cyclone.yaml.template
pkg/apis/cyclone/v1alpha1/resource.go
pkg/server/biz/scm/scm.go
pkg/server/handler/v1alpha1/integration.go
pkg/server/handler/v1alpha1/notification.go
pkg/server/handler/v1alpha1/webhook.go
pkg/workflow/controller/config.go
release/workflow-controller.yaml
web/src/lib/const.js

Add new scm type: SVN
Fixes #
Reference to #
```release-note
NONE
```

feat: support svn resource

---

build/resolver/git/entrypoint.sh

Git resolver to support url with user, such as:
```
http://root@192.168.21.17/scm/foobar.git
```
Fixes #
Reference to #
```release-note
NONE
```

fix: support git url with user in git resolver

---

cmd/server/main.go
pkg/server/apis/v1alpha1/types.go
pkg/server/biz/scm/bitbucket/bitbucket-server/auths.go
pkg/server/biz/scm/bitbucket/bitbucket-server/bitbucket_server.go
pkg/server/biz/scm/bitbucket/bitbucket-server/pull_requests.go
pkg/server/biz/scm/bitbucket/bitbucket-server/repos.go
pkg/server/biz/scm/bitbucket/bitbucket-server/repos_webhooks.go
pkg/server/biz/scm/bitbucket/bitbucket-server/v1Client.go
pkg/server/biz/scm/bitbucket/bitbucket-server/webhooks.go
pkg/server/biz/scm/bitbucket/bitbucket.go
pkg/server/biz/scm/scm.go
pkg/server/handler/v1alpha1/webhook.go

Fixes #
Reference to #
/cc @supereagle @cd1989 @zhujian7 
```release-note
NONE
```

feat: support bitbucket server in scm

---

build/resolver/svn/entrypoint.sh

Fix that svn revision did not support checkout code from branches/tags
Fixes #
Reference to #
```release-note
NONE
```

fix: svn revision

---

pkg/server/handler/v1alpha1/notification.go
pkg/workflow/workload/pod/builder.go

Fixes #
Reference to #
```release-note
NONE
```

fix: fix panic nil-pointer dereference

---

helm/cyclone/.helmignore
helm/cyclone/Chart.yaml
helm/cyclone/templates/_helpers.tpl
helm/cyclone/templates/controller.yaml
helm/cyclone/templates/crd.yaml
helm/cyclone/templates/server.yaml
helm/cyclone/templates/service-account.yaml
helm/cyclone/templates/web.yaml
helm/cyclone/values.yaml

Helm chart for Cyclone deployment
Fixes #774
Reference to #
```release-note
NONE
```

feat: use helm chart to deploy

---

web/package.json
web/src/api/http.js
web/src/components/integration/component/MenuAction.js
web/src/components/integration/component/createIntegration/FormContent.js
web/src/components/integration/component/createIntegration/FormWrap.js
web/src/components/integration/component/createIntegration/validate.js
web/src/components/integration/component/formGroup/Cluster/AuthSelector.js
web/src/components/integration/component/formGroup/Cluster/ValidateSelect.js
web/src/components/integration/component/formGroup/Cluster/WorkerCluster.js
web/src/components/integration/component/formGroup/Cluster/index.js
web/src/components/integration/component/formGroup/DockerRegistry/index.js
web/src/components/integration/component/formGroup/ScmGroup/Forms/AuthSelector.js
web/src/components/integration/component/formGroup/ScmGroup/Forms/Bitbucket.js
web/src/components/integration/component/formGroup/ScmGroup/Forms/GitHub.js
web/src/components/integration/component/formGroup/ScmGroup/Forms/GitLab.js
web/src/components/integration/component/formGroup/ScmGroup/Forms/ValidateSelect.js
web/src/components/integration/component/formGroup/ScmGroup/Selection.js
web/src/components/integration/component/formGroup/ScmGroup/index.js
web/src/components/integration/component/formGroup/SonarQube/index.js
web/src/index.js
web/src/less/u.integrationCenter.less
web/src/lib/const.js
web/src/locale/en-US.yaml
web/src/locale/zh-CN.yaml
web/src/store/workflow.js

- Fix bugs in integration center
- Adjust UI styles in integration center
- Add support for BitBucket
- Default locale set to `en-US`
Fixes #
Reference to #
```release-note
NONE
```

[WEB] feat: add bitbucket to scm support

---

web/src/layout/index.js
web/src/less/inc.var.less

Fixes #
Reference to #
```release-note
NONE
```

feat: change locale in web

---

web/src/api/index.js
web/src/components/project/component/detail/index.js
web/src/components/public/makeField/select.js
web/src/components/workflow/component/List.js
web/src/components/workflow/component/add/BasicInfo.js
web/src/components/workflow/component/add/CreateWorkflow.js
web/src/components/workflow/component/add/Form.js
web/src/components/workflow/component/add/Graph.js
web/src/components/workflow/component/list/ListLayout.js
web/src/components/workflow/component/list/WorkflowTable.js
web/src/components/workflow/component/list/index.js
web/src/components/workflow/component/resource/BindResource.js
web/src/components/workflow/component/resource/Form.js
web/src/components/workflow/component/resource/SCM.js
web/src/components/workflow/component/stage/StageField.js
web/src/components/workflow/index.js
web/src/lib/const.js
web/src/store/index.js
web/src/store/project.js
web/src/store/resource.js
web/src/store/workflow.js

- avoid stage forming closed loop dependence
- submit workflow form data
- show workflow list in project detail
Fixes #
Reference to #
```release-note
NONE
```

feat(devops): avoid stage forming closed loop dependence

---

README.md

The Linux Foundation (LF) Core Infrastructure Initiative (CII) Best Practices badge is a way for Free/Libre and Open Source Software (FLOSS) projects to show that they follow best practices. Projects can voluntarily self-certify, at no cost, by using this web application to explain how they follow each best practice. The CII Best Practices Badge is inspired by the many badges available to projects on GitHub. Consumers of the badge can quickly assess which FLOSS projects are following best practices and as a result are more likely to produce higher-quality secure software.
Fixes #
Reference to # …

docs: add cii best practices

---

web/src/components/workflow/component/add/CreateWorkflow.js
web/src/components/workflow/component/add/Form.js
web/src/components/workflow/component/list/ListLayout.js

- submit workflow form data
Fixes #
Reference to #
```release-note
NONE
```

feat(devops): submit workflow form data

---

pkg/meta/labels.go
pkg/meta/labels_test.go
pkg/server/biz/accelerator/accelerate.go
pkg/server/biz/accelerator/accelerate_test.go

Fixes #
Reference to #
```release-note
NONE
```

refact: refact label value

---

Makefile
README.md
docs/installation.md
helm/cyclone/templates/controller.yaml
helm/cyclone/templates/server.yaml
helm/cyclone/values.yaml
pkg/workflow/workflowrun/execution_context.go

Docs update for helm chart installation
Fixes #
Reference to #
```release-note
NONE
```

chore: update docs for helm chart install

---

web/src/components/integration/component/detail/index.js
web/src/less/u.detail.less
web/src/locale/en-US.yaml
web/src/locale/zh-CN.yaml

Fixes #
Reference to #
```release-note
NONE
```

feat: implement integration detail page

---

web/src/components/stageTemplate/List/index.js

when recive undefined template kind, will display null item, fix
Fixes #
Reference to #
/cc @caosm @qiuxiaolian 
```release-note
NONE
```

fix(templateKind): fix undefined template kind present null item

---

web/src/components/stageTemplate/Detail/index.js
web/src/components/stageTemplate/List/Item.js
web/src/components/stageTemplate/List/list.module.less

-->
Fixes #
Reference to #
```release-note
NONE
```

chore: ui styles in template

---

cmd/workflow/controller/main.go

Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

fix: ExecutionCluter creation before CRD

---

web/src/api/index.js
web/src/components/workflow/component/add/CreateWorkflow.js
web/src/components/workflow/component/add/Form.js
web/src/components/workflow/component/add/Graph.js
web/src/components/workflow/component/detail/StageDepend.js
web/src/components/workflow/component/detail/WorkflowDetail.js
web/src/components/workflow/component/detail/index.js
web/src/components/workflow/component/list/ListLayout.js
web/src/components/workflow/component/list/WorkflowTable.js
web/src/components/workflow/component/resource/BindResource.js
web/src/components/workflow/component/resource/Form.js
web/src/components/workflow/component/resource/ResourceArray.js
web/src/components/workflow/component/resource/SCM.js
web/src/components/workflow/component/stage/AddStage.js
web/src/components/workflow/component/stage/StageField.js
web/src/components/workflow/component/stage/TemplateStage.js
web/src/components/workflow/index.js
web/src/lib/const.js
web/src/lib/util.js
web/src/locale/en-US.yaml
web/src/locale/zh-CN.yaml
web/src/store/workflow.js

- workflow detail
- part of create from template stage
Fixes #
Reference to #
```release-note
NONE
```

 feat(workflow): workflow detail page and template stage

---

web/src/components/stageTemplate/List/Item.js
web/src/components/stageTemplate/List/index.js
web/src/components/stageTemplate/List/list.module.less
web/src/components/stageTemplate/add/Form.js
web/src/components/stageTemplate/add/FormContent.js
web/src/components/stageTemplate/add/Input.js
web/src/components/stageTemplate/add/Output.js
web/src/components/stageTemplate/add/ResourceType.js
web/src/components/stageTemplate/add/SelectSourceType.js
web/src/locale/en-US.yaml
web/src/locale/zh-CN.yaml

modify stageTemplate logic with resource type select & style problem
add resource type select component & modify intl
Fixes #
Reference to #
/cc @caosm @qiuxiaolian @cd1989 
```release-note
NONE
```

chore(stageTemplate): modify stageTemplate logic with resource type

---

web/src/components/stageTemplate/List/Item.js
web/src/components/stageTemplate/index.js

fix update template bread crumbs display & alter update url
Fixes #
Reference to #
/cc @cd1989 
```release-note
NONE
```

fix(stageTemplate): fix update template url

---

README.md
build/workflow/controller/Dockerfile
cmd/server/main.go
cmd/workflow/controller/main.go
docs/installation.md
helm/cyclone/templates/controller.yaml
helm/cyclone/templates/server.yaml
helm/cyclone/templates/web.yaml
helm/cyclone/values.yaml
pkg/common/const.go
pkg/server/common/const.go
pkg/server/config/config.go
pkg/server/handler/v1alpha1/template.go
pkg/workflow/common/const.go
release/cyclone-server.yaml

Fixes #979
Reference to #
```release-note
NONE
```

fix(#979): fix namespace when installed by helm

---

docs/design.md
docs/user_guide.md

As describe in the title
Fixes #
Reference to #
```release-note
NONE
```

docs: explain the limitation of supported external systems

---

web/src/components/stageTemplate/add/Input.js
web/src/components/stageTemplate/add/Output.js
web/src/components/stageTemplate/add/ResourceType.js

Add a verification method to the resource select form item
Fixes #
Reference to #
```release-note
NONE
```

feat(stageTemplate): add a verification method to the resource select form item

---

pkg/server/biz/integration/cluster/cluster.go
pkg/server/biz/integration/cluster/service_account.go
pkg/server/biz/integration/converter.go
pkg/server/biz/integration/name.go
pkg/server/biz/tenant/tenant.go
pkg/server/biz/utils/collection.go
pkg/server/common/utils.go
pkg/server/handler/v1alpha1/helper.go
pkg/server/handler/v1alpha1/integration.go
pkg/server/handler/v1alpha1/project.go
pkg/server/handler/v1alpha1/resource.go
pkg/server/handler/v1alpha1/stage.go
pkg/server/handler/v1alpha1/storage.go
pkg/server/handler/v1alpha1/template.go
pkg/server/handler/v1alpha1/tenant.go
pkg/server/handler/v1alpha1/workflow.go
pkg/server/handler/v1alpha1/workflowrun.go
pkg/server/handler/v1alpha1/workflowtrigger.go
pkg/server/handler/v1alpha1/workload.go

- Refactor integration part code in cyclone server
- Create service account when open cluster
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

feat: create service account when open cluster

---

web/src/layout/index.js
web/src/locale/en-US.yaml
web/src/locale/zh-CN.yaml

Add Cyclone Official Website
Fixes #973 
Reference to #
/cc @supereagle
```release-note
NONE
```

feat: add cyclone official website for refs

---

build/resolver/git/entrypoint.sh

Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

fix: skip git ssl verify

---

pkg/server/apis/v1alpha1/descriptors/integration.go
pkg/server/handler/v1alpha1/integration.go
pkg/server/handler/v1alpha1/notification.go
pkg/server/handler/v1alpha1/tenant.go
pkg/server/handler/v1alpha1/webhook.go
pkg/util/http/http.go

Fixes #
Reference to #
```release-note
NONE
```

feat(api): support operate public integration

---

web/src/components/stageTemplate/List/Item.js
web/src/components/stageTemplate/List/list.module.less

Fixes #
Reference to #
/cc @qiuxiaolian @cd1989 
```release-note
NONE
```

chore(stageTemplate): remove template item hover style

---

web/src/components/stageTemplate/add/Input.js
web/src/components/stageTemplate/add/Output.js
web/src/components/stageTemplate/add/validate.js

Fixes #
Reference to #
/cc @cd1989 
```release-note
NONE
```

chore(stageTemplate): remove resources type validation

---

web/src/components/stageTemplate/Detail/Configuration.js
web/src/components/stageTemplate/add/Form.js

… modify env
Fixes #
Reference to #
```release-note
NONE
```

chore(templateDetail): remove entrypoint & modify cmd display value

---

web/src/components/stageTemplate/add/Config.js

Fixes #
Reference to #
```release-note
NONE
```

chore(stageTemplate): replace cmd component with textarea & modify style

---

Makefile
build/cicd/sonarqube/Dockerfile
build/cicd/sonarqube/entrypoint.sh
manifests/templates/cicd/sonarqube.yaml
pkg/workflow/workflowrun/operator.go

- Support SonarQube by stage template
- Create image for SonarQube scan
Fixes #
Reference to #
```release-note
NONE
```

feat: add SonarQube image and stage template

---

pkg/server/handler/v1alpha1/integration.go
pkg/server/handler/v1alpha1/template.go
pkg/server/handler/v1alpha1/workflowrun.go

support filter integrations
Fixes #
Reference to #
```release-note
NONE
```

feat(api): support filter integrations

---

pkg/meta/labels.go
pkg/server/biz/integration/sonarqube/sonarqube.go
pkg/server/handler/v1alpha1/integration.go
pkg/util/cerr/error.go

Fixes #
Reference to #
```release-note
NONE
```

feat: validate token while creating sonarqube integration

---

web/src/api/http.js
web/src/api/index.js
web/src/components/workflow/component/add/CreateWorkflow.js
web/src/components/workflow/component/add/Form.js
web/src/components/workflow/component/add/Graph.js
web/src/components/workflow/component/add/util.js
web/src/components/workflow/component/detail/StageDepend.js
web/src/components/workflow/component/detail/WorkflowDetail.js
web/src/components/workflow/component/list/WorkflowTable.js
web/src/components/workflow/component/resource/BindResource.js
web/src/components/workflow/component/resource/Form.js
web/src/components/workflow/component/resource/ResourceArray.js
web/src/components/workflow/component/stage/AddStage.js
web/src/components/workflow/component/stage/StageField.js
web/src/components/workflow/component/stage/TemplateStage.js
web/src/components/workflow/index.js
web/src/lib/util.js
web/src/locale/en-US.yaml
web/src/locale/zh-CN.yaml
web/src/store/resource.js
web/src/store/workflow.js

- update workflow real-time
- update resource and stage
Fixes #
Reference to #
```release-note
NONE
```

feat(update): update workflow

---

release/cyclone-server.yaml

Fixes #
Reference to #
```release-note
NONE
```

fix(release): fix report url for storage watcher

---

pkg/workflow/coordinator/coordinator.go

collect execution results from init-container
Fixes #
Reference to #
```release-note
NONE
```

feat: support collect execution results from init-container

---

web/src/api/http.js
web/src/api/index.js
web/src/components/integration/component/MenuAction.js
web/src/components/project/component/MenuAction.js
web/src/components/public/makeField/select.js
web/src/components/workflow/component/MenuAction.js
web/src/components/workflow/component/RunWorkflow.js
web/src/components/workflow/component/add/Graph.js
web/src/components/workflow/component/detail/WorkflowDetail.js
web/src/components/workflow/component/detail/WorkflowRuns.js
web/src/components/workflow/component/list/WorkflowTable.js
web/src/components/workflow/component/resource/Form.js
web/src/components/workflow/component/resource/SCM.js
web/src/locale/en-US.yaml
web/src/locale/zh-CN.yaml
web/src/store/resource.js
web/src/store/workflow.js

-  run workflow
- workflow run record
Fixes #
Reference to #
```release-note
NONE
```

feat(devops): run workflow

---

web/src/less/u.resourceAllocation.less

Fixes #
Reference to #
```release-note
NONE
```

chore(style): adjust quta style disorder

---

docs/design.md
docs/user_guide.md

Fixes #
Reference to #
```release-note
NONE
```

docs: update user guide and design docs 

---

README.md

Fixes #1013
Reference to #
```release-note
NONE
```

chore: add slack invitation link

---

pkg/meta/labels.go
pkg/server/apis/v1alpha1/descriptors/webhook.go
pkg/server/biz/hook/hook.go
pkg/server/biz/hook/scm.go
pkg/server/handler/v1alpha1/helper.go
pkg/server/handler/v1alpha1/integration.go
pkg/server/handler/v1alpha1/webhook.go
pkg/server/handler/v1alpha1/workflowtrigger.go

Refactor scm webhook trigger, try to decouple scm webhook with integration
Fixes #
Reference to #
```release-note
NONE
```

refactor: scm webhook trigger

---

Makefile

* Fix `make container-local` to build all images
* Auto generate version by `git describe --tags`
Fixes #
Reference to #
```release-note
NONE
```

fix: Fix error and enhance tag in makefile

---

pkg/server/apis/v1alpha1/descriptors/integration.go
pkg/server/biz/scm/bitbucket/server/bitbucket_server.go
pkg/server/biz/scm/github/github.go
pkg/server/biz/scm/gitlab/gitlabv4.go
pkg/server/biz/scm/helper.go
pkg/server/handler/v1alpha1/helper.go
pkg/server/handler/v1alpha1/integration.go

Add api to list Dockerfiles from SCM repos.
Fixes #
Reference to #
```release-note
NONE
```

feat: add apis to list dockerfiles from scm

---

helm/cyclone/Chart.yaml
helm/cyclone/templates/controller.yaml
helm/cyclone/templates/server.yaml
helm/cyclone/templates/service-account.yaml
helm/cyclone/templates/web.yaml

Fix helm charts for cases:
- Istio
- Resource quota
- ServiceAccount
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

fix: update helm charts for serviceaccount

---

pkg/server/biz/scm/scm.go
pkg/server/handler/v1alpha1/integration.go

As described in subject
Fixes #
Reference to #
```release-note
NONE
```

fix: can not update svn type integration

---

web/src/components/stageTemplate/Detail/index.js
web/src/components/stageTemplate/List/Item.js

Cyclone web remains some  deprecated `cyclone.io`
Fixes #
Reference to #
```release-note
NONE
```

fix: cyclone.io to cyclone.dev

---

README.md

Fixes #
Reference to #
```release-note
NONE
```

chore: update readme for cycli

---

manifests/templates/cicd/build.yaml
manifests/templates/cicd/image-build.yaml
manifests/templates/cicd/sonarqube.yaml
manifests/templates/cicd/unit-test.yaml
web/src/components/stageTemplate/Detail/Inputs.js
web/src/components/stageTemplate/Detail/Outputs.js
web/src/locale/en-US.yaml
web/src/locale/zh-CN.yaml

- Remove resource name in template
- Display output resource in web
Fixes #
Reference to #
/cc @zhujian7
```release-note
NONE
```

remove-resource-name

---

helm/cyclone/templates/server.yaml
helm/cyclone/values.yaml
pkg/server/biz/hook/scm.go
pkg/server/config/config.go
release/cyclone-server.yaml

Fixes #
Reference to #
```release-note
NONE
```

chore: get webhook url from env

---

web/src/components/workflow/component/resource/BindResource.js

- reousrce type select
Fixes #
Reference to #
```release-note
NONE
```

feat(resource): resource type select

---

web/src/components/stageTemplate/Detail/Outputs.js
web/src/components/stageTemplate/List/list.module.less
web/src/locale/en-US.yaml
web/src/locale/zh-CN.yaml

- template item alignment
- artifacts display name
Fixes #
Reference to #
```release-note
NONE
```

fix: templates web

---

pkg/apis/cyclone/v1alpha1/workflow_trigger.go
pkg/server/biz/hook/scm.go
pkg/server/biz/scm/scm.go
pkg/server/biz/scm/svn/svn.go
pkg/server/common/const.go
pkg/server/handler/v1alpha1/webhook.go

support svn post commit hook
Fixes #
Reference to #
```release-note
NONE
```

feat: support svn post commit hook

---

web/src/components/public/makeField/autoComplete.js
web/src/components/stageTemplate/List/index.js
web/src/components/stageTemplate/add/Config.js
web/src/components/stageTemplate/add/Form.js
web/src/components/stageTemplate/add/FormContent.js
web/src/components/stageTemplate/add/Input.js
web/src/components/stageTemplate/add/validate.js
web/src/lib/const.js
web/src/locale/en-US.yaml
web/src/locale/zh-CN.yaml

fix template form error with field arguments & cmd , exchange field spec.pod.inputs.arguments with spec.pod.container fileds
Fixes #
Reference to #
/cc @cd1989 
```release-note
NONE
```

chore(stageTemplate): fix template form error with field arguments & cmd

---

web/src/api/http.js
web/src/components/workflow/component/add/BasicInfo.js
web/src/components/workflow/component/add/CreateWorkflow.js
web/src/components/workflow/component/add/Form.js
web/src/components/workflow/component/add/Graph.js
web/src/components/workflow/component/resource/BindResource.js
web/src/components/workflow/component/resource/Form.js
web/src/components/workflow/component/resource/SCM.js
web/src/components/workflow/component/stage/AddStage.js
web/src/components/workflow/component/stage/StageField.js
web/src/components/workflow/component/stage/TemplateStage.js
web/src/lib/const.js
web/src/lib/util.js

- Request timeout extended
- add form validate
Fixes #
Reference to #
```release-note
NONE
```

feat(workflow): add field level validate

---

manifests/templates/cicd/unit-test.yaml
web/package.json
web/src/components/stageTemplate/Detail/Inputs.js
web/src/components/stageTemplate/Detail/index.js
web/src/locale/en-US.yaml
web/src/locale/zh-CN.yaml

- Highlight cmd in template detail page
- Display scene and template type in template detail page
Fixes #
Reference to #
```release-note
NONE
```

fix: highlight cmd in template detail page

---

web/src/components/stageTemplate/Detail/Configuration.js
web/src/components/stageTemplate/Detail/Inputs.js
web/src/components/stageTemplate/List/Item.js
web/src/components/stageTemplate/List/list.module.less
web/src/components/stageTemplate/add/Form.js
web/src/components/stageTemplate/add/Input.js
web/src/components/stageTemplate/add/Output.js
web/src/components/stageTemplate/add/ResourceType.js
web/src/components/stageTemplate/add/SelectSourceType.js

fix configuration cmd value 
set resources options optional access props
replace cmd regex
edit css of template list item action button
Fixes #
Reference to #
/cc @cd1989 
```release-note
NONE
```

fix(stageTemplate): fix configuration cmd value & resource options

---

pkg/server/biz/scm/gitlab/gitlab.go
pkg/server/handler/v1alpha1/integration.go
web/src/components/integration/component/createIntegration/FormWrap.js
web/src/components/integration/component/formGroup/DockerRegistry/index.js
web/src/components/integration/component/formGroup/ScmGroup/Forms/AuthSelector.js
web/src/components/stageTemplate/Detail/Inputs.js
web/src/components/stageTemplate/Detail/detail.module.less
web/src/consts/const.js
web/src/locale/en-US.yaml
web/src/locale/zh-CN.yaml

Fix update integration center problem in cyclone web.
- Can't update Gitlab type integration
- Clean data in add integration page
- Fix sonarQube type integration problems, key name is incorrect.
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

fix: integration center problems in web

---

web/src/components/project/component/detail/index.js
web/src/components/public/makeField/select.js
web/src/components/stageTemplate/Detail/Inputs.js
web/src/components/stageTemplate/Detail/detail.module.less
web/src/components/workflow/component/MenuAction.js
web/src/components/workflow/component/RunWorkflow.js
web/src/components/workflow/component/add/Graph.js
web/src/components/workflow/component/list/ListLayout.js
web/src/components/workflow/component/resource/BindResource.js
web/src/components/workflow/component/resource/Form.js
web/src/components/workflow/component/resource/ResourceArray.js
web/src/components/workflow/component/stage/AddStage.js
web/src/components/workflow/component/stage/StageField.js
web/src/components/workflow/component/stage/TemplateStage.js
web/src/locale/en-US.yaml
web/src/locale/zh-CN.yaml

Fix some cyclone web problems
Fixes #
Reference to #
```release-note
NONE
```

fix: cyclone web problems

---

web/src/components/workflow/component/add/Graph.js
web/src/components/workflow/component/resource/ResourceArray.js
web/src/locale/en-US.yaml
web/src/locale/zh-CN.yaml

- validate resource field array
Fixes #
Reference to #
```release-note
NONE
```

fix(devops): validate resource field array

---

docs/user_guide.md

Fixes #
Reference to #
```release-note
NONE
```

docs: add svn post commit hook user guide

---

web/src/api/index.js
web/src/components/stageTemplate/add/FormContent.js
web/src/components/stageTemplate/add/Input.js
web/src/components/stageTemplate/add/Output.js
web/src/store/resource.js

resource type select data request type from backend api
Fixes #
Reference to #
/cc @cd1989 
```release-note
NONE
```

chore(stageTemplate): support resourceTypes select api

---

web/src/components/workflow/component/add/CreateWorkflow.js
web/src/components/workflow/component/add/Form.js
web/src/components/workflow/component/add/Graph.js
web/src/components/workflow/component/index.module.less
web/src/components/workflow/component/resource/BindResource.js
web/src/components/workflow/component/resource/Form.js
web/src/components/workflow/component/resource/ResourceArray.js
web/src/components/workflow/component/stage/AddStage.js
web/src/components/workflow/component/stage/TemplateStage.js
web/src/lib/const.js

- show resource type and transform cmd
- fix validate used error
Fixes #
Reference to #
/cc @cd1989 @huxiangtao 
```release-note
NONE
```

 fix(stage): The verification method is incorrectly used.

---

web/src/components/workflow/component/add/Graph.js
web/src/locale/en-US.yaml
web/src/locale/zh-CN.yaml

Fixes #
Reference to #
```release-note
NONE
```

fix(graph): fix intl problem

---

cmd/workflow/coordinator/main.go

Fixes #
Reference to #
```release-note
NONE
```

fix: make coordinator exit gracefully

---

pkg/server/biz/scm/github/github.go
pkg/server/biz/scm/gitlab/gitlabv3.go
pkg/server/biz/scm/gitlab/gitlabv4.go
pkg/server/biz/scm/helper.go

Fixes #1059
Reference to #
```release-note
NONE
```

fix(#1059): list all branches and tags from scm repo

---

web/src/components/workflow/component/add/Graph.js

Fixes #
Reference to #
/cc @cd1989 @qiuxiaolian 
```release-note
NONE
```

chore(workflow): drawer show close button

---

web/src/components/integration/component/createIntegration/FormContent.js
web/src/components/stageTemplate/add/Form.js
web/src/components/stageTemplate/add/FormContent.js

Fixes #
Reference to #
/cc @cd1989 
```release-note
NONE
```

chore(stageTemplate): add dirty to form & disable submit button

---

helm/cyclone/templates/resource-type.yaml
pkg/apis/cyclone/v1alpha1/common.go
pkg/server/apis/v1alpha1/descriptors/resourcetypes.go
pkg/server/handler/v1alpha1/resourcetypes.go
web/src/api/index.js
web/src/components/resource/component/List.js
web/src/components/resource/component/MenuAction.js
web/src/components/resource/component/create/FormContent.js
web/src/components/resource/component/create/index.js
web/src/components/resource/component/detail/index.js
web/src/components/resource/index.js
web/src/components/stageTemplate/add/Input.js
web/src/layout/index.js
web/src/locale/en-US.yaml
web/src/locale/zh-CN.yaml
web/src/routes/index.js
web/src/store/resource.js

Provides APIs to create, update, delete resource types
Provides Web to manage resource types.
Fixes #
Reference to #1047
```release-note
NONE
```

feat: manage resource types

---

web/src/components/workflow/component/add/util.js
web/src/components/workflow/component/detail/WorkflowRuns.js
web/src/components/workflow/component/index.module.less
web/src/components/workflow/component/list/WorkflowTable.js
web/src/components/workflow/component/resource/BindResource.js
web/src/components/workflow/component/resource/Form.js
web/src/components/workflow/component/resource/ResourceArray.js
web/src/components/workflow/component/stage/AddStage.js
web/src/components/workflow/component/stage/TemplateStage.js
web/src/locale/en-US.yaml
web/src/locale/zh-CN.yaml
web/src/store/resource.js

- fix resource initialValues error
- modify stage arguments style
-fix  stage resource missing name
Fixes #
Reference to #
```release-note
NONE
```

 feat(workflow): stage resource missing name

---

web/src/components/public/ellipsisMenu/index.js
web/src/components/workflow/component/add/Graph.js
web/src/components/workflow/component/add/util.js
web/src/components/workflow/component/detail/WorkflowDetail.js
web/src/components/workflow/component/index.module.less
web/src/components/workflow/component/list/WorkflowTable.js
web/src/components/workflow/component/resource/Form.js
web/src/components/workflow/component/resource/ResourceArray.js
web/src/components/workflow/component/stage/AddStage.js
web/src/components/workflow/component/stage/StageField.js
web/src/store/resource.js

- remove useless stageDetail store
- modify menu action style
Fixes #
Reference to #
```release-note
NONE
```

 fix(stage): stage store useless for stageDetail

---

pkg/workflow/workload/pod/builder.go

- Resolve arguments for stag before pass to coordinator
- Ensure container names before pass to coordinator
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

fix: resolve args for coordinator

---

helm/cyclone/templates/resource-type.yaml
pkg/apis/cyclone/v1alpha1/common.go
pkg/apis/cyclone/v1alpha1/resource.go
pkg/server/handler/v1alpha1/resourcetypes.go
pkg/workflow/common/resource_resolver.go
pkg/workflow/controller/config.go
pkg/workflow/workload/pod/builder.go
pkg/workflow/workload/pod/builder_test.go

- Support arbitrary resource type registered
Fixes #
Reference to #
```release-note
NONE
```

feat: support arbitrary resource type

---

web/src/components/resource/component/create/index.js
web/src/components/workflow/component/detail/WorkflowRuns.js
web/src/lib/util.js
web/src/locale/en-US.yaml
web/src/locale/zh-CN.yaml

- Add tag for status
- Add time duration for wfr execution
Fixes #
Reference to #
```release-note
NONE
```

feat: wfr status tag and duration

---

web/src/components/workflow/component/add/Form.js
web/src/components/workflow/component/detail/StageDepend.js
web/src/components/workflow/component/detail/WorkflowDetail.js
web/src/components/workflow/component/resource/Form.js
web/src/components/workflow/component/resource/ResourceArray.js
web/src/components/workflow/component/stage/AddStage.js
web/src/components/workflow/component/stage/StageField.js
web/src/components/workflow/component/stage/TemplateStage.js
web/src/lib/const.js
web/src/lib/util.js

Fixes #
Reference to #
/cc @cd1989 @huxiangtao 
```release-note
NONE
```

 feat(workflow): default stage/resource name

---

web/src/layout/index.js
web/src/locale/en-US.yaml
web/src/locale/zh-CN.yaml

- Hide account icon in headerbar
- Add API docs link in headerbar
Fixes #
Reference to #
```release-note
NONE
```

feat: api doc link to headerbar

---

pkg/server/handler/v1alpha1/project.go

Project list api supports searching by name and alias.
Fixes #
Reference to #
/cc @cd1989 @qiuxiaolian 
```release-note
NONE
```

feat: project list api supports searching

---

web/src/components/workflow/component/resource/BindResource.js
web/src/components/workflow/component/resource/Form.js
web/src/components/workflow/component/resource/ResourceArray.js
web/src/store/resource.js

- 
Fixes #
Reference to #
```release-note
NONE
```

feat(resource): use integration in resoure create

---

web/src/api/index.js
web/src/components/project/component/List.js
web/src/components/project/component/detail/index.js
web/src/components/workflow/component/detail/WorkflowRuns.js
web/src/components/workflow/component/list/ListLayout.js
web/src/components/workflow/component/list/WorkflowTable.js
web/src/less/inc.var.less
web/src/store/integration.js
web/src/store/project.js
web/src/store/workflow.js

- search
Fixes #
Reference to #
```release-note
NONE
```

feat(*): add project/workflow/workflowruns search

---

web/src/components/resource/component/List.js

Fixes #
Reference to #
```release-note
NONE
```

fix: resource type page error

---

web/src/components/integration/component/createIntegration/FormWrap.js
web/src/components/stageTemplate/add/Form.js
web/src/consts/const.js
web/src/lib/const.js

replace integration const js & fix template bug
Fixes #
Reference to #
```release-note
NONE
```

chore(integration): replace integration const js & fix template bug

---

web/src/components/workflow/component/RunWorkflow.js
web/src/locale/en-US.yaml
web/src/locale/zh-CN.yaml

- Support auto generation wfr name and user input
Fixes #
Reference to #
/cc @supereagle @huxiangtao 
```release-note
NONE
```

feat: wfr version generation

---

web/src/components/project/component/addProject/FormContent.js

Fixes #
Reference to #
```release-note
NONE
```

chore(project): remove quota config field

---

web/src/components/workflow/component/list/WorkflowTable.js

fix project detail to workflow page url path with repacing path value
Fixes #
Reference to #
```release-note
NONE
```

fix(project): fix project detail workflow url path

---

manifests/templates/cicd/build.yaml
manifests/templates/cicd/cd.yaml
manifests/templates/cicd/image-build.yaml
manifests/templates/cicd/sonarqube.yaml
manifests/templates/cicd/unit-test.yaml

Fixes #
Reference to #
/cc @cd1989 @zhujian7 
```release-note
NONE
```

refact: remove suffix of stage template names

---

cmd/workflow/coordinator/main.go
pkg/server/handler/v1alpha1/helper.go
pkg/server/handler/v1alpha1/integration.go
pkg/server/handler/v1alpha1/workflowrun.go
pkg/server/handler/v1alpha1/workflowtrigger.go

Cherry-pick:
- https://github.com/caicloud/cyclone/pull/1021
- https://github.com/caicloud/cyclone/pull/1050
Fixes #
Reference to #
```release-note
NONE
```

fix webhook issue

---

build/resolver/git/entrypoint.sh
helm/cyclone/templates/resource-type.yaml

Add additional SCM_REPO variable to git resource.
Fixes #
Reference to #
```release-note
NONE
```

feat: add SCM_REPO to git resource

---

web/src/components/integration/component/List.js
web/src/components/integration/component/createIntegration/FormWrap.js
web/src/components/integration/component/detail/index.js

fix bug about integraion wrong field of alias & detail page bug
https://github.com/caicloud/cyclone/issues/1078
Fixes #1078 
Reference to #
```release-note
NONE
```

fix(integration): fix integration form wrong alias & detail

---

web/src/components/workflow/component/resource/BindResource.js
web/src/locale/en-US.yaml
web/src/locale/zh-CN.yaml

Fixes #
Reference to #
```release-note
NONE
```

fix(workflow): add section card to resource form in workflow

---

web/src/components/workflow/component/detail/WorkflowRuns.js
web/src/locale/en-US.yaml
web/src/locale/zh-CN.yaml

Fixes #
Reference to #
```release-note
NONE
```

feat: add status filter to wfr list

---

manifests/templates/cicd/build.yaml
manifests/templates/cicd/image-build.yaml
manifests/templates/cicd/unit-test.yaml

Fixes #
Reference to #
/cc @cd1989 
```release-note
NONE
```

fix: fix special character in cmd

---

web/src/components/workflow/component/resource/Form.js

- Fix problem when update resource in stage
Fixes #
Reference to #
/cc @supereagle @huxiangtao 
```release-note
NONE
```

fix: edit resource in stage

---

web/src/components/workflow/component/resource/BindResource.js
web/src/components/workflow/component/resource/Form.js
web/src/components/workflow/component/stage/AddStage.js
web/src/components/workflow/component/stage/TemplateStage.js
web/src/store/stageTemplate.js
web/yarn.lock

- not post arguments description info
Fixes #
Reference to #
```release-note
NONE
```

fix(devops): not post arguments description info

---

web/src/components/workflow/component/resource/ResourceArray.js
web/src/components/workflow/component/stage/AddStage.js
web/src/components/workflow/component/stage/StageField.js
web/src/components/workflow/component/stage/TemplateStage.js
web/src/lib/const.js

- if use word break
- growth label width
Fixes #
Reference to #
```release-note
NONE
```

chore(*): drawer formItem Layout

---

web/src/components/public/ellipsisMenu/index.js
web/src/components/resource/component/List.js
web/src/components/resource/component/MenuAction.js
web/src/components/stageTemplate/add/FormContent.js

Fixes #
Reference to #
```release-note
NONE
```

chore(resource): forbidden bulit in resource edited & deleted

---

web/src/api/http.js
web/src/components/workflow/component/RunWorkflow.js
web/src/components/workflow/component/detail/WorkflowRuns.js
web/src/store/workflow.js

while workflow run has nonterminated  status, loop request for workflow run data
Fixes #
Reference to #
/cc @qiuxiaolian @cd1989 
```release-note
NONE
```

chore(workflow): add loop request while nonterminated status

---

web/src/components/resource/component/create/FormContent.js
web/src/components/resource/component/create/SelectSourceType.js
web/src/components/resource/component/create/index.js
web/src/components/resource/component/detail/index.js

Fixes #
Reference to #
/cc @cd1989 
```release-note
NONE
```

feat(resourceType): add integration type to resourceType

---

web/src/components/workflow/component/add/BasicInfo.js
web/src/components/workflow/component/add/CreateWorkflow.js

- 
Fixes #
Reference to #
```release-note
NONE
```

fix(workflow): workflow name read only when update

---

web/src/components/workflow/component/stage/StageField.js
web/src/components/workflow/component/stage/TemplateStage.js

Fixes #
Reference to #
/cc @cd1989 
```release-note
NONE
```

fix(resource): resource array field name error

---

web/src/components/workflow/component/stage/StageField.js
web/src/components/workflow/component/stage/TemplateStage.js

Fixes #
Reference to #
```release-note
NONE
```

fix(devops): custom stage resource array field name error

---

pkg/apis/cyclone/v1alpha1/resource.go
pkg/workflow/common/resource_resolver.go

Use resolvers configured in configmap
Fixes #
Reference to #
```release-note
NONE
```

fix: use resolvers in config file

---

pkg/server/biz/scm/gitlab/gitlabv3.go
pkg/server/biz/scm/gitlab/gitlabv4.go

Fixes #1114
Reference to #
/cc @cd1989 
```release-note
NONE
```

fix(#1114): support multiple level scm repo

---

web/src/components/workflow/component/add/Graph.js
web/src/locale/en-US.yaml
web/src/locale/zh-CN.yaml
web/src/store/resource.js

Fixes #
Reference to #
/cc @cd1989 
```release-note
NONE
```

fix(workflow): delete stage at workflow update

---

web/src/components/workflow/component/add/Graph.js
web/src/components/workflow/component/add/util.js
web/src/components/workflow/component/stage/StageField.js
web/src/locale/en-US.yaml
web/src/locale/zh-CN.yaml

- modify command
Fixes #
Reference to #
/cc @cd1989 
```release-note
NONE
```

 fix(stage): stage config command

---

pkg/server/handler/v1alpha1/webhook.go
pkg/workflow/controller/handlers/workflowtrigger/cron_job.go

Fixes #
Reference to #
```release-note
NONE
```

fix(#1116): fix acceleration for auto triggered workflowruns

---

pkg/server/biz/scm/bitbucket/server/server.go

Fix lint error
Fixes #
Reference to #
```release-note
NONE
```

fix ci problem

---

web/src/components/workflow/component/add/Graph.js
web/src/components/workflow/component/add/util.js

- remove workflow stage artifacts
- fix stage depends
Fixes #
Reference to #
/cc @cd1989 
```release-note
NONE
```

fix(workflow): remove workflow stage artifacts and fix stage depends

---

helm/cyclone/templates/controller.yaml
pkg/workflow/controller/config.go
pkg/workflow/workload/pod/builder.go

- Configure dind sidercar for insecure-registries
- Resolve template in parameter values.
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

feat: configre dind sidercar and fix parameter value template

---

Makefile
README.md
helm/cyclone/Chart.yaml

Update helm chart for v1.0.0-alpha
Fixes #
Reference to #
```release-note
NONE
```

chore: update helm for v1.0.0-alpha

---

web/src/api/http.js
web/src/components/resourceTypes/component/List.js
web/src/components/workflow/component/list/WorkflowTable.js

Fixes #
Reference to #
```release-note
NONE
```

fix: some cyclone web problems

---

pkg/server/biz/scm/github/github.go
pkg/server/biz/scm/gitlab/gitlabv4.go
pkg/server/biz/scm/helper.go

Speedup SCM list APIs.
Fixes partial of #1134
Reference to #
/cc @zhujian7 
```release-note
NONE
```

enhance: improve scm list api performance

---

build/watcher/pvc-watcher.sh
pkg/workflow/workflowrun/operator.go
release/cyclone-server.yaml

```
ERRO[2019-06-13T16:08:21+08:00] Unknown stage status observed.                status=Cancelled stg=testgithub-pipeline-20190520154142-codescan-template-0-0
```
Fixes #
Reference to #
```release-note
NONE
```

fix: unknown Cancelled status

---

build/resolver/git/entrypoint.sh

Fixes #
Reference to #https://github.com/caicloud/prod-issue/issues/653
```release-note
NONE
```

fix: filter sensitive infomation

---

pkg/server/handler/v1alpha1/workflowrun.go

support append container logs
Fixes #
Reference to #
```release-note
NONE
```

fix: support append container logs

---

pkg/server/handler/v1alpha1/webhook.go

Generate image random tag for scm triggered wfr
Fixes #
Reference to #
```release-note
NONE
```

fix: generate image random tag

---

pkg/server/biz/pvc/pvc.go

Fixes #
Reference to #
```release-note
NONE
```

fix: update tenant pvc not found error

---

pkg/server/biz/scm/github/github.go

Fixes #1099
Reference to #
```release-note
NONE
```

feat(#1099): support enterprise Github

---

web/src/components/stageTemplate/add/Input.js

Signed-off-by: ivc369 <iveon.cc@gmail.com>
When I tried this web project locally, I encountered the following error:
This PR is to solve the above problem, other web developers may also encounter the same error.
Fixes #
Reference to #
```release-note
NONE
```

fix: fix a Prettier error

---

CONTRIBUTING.md

It should be `git remote add`, not `git remove add` 😀
Fixes #
Reference to #
```release-note
NONE
```

docs: fix contributing md error

---

docs/concepts/values.md
pkg/apis/cyclone/v1alpha1/workflow.go
pkg/apis/cyclone/v1alpha1/workflow_run.go
pkg/common/values/generators.go
pkg/common/values/generators_test.go
pkg/workflow/controller/handlers/workflowrun/handler.go
pkg/workflow/values/ref/ref.go
pkg/workflow/values/ref/ref_test.go
pkg/workflow/workflowrun/operator.go
pkg/workflow/workload/pod/builder.go

Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

chore: styles, comments and values docs

---

pkg/server/config/config.go
pkg/server/handler/v1alpha1/helper.go
release/cyclone-server.yaml

Fixes #
Reference to #
```release-note
NONE
```

chore: get record web url template from env firstly

---

pkg/server/handler/v1alpha1/workflowrun.go

Missing last line log
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

fix: last line log would be missing if not ended with \n

---

pkg/workflow/workload/pod/builder.go
pkg/workflow/workload/pod/builder_test.go

This pr fix the resource wasting issue that all containers average the workflow resource requirements, but cyclone containers actually need little resources.
We do the following things:
- cyclone containers will be assigned resource requirements with 0(unbounded), since they only consume negligible resources.
- the other containers will average the pod resource requirements
Fixes #
Reference to #
```release-note
NONE
```

fix: assign resource requirements of cyclone containers with 0

---

pkg/server/handler/v1alpha1/webhook.go

Fixes #
Reference to #
```release-note
NONE
```

fix: update image tag rule for webhook triggered pipeline

---

pkg/server/biz/scm/gitlab/gitlab.go

Fixes # 
Reference to # https://github.com/caicloud/service/issues/761
/cc @zhujian7 
```release-note
NONE
```

fest: skip ssl verify for gitlab

---

pkg/server/apis/api.go
pkg/server/apis/v1/descriptors/descriptor.go
pkg/server/apis/v1/descriptors/oauth.go
pkg/server/apis/v1/handler/oauth.go
pkg/server/apis/v1/types.go
pkg/server/biz/scm/gitlab/gitlab.go
pkg/server/biz/scm/scm.go
pkg/util/http/http.go

Fixes #
Reference to #
/cc @zhujian
```release-note
NONE
```

 feat(oauth): cherry-pick from v0.8 to v0.9

---

pkg/server/biz/stream/folder.go
pkg/server/biz/stream/folder_test.go
pkg/server/handler/v1alpha1/workflowrun.go

- Implement logs stream for all containers that user care
- Download logs for all containers that user care
Fixes #
Reference to #
```release-note
NONE
```

All container logs

---

build/cicd/sonarqube/entrypoint.sh

Fixes #
Reference to #
```release-note
NONE
```

fix: sonar qube entrypoint bug fixes

---

build/cicd/sonarqube/entrypoint.sh

Fixes #
Reference to #
```release-note
NONE
```

chore: add debug logs for sonar qube image

---

build/resolver/git/entrypoint.sh

Fixes #https://github.com/caicloud/cyclone/issues/1168
Reference to #
```release-note
NONE
```

perf: improve git resolver performance with --depth

---

pkg/workflow/workflowrun/operator.go

Fixes #
Reference to #
```release-note
NONE
```

fix: update wfr with global variable resolved

---

pkg/server/biz/scm/gitlab/gitlabv3.go

Fixes #
Reference to #
```release-note
NONE
```

fix: low level bug of gitlab v3 version

---

pkg/server/biz/hook/scm.go
pkg/server/biz/integration/sonarqube/sonarqube.go
pkg/server/biz/scm/bitbucket/server/server.go
pkg/server/biz/scm/github/github.go
pkg/server/biz/scm/gitlab/gitlabv3.go
pkg/server/biz/scm/gitlab/gitlabv4.go
pkg/server/biz/scm/scm.go
pkg/server/handler/v1alpha1/tenant.go
pkg/util/cerr/error.go

Fixes #
Reference to #
```release-note
NONE
```

fix(error code): clarify error code

---

pkg/server/biz/scm/gitlab/gitlab.go
pkg/server/biz/scm/gitlab/gitlabv3.go

fix: skip ssl verify for gitlab
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

fix: skip ssl verify for gitlab

---

pkg/server/biz/scm/bitbucket/server/v1Client.go

Need response of Bitbucket to do error check
Fixes #
Reference to #
```release-note
NONE
```

fix(bitbucket): need response to do error check

---

build/resolver/git/entrypoint.sh

Fixes #
Reference to #
```release-note
NONE
```

fix(git-resolver): can not pull bitbucket code with personal access token

---

pkg/server/biz/hook/scm.go

Did not use repo as a label since repo length may greater than the label length limit 64.
Error like this:
```
{"reason":"ReasonInternal","message":"unknown error: unable to parse requirement: invalid label value: \"longname-fufu.01234567890-.subgroup-fufu.01234567890.layer3.subgroup.layer4.subgroup.subgroup5-fufu.test.nobranch\": must be no more than 63 characters","data":{"error":"unable to parse requirement: invalid label value: \"longname-fufu.01234567890-.subgroup-fufu.01234567890.layer3.subgroup.layer4.subgroup.subgroup5-fufu.test.nobranch\": must be no more than 63 characters"}}
```
Fixes #
Reference to #
/cc @cd1989 @supereagle …

fix: label value for wft event repo too long

---

pkg/server/apis/v1alpha1/descriptors/integration.go
pkg/server/biz/scm/gitlab/gitlab.go
pkg/server/biz/scm/gitlab/gitlabv3.go
pkg/server/biz/scm/gitlab/gitlabv4.go
pkg/server/handler/v1alpha1/integration.go
pkg/server/handler/v1alpha1/tenant.go
pkg/util/http/http.go

- support dry-run for creating integration, we can use this feature to validate integration before the creation
- refactor gitlab error conversion
Fixes #
Reference to #
```release-note
NONE
```

feat(server): support dry-run for creating integration

---

helm/cyclone/templates/controller.yaml
helm/cyclone/values.yaml
pkg/workflow/controller/config.go
pkg/workflow/workload/pod/builder.go
release/workflow-controller.yaml

Make IP subnet of docker-in-docker configurable, so that when conflict with external network, we can change it easily.
Fixes #
Reference to #
```release-note
NONE
```

fix: make dind bip configurable

---

helm/cyclone/templates/controller.yaml
helm/cyclone/values.yaml
pkg/workflow/controller/config.go
pkg/workflow/workflowrun/operator.go
release/workflow-controller.yaml

Fixes #
Reference to #
```release-note
NONE
```

feat: make resource requirement of gc pod configurable

---

manifests/templates/cicd/build.yaml
manifests/templates/cicd/unit-test.yaml

Image gradle:3.4.1 run as `gradle` user in default, unfortunately, the user `gradle` may not have access to create directory. So when you exec gradle commands you may encounter an error like: 
```
FAILURE: Build failed with an exception.
* What went wrong:
Failed to create parent directory '/tmp/code/.gradle' when creating directory '/tmp/code/.gradle/buildOutputCleanup'
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED
```
The newest version image of gradle 5.5.1 run as `root` user in default. And I think we can upgrade it to solve the problem above.
Fixes #
Reference to #
**Special notes for …

chore: update gradle image version to 5.5.1 for stage template

---

pkg/server/apis/v1alpha1/descriptors/integration.go
pkg/server/biz/scm/bitbucket/server/repos.go
pkg/server/biz/scm/bitbucket/server/server.go
pkg/server/biz/scm/bitbucket/server/v1Client.go
pkg/server/biz/scm/github/github.go
pkg/server/biz/scm/gitlab/gitlabv3.go
pkg/server/biz/scm/gitlab/gitlabv4.go
pkg/server/biz/scm/scm.go
pkg/server/biz/scm/svn/svn.go
pkg/server/handler/v1alpha1/helper.go
pkg/server/handler/v1alpha1/integration.go

As the title suggested.
Fixes #
Reference to #
```release-note
NONE
```

feat(api): support list pull requests of scm repo

---

pkg/server/handler/v1alpha1/workload.go

List working pod, the namespace is wrong.
Fixes #
Reference to #
```release-note
NONE
```

fix: can not list working pods

---

README.md
build/cicd/sonarqube/entrypoint.sh
build/resolver/git/entrypoint.sh
docs/installation.md
pkg/server/biz/integration/cluster/cluster.go
pkg/server/biz/pvc/pvc.go
pkg/server/biz/scm/gitlab/gitlab.go
pkg/server/biz/scm/gitlab/gitlabv3.go
pkg/server/biz/stream/folder.go
pkg/server/biz/stream/folder_test.go
pkg/server/handler/v1alpha1/workflowrun.go
pkg/util/retry/retry.go
pkg/workflow/controller/handlers/pod/operation.go
pkg/workflow/workflowrun/operator.go
pkg/workflow/workflowrun/workload.go
pkg/workflow/workload/pod/builder.go
pkg/workflow/workload/pod/builder_test.go

cherry-pick from v0.9.5 to v0.9.7-alpha  
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

feat(oauth): cherry-pick from v0.9.5 to v0.9.7-alpha

---

helm/cyclone/templates/controller.yaml
pkg/workflow/common/const.go
pkg/workflow/controller/config.go
pkg/workflow/coordinator/coordinator.go
pkg/workflow/workload/pod/builder.go
pkg/workflow/workload/pod/builder_test.go
release/workflow-controller.yaml

Add a init container to copy cyclone toolbox to other init containers, so that those init containers can report realtime logs to cyclone server.
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

feat: collect realtime init container logs

---

cmd/toolbox/fstream/main.go
pkg/server/apis/v1alpha1/descriptors/workflowrun.go
pkg/server/biz/stream/folder.go
pkg/server/handler/v1alpha1/workflowrun.go
pkg/util/websocket/websocket.go
pkg/workflow/coordinator/cycloneserver/client.go

- Fix WebSocket interrupted occasionally
- Add some debug logs
Fixes #
Reference to #
```release-note
NONE
```

fix(log-stream): websocket interrupted occasionally

---

pkg/server/biz/scm/bitbucket/server/server.go

Fix bitbucket token validation will always return true.
Fixes #
Reference to #
```release-note
NONE
```

fix: validate bitbucket token

---

pkg/workflow/controller/handlers/pod/operation.go

In [PR #1214](https://github.com/caicloud/cyclone/pull/1214), we changed  WorkflowRun status check logic, but I found using the `Ready` field to check WorkflowRun status is not right.
> 	// Specifies whether the container has passed its readiness probe.
Ready bool `json:"ready" protobuf:"varint,4,opt,name=ready"`
So we use `StartAt` instead.
Fixes #
Reference to #1214 
```release-note
NONE
```

fix: workflow run status check logic

---

pkg/server/biz/scm/bitbucket/server/server.go

Fixes #
Reference to #
```release-note
NONE
```

fix: use authorization error to token validation fail

---

build/resolver/git/entrypoint.sh

Git clone with "--depth" option will fail when the server is Bitbucket which version less than v0.6.4(This version is not guaranteed to be accurate, I tested v0.6.4 support "--depth", but v0.5.4.9 not support), so we will not use "--depth" when the server is Bitbucket.
Fixes #
Reference to #
```release-note
NONE
```

fix: git clone from bitbucket failed

---

pkg/server/biz/scm/bitbucket/server/server.go
pkg/server/biz/scm/github/github.go
pkg/server/biz/scm/gitlab/gitlab.go
pkg/util/cerr/error.go

Specify connection refused error
Fixes #
Reference to #
```release-note
NONE
```

fix: specify connection refused error

---

pkg/server/biz/scm/gitlab/gitlab.go
pkg/util/cerr/error.go

fix panic: call of reflect.Value.IsNil on zero Value
Fixes #
Reference to #
```release-note
NONE
```

fix(panic): call of reflect.Value.IsNil on zero Value

---

pkg/server/handler/v1alpha1/admin.go
pkg/server/handler/v1alpha1/integration.go
pkg/server/handler/v1alpha1/project.go
pkg/server/handler/v1alpha1/resource.go
pkg/server/handler/v1alpha1/stage.go
pkg/server/handler/v1alpha1/template.go
pkg/server/handler/v1alpha1/tenant.go
pkg/server/handler/v1alpha1/workflow.go
pkg/server/handler/v1alpha1/workflowrun.go
pkg/server/handler/v1alpha1/workflowtrigger.go
pkg/server/handler/v1alpha1/workload.go
pkg/server/types/common.go

out of range panic protection
Fixes #
Reference to #
```release-note
NONE
```

fix: out of range panic protection

---

pkg/server/biz/integration/cluster/cluster.go
pkg/server/biz/pvc/pvc.go

Revert https://github.com/caicloud/cyclone/pull/1191
Fixes #
Reference to #
```release-note
NONE
```

chore: enable PVC watcher

---

pkg/server/biz/usage/usage.go
pkg/server/biz/usage/watcher.go
pkg/server/biz/usage/watcher_test.go

Add tests for PVC watcher
Fixes #
Reference to #
```release-note
NONE
```

test: add tests for pvc watcher

---

release/cyclone-server.yaml
release/workflow-controller.yaml

Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

chore: add mount propagation

---

pkg/workflow/controller/controllers/configmap.go
pkg/workflow/controller/controllers/controller.go
pkg/workflow/controller/controllers/exucution_cluster.go
pkg/workflow/controller/controllers/pod.go
pkg/workflow/controller/controllers/workflow_trigger.go
pkg/workflow/controller/controllers/workflowrun.go
pkg/workflow/controller/handlers/configmap/handler.go
pkg/workflow/controller/handlers/executioncluster/handler.go
pkg/workflow/controller/handlers/interface.go
pkg/workflow/controller/handlers/pod/handler.go
pkg/workflow/controller/handlers/workflowrun/handler.go
pkg/workflow/controller/handlers/workflowtrigger/handler.go

Resync of wfr doesn't take effect, this will result in wfr limits failed.
Fixes #
Reference to #
https://github.com/caicloud/cyclone/issues/1221
```release-note
NONE
```

fix: resync of wfr

---

Makefile

Fixes #
Reference to #
/cc @cd1989 @zhujian7 
```release-note
NONE
```

chores(makefile): add ut coverage for make test

---

pkg/workflow/workflowrun/operator.go

Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

fix: overall status judgement when multiple stage errors

---

README.md

Update invitation link of slack
Fixes #1289
Reference to #
/cc @zhujian7 
```release-note
NONE
```

docs(readme): update invitation link of slack

---

.travis.yml

Good usage of golangci-lint: 
* Install golangci-lint with a fixed version, refer to [CI Installation](https://github.com/golangci/golangci-lint#ci-installation)
> It's highly recommended to install a fixed version of golangci-lint.
* Set `GOGC` to limit memory usage, refer to: [Memory Usage of Golangci-lint](https://github.com/golangci/golangci-lint#memory-usage-of-golangci-lint)
Fixes #1292
Reference to #
```release-note
NONE
```

fix(1292): fix out of memory of golangci-lint

---

.gitignore

- ignore history folder
Fixes #
Reference to #
```release-note
NONE
```

chore(*): ignore history folder

---

cmd/workflow/coordinator/main.go
pkg/common/const.go
pkg/server/biz/stream/folder.go
pkg/server/biz/stream/folder_test.go
pkg/server/handler/v1alpha1/workflowrun.go
pkg/util/websocket/websocket.go
pkg/workflow/coordinator/coordinator.go
pkg/workflow/coordinator/cycloneserver/client.go
pkg/workflow/coordinator/k8sapi/k8sapi.go

Cherry-pick of #1285
Fixes #
Reference to #
```release-note
NONE
```

[cps-2.9] fix: eof of stage logs FolderReader

---

Makefile

Fixes #
Reference to #
```release-note
NONE
```

fix(Makefile): use config file for golangci-lint

---

pkg/server/apis/v1alpha1/descriptors/integration.go
pkg/server/biz/integration/cluster/cluster.go
pkg/server/biz/pvc/pvc.go
pkg/server/biz/usage/watcher.go
pkg/server/handler/v1alpha1/integration.go
pkg/server/handler/v1alpha1/tenant.go
pkg/util/cerr/error.go

Support start and stop pvc watcher
Fixes #
Reference to #
```release-note
NONE
```

feat(api): support start and stop pvc watcher

---

web/.eslintrc
web/src/components/project/component/detail/stage.js
web/src/components/workflow/component/RunWorkflow.js
web/src/components/workflow/component/add/CreateWorkflow.js
web/src/components/workflow/component/add/Form.js
web/src/components/workflow/component/detail/WorkflowRuns.js

- worklofw runs interval repeat request
Fixes #
Reference to #
```release-note
NONE
```

fix(web): worklofw runs interval repeat request

---

pkg/workflow/controller/handlers/workflowtrigger/handler.go

Fixes #
Reference to #
```release-note
NONE
```

fix: workflow trigger controller should only process cron type trigger

---

Makefile
pkg/server/biz/hook/scm.go

Fixes #
Reference to #
```release-note
NONE
```

fix: maybe occur dead lock while register/unregister scm webhook

---

CHANGELOG.md

Add changelog file for [CII Best Practices](https://bestpractices.coreinfrastructure.org/en/projects/2792#changecontrol)
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

chore(changlog): add changelog file for CII

---

build/cicd/sonarqube/entrypoint.sh

- feat: support extension parameters for sonar scanner
- fix: hard-code `sonar.exclusions=vendor/***,node_modules/***` will overwrite the sonar.exclusions config in user's repo(sonar-project.properties)
Fixes #
Reference to #
/cc @supereagle @caosm 
```release-note
NONE
```

fix(sonar): support extension parameters for sonar scanner

---

pkg/workflow/workflowrun/limits.go

Reduce cpu usage caused by go ticker incorrect use
Fixes #
Reference to #
```release-note
NONE
```

fix: reduce cpu usage caused by go ticker incorrect use

---

pkg/apis/cyclone/v1alpha1/zz_generated.deepcopy.go
pkg/workflow/controller/handlers/workflowrun/handler.go
pkg/workflow/workflowrun/operator.go

Fixes #
Reference to #
```release-note
NONE
```

fix: workflow topology lost problem

---

release/cyclone-server.yaml
release/workflow-controller.yaml

Fixes #
Reference to #
/cc @supereagle @bbbmj 
```release-note
NONE
```

chore(release): adjust resource quota

---

web/src/components/workflow/component/stage/AddStage.js

- fix update workflow, display form is incorrect
Fixes #
Reference to #
https://github.com/caicloud/cyclone/issues/1131
```release-note
NONE
```

fix(devops): update workflow display form is incorrect

---

helm/cyclone/templates/controller.yaml
helm/cyclone/values.yaml
pkg/workflow/common/const.go
pkg/workflow/controller/config.go
pkg/workflow/controller/controllers/workflowrun.go
pkg/workflow/controller/handlers/workflowrun/handler.go
pkg/workflow/workflowrun/operator.go
pkg/workflow/workflowrun/parallelism.go
pkg/workflow/workflowrun/parallelism_test.go

Apply parallelism constraint to WorkflowRun execution on both overall scope and Workflow scope.
Give each Workflow a limit-sized waiting queue for WorkflowRun to wait for execution.
```
parallelism:
overall:
maxParallel: 20
maxQueueSize: 100
singleWorkflow:
maxParallel: 3
maxQueueSize: 10
```
Fixes #
Reference to #
```release-note
NONE
```

feat: add WorkflowRun parallelism constraints and waiting queue

---

pkg/workflow/controller/handlers/workflowrun/handler.go
pkg/workflow/workflowrun/parallelism.go

constraints and waiting queue
address code review comments for https://github.com/caicloud/cyclone/pull/1280
Fixes #
Reference to #
```release-note
NONE
```

fix: address code review comments for workflowRun parallelism

---

pkg/apis/cyclone/v1alpha1/workflow_trigger.go
pkg/server/biz/scm/bitbucket/server/webhooks.go
pkg/server/biz/scm/github/github.go
pkg/server/biz/scm/gitlab/gitlab.go
pkg/server/handler/v1alpha1/webhook.go

Fixes #
Reference to #
```release-note
NONE
```

feat(server): PR events support specify target branch

---

pkg/server/apis/v1alpha1/types.go
pkg/server/biz/usage/usage.go
pkg/server/handler/v1alpha1/executioncontext.go

Record pvc usage in list executioncontexts api
List executioncontexts return body:
```
{
"metadata": {
"total": 1,
"itemsLength": 1
},
"items": [
{
"spec": {
"cluster": "compass-stack",
"namespace": "cyclone--devops",
"pvc": "cyclone-pvc-devops"
},
"status": {
"phase": "Ready",
"reservedResources": {
"limits.cpu": "100m",
"limits.memory": "64Mi",
"requests.cpu": "50m",
"requests.memory": "32Mi"
},
"pvc": {
"usage": {
"total": "10.0G",
"used": "0",
"items": {
"workflowruns": "4.0K"
},
"usedPercentage": 0
},
"status": {
"phase": "Bound",
"accessModes": [
"ReadWriteMany"
],
"capacity": {
"storage": "10Gi"
}
}
}
}
}
]
}
```
Fixes #
Reference to #
**Special notes for your …

feat(api): record pvc usage in list executioncontexts api

---

pkg/server/biz/scm/github/github.go
pkg/server/biz/scm/gitlab/gitlab.go

Fixes #
Reference to #
```release-note
NONE
```

fix: delete branch should not trigger workflowrRun

---

pkg/server/biz/pvc/pvc.go
pkg/server/biz/usage/watcher.go

Fix update pvc failed as old watchdog have not been deleting completed
Fixes #
Reference to #
```release-note
NONE
```

fix: update pvc failed as old watchdog have not been deleting completed

---

build/resolver/svn/Dockerfile

Fixes #
Reference to #1340 
```release-note
NONE
```

fix: svn checkout with can't convert string from 'UTF-8' to native encoding

---

release/cyclone-server.yaml

- 修改邮件跳转地址
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

[CPS-4908]fix(cyclone): 修改邮件跳转地址

---

docs/user_guide.md
pkg/apis/cyclone/v1alpha1/workflow_trigger.go
pkg/apis/cyclone/v1alpha1/zz_generated.deepcopy.go
pkg/server/biz/scm/scm.go
pkg/server/biz/scm/svn/svn.go
pkg/server/biz/scm/svn/svn_test.go
pkg/server/handler/v1alpha1/helper.go
pkg/server/handler/v1alpha1/webhook.go
pkg/server/handler/v1alpha1/workflowtrigger.go
pkg/util/exec/exec.go
pkg/util/exec/exec_test.go

svn post commit trigger support selecting repo
Fixes #
Reference to #
```release-note
action required: If users used the SVN Post-Commit trigger workflow feature, you *MUST* reconfigure you SVN server by the new guild.
```

feat: svn post commit trigger support selecting repo

---

helm/cyclone/templates/controller.yaml
helm/cyclone/values.yaml
pkg/server/handler/v1alpha1/tenant.go

- fix invalid controller yaml
- fix can not create default tenant
Fixes #
Reference to #
```release-note
NONE
```

fix: first time deploy error

---

docs/develop/crd.md

Enhancements for caicloud/cyclone#1337
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

chores(docs): update crd docs

---

pkg/server/biz/scm/gitlab/gitlab.go
pkg/server/biz/scm/scm.go

修复之前由于 Rebase 和谐掉了部分 OAuth 的代码导致 Gitlab 的流水线组不能创建的问题。
/cc @zhujian7
```release-note
Fix cannot create pipeline due to OAuth err.
```

fix(OAuth): Fix cannot create pipeline due to OAuth err.

---

web/src/components/public/log/Log.js
web/src/components/workflow/component/stage/TemplateStage.js
web/src/layout/Breadcrumb.js

- Whether the field is required
- Clickable secondary breadcrumbs
- log  component bug fix 
Fixes #
Reference to #
/cc @ladjzero
```release-note
NONE
```

fix(*): fix workflow required field and undefined func

---

web/src/components/workflow/component/add/Graph.js
web/src/components/workflow/component/add/Icons.js
web/src/components/workflowRun/component/detail/index.js
web/src/less/inc.var.less

- running status add animation
Fixes #
Reference to #
/cc @ladjzero 
```release-note
NONE
```

fix(*): running status animation

---

web/src/components/public/log/Log.js
web/src/components/workflow/component/add/Graph.js
web/src/components/workflowRun/component/detail/index.js

- stream log
Fixes #
Reference to #
/cc @ladjzero 
```release-note
NONE
```

feat: stream log

---

cmd/server/main.go
pkg/server/config/config.go
pkg/util/k8s/client.go
release/cyclone-server.yaml

Fixes #
Reference to #
```release-note
NONE
```

feat(server): make qps and brust configurable for k8s client

---

pkg/server/apis/v1alpha1/descriptors/workflowrun.go
pkg/server/handler/v1alpha1/workflowrun.go

Fixes #
Reference to #
/cc @supereagle @qiuxiaolian 
```release-note
NONE
```

chore: get tenant info from query if header omitted

---

pkg/server/handler/init.go
pkg/workflow/workflowrun/operator.go

Fix overall last transition time not correct
Fixes #
Reference to #
```release-note
NONE
```

fix: overall last transition time not correct

---

Makefile
docs/installation.md
helm/cyclone/Chart.yaml
helm/cyclone/values.yaml
manifests/templates/cicd/cd.yaml
manifests/templates/cicd/sonarqube.yaml

Fixes #
Reference to #
```release-note
NONE
```

feat(*): update helm chart for release v1.0

---

release/cyclone-server.yaml

Fixes #
Reference to #
/cc @qianlei90 @supereagle @hyy0322 
```release-note
NONE
```

[cps-2.8]chore(release): adjust qps and burst for kube client

---

release/cyclone-server.yaml

Fixes #
Reference to #
/cc @qianlei90 @supereagle @hyy0322 
```release-note
NONE
```

chore(release): adjust qps and burst for kube client

---

build/resolver/image/entrypoint.sh

Fixes #
Reference to #
```release-note
NONE
```

feat: push image with retry logic

---

build/watcher/Dockerfile
build/watcher/pvc-watcher.sh

Unify base image to alpine:3.8, Fix #1364 (review)
Fixes #
Reference to #
```release-note
NONE
```

refactor: use alpine base image for watcher

---

Makefile
hack/read_cpus_available.sh

- change REPOSITORIES to REPOSITORY
- limit CPU while building
Fixes #
Reference to #
```release-note
NONE
```

chore: normalize makefile

---

build/resolver/svn/Dockerfile

Unify base image to `alpine:3.8` (Fix https://github.com/caicloud/cyclone/pull/1364#pullrequestreview-343867201) , and locale setting is no longer needed in the alpine, related PR: https://github.com/caicloud/cyclone/pull/1341.
Fixes #
Reference to #
```release-note
NONE
```

refactor(svn): use alpine base image for svn

---

Makefile
hack/read_cpus_available.sh

cherry-pick of #1375 
Fixes #
Reference to #
```release-note
NONE
```

[cps-2.8]chore: normalize makefile

---

Makefile
hack/read_cpus_available.sh

cherry-pick of #1375
Fixes #
Reference to #
```release-note
NONE
```

[cps-2.9]chore: normalize makefile

---

Makefile
build/cicd/cd/Dockerfile
build/cicd/cd/Dockerfile.arm64
build/cicd/sonarqube/Dockerfile
build/cicd/sonarqube/Dockerfile.arm64
build/cicd/sonarqube/sonar-runner.properties
build/resolver/git/Dockerfile.arm64
build/resolver/image/Dockerfile
build/resolver/image/Dockerfile.arm64
build/resolver/svn/Dockerfile.arm64
build/server/Dockerfile.arm64
build/toolbox/Dockerfile.arm64
build/watcher/Dockerfile.arm64
build/web/Dockerfile
build/web/Dockerfile.arm64
build/web/Dockerfile.arm64.local
build/workflow/controller/Dockerfile
build/workflow/controller/Dockerfile.arm64
build/workflow/coordinator/Dockerfile.arm64

Fixes #
Reference to #
/cc @supereagle @hyy0322 @liwandaniel 
```release-note
NONE
```

feat: support arm64

---

helm/cyclone/templates/server.yaml
helm/cyclone/values.yaml
pkg/meta/annotations.go
pkg/meta/labels.go
pkg/server/apis/v1alpha1/descriptors/project.go
pkg/server/apis/v1alpha1/types.go
pkg/server/biz/accelerator/accelerate.go
pkg/server/biz/accelerator/cleaner/clean.go
pkg/server/biz/accelerator/cleaner/clean_test.go
pkg/server/common/const.go
pkg/server/config/config.go
pkg/server/handler/v1alpha1/project.go
release/cyclone-server.yaml

Add api to cleanup acceleration cache
TODO in the future:
Fixes #
Reference to #
```release-note
NONE
```

feat: add api to cleanup acceleration cache

---

Makefile
build/resolver/http/Dockerfile
build/resolver/http/entrypoint.sh
helm/cyclone/templates/controller.yaml
pkg/apis/cyclone/v1alpha1/resource.go
pkg/server/apis/v1alpha1/descriptors/workflowrun.go
pkg/server/apis/v1alpha1/types.go
pkg/server/handler/v1alpha1/helper.go
pkg/server/handler/v1alpha1/workflowrun.go
pkg/util/http/http.go
pkg/workflow/common/const.go
pkg/workflow/workload/pod/builder.go
pkg/workflow/workload/pod/builder_test.go
release/workflow-controller.yaml

- Workflow Engine supports a new type resource: `Http`，you can use this feature to pull/push resources from/to a remote server.
- Cyclone Server provides APIs to receive and send artifacts. 
Fixes #
Reference to #
```release-note
NONE
```

feat: support http type resource

---

pkg/server/apis/v1alpha1/descriptors/workflowrun.go
pkg/server/handler/v1alpha1/workflowrun.go

ref to: https://github.com/caicloud/cyclone/pull/1189#pullrequestreview-382564973
Fixes #
Reference to #
```release-note
NONE
```

fix: remove download param for artifacts download api

---

build/resolver/svn/entrypoint.sh

Similar to: https://github.com/caicloud/cyclone/pull/1156
Fixes #
Reference to #
```release-note
NONE
```

refactor: use mkdir to acquire lock in svn resolver

---

build/cicd/sonarqube/Dockerfile.arm64
build/resolver/image/Dockerfile.arm64
build/workflow/coordinator/Dockerfile.arm64

Fixes #
Reference to #
```release-note
NONE
```

fix: arm64 for docker and jq

---

pkg/server/apis/v1alpha1/descriptors/integration.go
pkg/server/apis/v1alpha1/descriptors/project.go
pkg/server/apis/v1alpha1/descriptors/storage.go
pkg/server/apis/v1alpha1/descriptors/workflow.go
pkg/server/apis/v1alpha1/descriptors/workflowrun.go

Fixes #
Reference to #
/cc @zhujian7 @iawia002 
```release-note
NONE
```

refact(*): use children descriptor to simplify api definition

---

build/resolver/http/entrypoint.sh
pkg/server/biz/usage/watcher_test.go

Fixes #
Reference to #
```release-note
NONE
```

feat: support matching files by find_options for http resource

---

build/resolver/svn/Dockerfile
cmd/server/main.go
pkg/server/config/config.go
pkg/util/k8s/client.go
release/cyclone-server.yaml

fix(cyclone):merge with tag v0.9.8, update to v0.9.8-alpha-oem-hr-4
Fixes #
Reference to #
/cc @wzqnls @zhujian7 
```release-note
NONE
```

[HAIER-89]fix(cyclone):merge with tag v0.9.8, update to v0.9.8-alpha-oem-hr-4

---

pkg/workflow/workflowrun/utils.go

Fixes #
Reference to #
```release-note
NONE
```

fix: process trivial stage cancellation

---

pkg/server/biz/accelerator/cleaner/clean.go
pkg/server/biz/accelerator/cleaner/clean_test.go

Fixes #
Reference to #
```release-note
NONE
```

fix: delete old cache cleanup pod while server restart

---

cmd/server/main.go
cmd/workflow/controller/main.go
pkg/workflow/controller/config.go
pkg/workflow/controller/controllers/configmap.go
pkg/workflow/controller/controllers/controller.go
pkg/workflow/controller/controllers/deletedresources.go
pkg/workflow/controller/controllers/exucution_cluster.go
pkg/workflow/controller/controllers/pod.go
pkg/workflow/controller/controllers/workflow_trigger.go
pkg/workflow/controller/controllers/workflowrun.go
pkg/workflow/controller/handlers/configmap/handler.go
pkg/workflow/controller/handlers/executioncluster/handler.go
pkg/workflow/controller/handlers/interface.go
pkg/workflow/controller/handlers/pod/handler.go
pkg/workflow/controller/handlers/workflowrun/handler.go
pkg/workflow/controller/handlers/workflowtrigger/cron_job.go
pkg/workflow/controller/handlers/workflowtrigger/handler.go
pkg/workflow/workflowrun/podwatcher.go
pkg/workflow/workflowrun/timeout.go
pkg/workflow/workflowrun/timeout_test.go
release/workflow-controller.yaml

Fixes #
Reference to #https://github.com/caicloud/cyclone/issues/1429
```release-note
NONE
```

perf(controller): support starting multi workers

---

build/cicd/sonarqube/entrypoint.sh

Fixes #https://github.com/caicloud/cyclone/issues/1438
Reference to #
```release-note
NONE
```

fix(sonar): trim suffix / for the server

---

build/cicd/sonarqube/entrypoint.sh
build/cicd/sonarqube/result.example.json

Fixes #https://github.com/caicloud/cyclone/issues/1440
Reference to #
```release-note
NONE
```

fix(sonar): return error when quality gate failed

---

Makefile

Fixes #
Reference to #
```release-note
NONE
```

chore(makefile): docker run using interactive mode

---

pkg/workflow/workflowrun/podwatcher.go
pkg/workflow/workflowrun/podwatcher_test.go

Fixes #
Reference to #
/cc @hyy0322 
```release-note
NONE
```

fix: check channel error before using

---

pkg/workflow/workflowrun/timeout.go

Fixes #
Reference to #
/cc @hyy0322 
```release-note
NONE
```

fix: overall start time lost when wfr timeout

---

pkg/workflow/controller/controllers/controller.go
pkg/workflow/controller/handlers/pod/operation.go
pkg/workflow/controller/handlers/workflowrun/handler.go
pkg/workflow/workflowrun/gc.go

When we delete a workflow that has pods running, the pods will remain in Terminating status after the workflow deletion.
Old logic details: 
1. **Delete the workflow**, will delete the related workflowRuns(OwnerReferences)
2. Delete the workflowRun will delete the related pods, **and wait until the pods deleting completed**
3. Delete the pod **will get the workflow** and update status of the workflowRun, workflow has already been deleted so failed.
Actually, when the workflow is under deleting(deletionTimestamp is not nil)，we do not need to update status of the workflowRun, so the problem will be solved.
Fixes #
Reference to #
/cc …

fix(controller): pod stuck on terminating while related wf deleted

---

helm/cyclone/templates/controller.yaml
release/workflow-controller.yaml

Fixes #
Reference to #
```release-note
NONE
```

fix: change log level of workflow controller from debug to info

---

Makefile
build/base/alpine/Dockerfile
build/base/alpine/Dockerfile.arm64
build/cicd/cd/Dockerfile
build/cicd/cd/Dockerfile.arm64
build/resolver/git/Dockerfile
build/resolver/git/Dockerfile.arm64
build/resolver/http/Dockerfile
build/resolver/http/Dockerfile.arm64
build/resolver/image/Dockerfile
build/resolver/image/Dockerfile.arm64
build/resolver/svn/Dockerfile
build/resolver/svn/Dockerfile.arm64
build/server/Dockerfile
build/server/Dockerfile.arm64
build/toolbox/Dockerfile
build/toolbox/Dockerfile.arm64
build/watcher/Dockerfile
build/watcher/Dockerfile.arm64
build/workflow/controller/Dockerfile
build/workflow/controller/Dockerfile.arm64
build/workflow/coordinator/Dockerfile
build/workflow/coordinator/Dockerfile.arm64

- bump alpine from 3.8 to 3.12
- bump git from 2.18 to 2.26
In order to fix
- https://github.com/git/git/security/advisories/GHSA-hjc9-x69f-jqj7
- https://github.com/git/git/security/advisories/GHSA-qm7j-c969-7j4q
- filter sensitive information printing when git fetch/clone failed
Fixes #
Reference to #
/cc @hyy0322 @supereagle @bbbmj
```release-note
NONE
```

fix: bump git version to 2.26.2

---

build/resolver/image/entrypoint.sh

Disable line wrapping for base64 encoded string.
Fixes #
Reference to # https://stackoverflow.com/questions/19952621/is-it-ok-to-remove-newline-in-base64-encoding
```release-note
NONE
```

fix(resolver): replace line feed

---

pkg/server/biz/scm/gogs/gogs.go

…th failed
change errors to nirvana errors, because front won't represent 5xx errors
Fixes #
Reference to #
/cc @zhujian7 @tosone 
```release-note
NONE
```

fix(gogs): change errors type to nirvana error

---

Makefile
build/base/alpine/Dockerfile
build/base/alpine/Dockerfile.arm64
build/cicd/cd/Dockerfile
build/cicd/cd/Dockerfile.arm64
build/resolver/git/Dockerfile
build/resolver/git/Dockerfile.arm64
build/resolver/image/Dockerfile
build/resolver/image/Dockerfile.arm64
build/resolver/svn/Dockerfile
build/resolver/svn/Dockerfile.arm64
build/server/Dockerfile
build/server/Dockerfile.arm64
build/toolbox/Dockerfile
build/toolbox/Dockerfile.arm64
build/watcher/Dockerfile
build/watcher/Dockerfile.arm64
build/workflow/controller/Dockerfile
build/workflow/controller/Dockerfile.arm64
build/workflow/coordinator/Dockerfile
build/workflow/coordinator/Dockerfile.arm64

- bump alpine from 3.8 to 3.12
- bump git from 2.18 to 2.26
In order to fix
- https://github.com/git/git/security/advisories/GHSA-hjc9-x69f-jqj7
- https://github.com/git/git/security/advisories/GHSA-qm7j-c969-7j4q
- filter sensitive information printing when git fetch/clone failed
Cherry-pick https://github.com/caicloud/cyclone/pull/1475
Fixes #
Reference to #
/cc @hyy0322 
```release-note
NONE
```

[cps-2.8]fix: bump git version to 2.26.2 (#1475)

---

pkg/server/biz/scm/gitlab/gitlab.go

Fixes #
Reference to #
```release-note
NONE
```

fix: should not mutate users input silently

---

build/resolver/git/entrypoint.sh

- clone with depth flag first, if fail (some version of bitbucket not support), retry without depth flag.
Fixes #
Reference to #
```release-note
NONE
```

fix: optimize git clone process

---

pkg/server/biz/scm/gitlab/gitlab.go

Fixes #
Reference to #
/cc @hyy0322 @huxiangtao 
```release-note
NONE
```

chore: fix typo of gitlab error message

---

pkg/server/biz/scm/scm.go
pkg/util/cerr/error.go

only check token type auth, also need to check password type auth.
Fixes #
Reference to #
```release-note
NONE
```

fix: validate scm auth info problem

---

pkg/server/biz/integration/cluster/cluster.go

Fixes #
Reference to #
```release-note
NONE
```

fix: connection refused should not block close cluster

---

release/cyclone-server.yaml
release/workflow-controller.yaml

Fixes #
Reference to #
/cc @hyy0322 
```release-note
NONE
```

chore: update release yaml for infra

---

.gitignore

Fixes #
Reference to #
```release-note
NONE
```

chore(git): add Intellij generated file to git ignore

---

pkg/workflow/common/const.go
pkg/workflow/common/owner.go
pkg/workflow/common/owner_test.go
pkg/workflow/workflowrun/operator.go
pkg/workflow/workload/pod/builder.go
pkg/workflow/workload/pod/builder_test.go

cherry pick: #1506 #1509 
Fixes #
Reference to #
/cc @hyy0322 
```release-note
NONE
```

fix: add workflow and project name info for pods created by cyclone

---

Makefile
pkg/workflow/common/const.go
pkg/workflow/controller/config.go
pkg/workflow/controller/controllers/exucution_cluster.go
pkg/workflow/controller/controllers/pod.go
pkg/workflow/controller/controllers/workflow_trigger.go
pkg/workflow/controller/controllers/workflowrun.go
pkg/workflow/controller/handlers/workflowrun/handler.go
pkg/workflow/workflowrun/limits.go

Manually cherry-pick https://github.com/caicloud/cyclone/commit/4319aaf66fe10a4e91d70b6d56f89ad46e2b26a9 into branch cps-2.10.
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

feat(controllers): make resyncPeriod configurable (#1519)

---

helm/cyclone/templates/service-account.yaml
pkg/meta/annotations.go
pkg/workflow/coordinator/k8sapi/k8sapi.go

/kind feature
/area cicd
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

feat(coordinator): drop the seccomp annotation before setting results

---

pkg/workflow/common/const.go
pkg/workflow/workload/pod/builder.go

coordinator no longer depends on Docker now.
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

fix(workflow): remove unnecessary volume from coordinator

---

pkg/server/biz/scm/gogs/gogs.go
pkg/util/cerr/error.go

/kind bug
/area cicd
/cc @zhujian7 
```release-note
fix(*): Fix error that username or password is not correct.
```

fix(*): Fix error that username or password is not correct.

---

pkg/server/biz/integration/cluster/cluster.go
pkg/util/cerr/error.go
pkg/workflow/controller/config.go

cluster lost should not block close cluster
Fixes #
Reference to #
/cc @knight42 
```release-note
Cluster lost does not block close cluster
```

fix: cluster lost should not block close cluster

---

OWNERS

Fixes #
Reference to #
/cc @knight42 
```release-note
none
```

chore: update owners

---

manifests/cyclone/templates/controller.yaml
manifests/cyclone/templates/server.yaml

/kind bug
/kind cleanup
/area cicd
Correct image names.
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

fix(chart): correct images

---

Makefile
pkg/workflow/values/ref/ref.go
pkg/workflow/values/ref/ref_test.go
pkg/workflow/values/ref/secret.go
pkg/workflow/values/ref/secret_test.go
pkg/workflow/workload/pod/builder.go

/kind cleanup
/area cicd
* Decouple the secret resolver from the kubernetes clientset
* Add `-trimpath` to build flags
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

refactor: Decouple the secret resolver from the kubernetes clientset

---

manifests/cyclone/values.yaml

/kind documentation
/area cicd
chore(manifest): unify the platform config info
Fixes #
Reference to #
```release-note
chore(manifest): unify the platform config info
```

chore(manifest): unify the platform config info

---

manifests/cyclone/templates/controller.yaml
manifests/cyclone/templates/server.yaml
manifests/cyclone/values.yaml

/kind cleanup
/area cicd
Fix the port value in chart.
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

chore(*): update chart

---

manifests/cyclone/Chart.yaml

/kind upgrade
/area cicd
Bump chart version to v1.2.0-alpha.3
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

chore(chart): bump version to v1.2.0-alpha.3

---

Makefile
pkg/server/handler/init.go
pkg/server/handler/v1alpha1/webhook.go
pkg/server/handler/v1alpha1/workflowrun.go
pkg/util/k8s/client.go
pkg/workflow/common/event_recorder.go

/kind feature
/area cicd
Automatically cancel previous builds if they are triggered by PR event.
Fixes #
Reference to #
/cc @zhujian7 
```release-note
Automatically cancel previous builds if they are triggered by PR event.
```

feat(webhook): cancel previous build

---

pkg/server/biz/scm/github/github.go
pkg/util/retry/retry.go

/kind feature
/area cicd
Retry creating status on GitHub on error.
Fixes #
Reference to #
/cc @zhujian7 
```release-note
feat(github): retry CreateStatus on error
```

feat(github): retry CreateStatus on error

---

pkg/server/biz/scm/github/github.go
pkg/util/retry/retry.go

/kind feature
/area cicd
Retry `github.CreateStatus` on error.
Fixes #
Reference to #
/cc @zhujian7 
```release-note
cps-2.10-infra: retry github.CreateStatus on error.
```

[cps-2.10-infra] feat(github): retry CreateStatus

---

pkg/server/handler/init.go
pkg/server/handler/v1alpha1/webhook.go
pkg/server/handler/v1alpha1/workflowrun.go
pkg/util/k8s/client.go
pkg/workflow/common/event_recorder.go

/kind feature
/area cicd
Manually cherry-pick #1541 
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

[cps-2.10-infra] feat(webhook): cancel previous build

---

pkg/apis/cyclone/v1alpha1/workflow_run.go
pkg/server/biz/scm/github/github.go
pkg/server/handler/v1alpha1/notification.go
pkg/server/handler/v1alpha1/workflowrun.go

/kind bug
/area cicd
Do not update PR status if WorkflowRun is canceled automatically.
Complement #1541 
Fixes #
Reference to #
/cc @zhujian7 
```release-note
fix: do not update PR status if WorkflowRun is canceled automatically.
```

fix(*): do not update PR status if wfr is canceled automatically

---

manifests/cyclone/templates/server.yaml

/area cicd
/kind cleanup
Specify the namespace of cyclone-server service.
Fixes #
Reference to #
/cc @zhujian7 
```release-note
Specify the namespace of cyclone-server service.
```

fix(chart): specify namespace of service

---

build/cicd/sonarqube/entrypoint.sh

/area cicd
/kind bug
Make SonarQube support Java projects with multiple modules.
Fixes #
Reference to #
/cc @zhujian7 
```release-note
Make SonarQube support Java projects with multiple modules.
```

fix(sonarqube): support java projects with multiple modules

---

manifests/cyclone/templates/server.yaml
manifests/cyclone/values.yaml
pkg/server/biz/hook/scm.go
pkg/server/config/config.go

/area cicd
/kind cleanup
* Correct notification url in chart
* Use webhook url template
Fixes #
Reference to #
/cc @zhujian7 
```release-note
* Correct notification url in chart
* Switch to webhook url template
```

refactor(*): correct notification url & switch to webhook url template

---

manifests/cyclone/Chart.yaml

/area cicd
/kind cleanup
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

fix(chart): upgrade version to v1.2.0-rc

---

manifests/cyclone/templates/server.yaml

/area cicd
/kind cleanup
Rename pipeline to pipeline-server in helm chart.
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

chore(chart): rename pipeline to pipeline-server

---

manifests/cyclone/templates/server.yaml
pkg/server/handler/v1alpha1/webhook.go

/area cicd
/kind cleanup
* Only set LabelWorkflowRunPRRef when needed(e.g. we don't need to set this label if the workflorRun is trigger by tag release)
* Correct storageClass name
Fixes #
Reference to #
/cc @zhujian7 
```release-note
* Only set LabelWorkflowRunPRRef if workflowRun is triggered by PR
* Change storageClass name to `platform-storageclass`
```

fix: only set LabelWorkflowRunPRRef when needed and correct storageClass

---

manifests/cyclone/Chart.yaml
manifests/cyclone/templates/controller.yaml
manifests/cyclone/templates/server.yaml
manifests/cyclone/values.yaml

/area cicd
/kind cleanup
Update storageClass & version
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

chore(chart): update storageClass & version

---

pkg/server/biz/scm/github/github.go

/area cicd
/kind bug
Switch to `github.BasicAuthTransport` to avoid 401 response from github.
Fixes #
Reference to #
/cc @zhujian7 
```release-note
fix(github): use BasicAuthTransport
```

fix(github): use BasicAuthTransport

---

pkg/server/biz/scm/github/github.go

/area cicd
/kind bug
Manually cherry-pick #1564 to cps-2.10.
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

[cps-2.10] fix(github): use BasicAuthTransport

---

pkg/server/handler/v1alpha1/webhook.go

/area cicd
/kind bug
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

[cps-2.10] fix(webhook): only set PRRef label if wfr is trigger by PR

---

CHANGELOG.md
docs/design.md
docs/user_guide.md

/area cicd
/kind documentation
**What this PR does / why we need it**: Fix(docs): fix typos in docs
Fixes #
Reference to #
/cc @zhujian7 
```release-note
Fix(docs): fix typos in docs
```

Fix(docs): fix typos in docs
