.travis.yml
docker-compose-dev.yml
docker/manager.go
scripts/local-up.sh
tests/common/utils.go
tests/run-e2e.sh
tests/yaml/yaml_test.go
utils/utils_test.go
websocket/application.go
worker/ci/helper_test.go
worker/ci/runner/docker.go
worker/ci/runner/docker_test.go
worker/ci/yaml/yaml_test.go
worker/clair/clair.go
worker/cyclone-worker.go
worker/helper/helper_test.go

add test cases

---

worker/ci/manager.go
worker/clair/clair.go

1、 add log in log file when the specified  caicloud.yaml is not exsited 
2、 adjust the order of the  vulnerabilities from  clair checking

add log to log file and adjust the order of the  vulnerabilities from  clair checking

---

event/event.go
worker/ci/manager.go
worker/log/log.go
worker/vcs/manager.go

1、increase the check to prevent crashes
2、set service status according event's status
3、add log info about parsing yaml

add  parsing yaml log in caicloud.yaml ; increase more check when clone code

---

docker/manager.go

fix issue about pulling all tags when image name which dosen't have tag name

add latest tag for image name which dosen't have tag name

---

pkg/server/manager/pipeline.go
store/pipelineRecord.go

Fix cascaded deletion error for pipelines and projects

---

worker/ci/runner/docker.go

fix(#207): output path is relative path instead of absolute path

---

pkg/server/manager/pipelineRecord.go

fix(server): allow to get log for aborted pipeline record

---

api/conversion/conversion.go
worker/worker.go

**Changes**
set '$commitID[:7]-$createTime' instead of random string as default pipelineRecord.name 
**Reviewers**
- @supereagle please review
**Checklist**

feat(server): set default name when name empty in creating pipeline record

---

worker/worker.go

**Changes**
/cc @zz-bmj @LiangXugang

fix(#253): use record name as the image tag if not empty

---

cloud/k8s.go
cloud/worker.go
event/event.go
event/operations.go
pkg/api/types.go
pkg/server/manager/project.go

**Changes**
/cc @superxi911  @LiangXugang

feat(#255): make the namespace of workers configurable for k8s cloud

---

event/event.go

**Changes**
**Reviewers**
**Checklist**

fix(#252;#258): ensure terminating worker with error before delete fail event

---

event/event.go

update dueTime to workerInfo in event
**Changes**
**Reviewers**
**Checklist**

fix: update workerInfo after worker.Do()

---

pkg/scm/provider/github.go
pkg/scm/provider/gitlab.go
pkg/scm/scm.go

**Changes**
**Reviewers**
**Checklist**

fix(#278): check token when creat/update project with token

---

worker/worker.go

Cherry pick #256 to release-0.1.1

---

LICENSE

The Apache 2.0 license includes an Appendix about how to apply the
license terms to files. We should not modify the license file and
instead should tell people what to do as far as dates, etc in the devel
guides.
**Changes**
xref:  [LICENSE: revert modifications to Apache license](
https://github.com/kubernetes/kubernetes/commit/d30db1f9a915aa95402e1190461469a1889d92be)

fix(309): keep the license itself untouched

---

pkg/docker/client.go

Add registry auth info into Docker manager to support pushing and pulling images from registry.
Fixes partially #319
/cc @bbbmj 
```release-note
NONE
```

feat(#319): add registry auth info into Docker manager

---

api/conversion/conversion.go
api/conversion/types.go
api/types.go
cloud/k8s.go
cloud/worker.go
event/event.go
event/operations.go
pkg/api/types.go
worker/ci/runner/docker.go
worker/ci/runner/docker_test.go

Use cache volume to speed up pipeline
Fixes #346
/cc @bbbmj 
```release-note
Cache dependency to speed up pipeline.
```

feat(#346): use cache volume to speed up pipeline

---

cmd/worker/options.go
pkg/docker/client.go
pkg/worker/cycloneserver/client.go
pkg/worker/options.go
pkg/worker/scm/manager.go
pkg/worker/scm/provider/git.go
pkg/worker/stage/stage.go
pkg/worker/worker.go

Run based on pipeline config instead of caicloud.yaml.
Fixes #308
/cc @bbbmj 
```release-note
Refactor worker: Run based on pipeline config instead of caicloud.yaml.
```

feat(#308): refactor worker to run based on pipeline config instead of caicloud.yaml

---

pkg/event/manager.go

terminate worker after worker exited
Fixes #368 
```release-note
NONE
```

bug(server):terminate worker after worker exited

---

.travis.yml

Remove Go 1.7 and add Go 1.9
Go 1.7 is not supported after update deps. 
xref: https://travis-ci.org/caicloud/cyclone/jobs/357780015#L480
Fixes #
```release-note
Not support Go 1.7 and add the support of Go 1.9.
```

Remove Go 1.7 and add Go 1.9

---

pkg/server/manager/pipeline.go

statistic of pipeline the divisor cannot be 0
Fixes #
```release-note
NONE
```

fix:fix bug statistic of pipeline the divisor cannot be 0

---

pkg/scm/provider/github.go
pkg/scm/provider/gitlab.go
pkg/scm/provider/svn.go
pkg/scm/scm.go
pkg/worker/worker.go

tag is always created based on master for Gitlab
Fixes #425 
```release-note
NONE
```

fix(gitlab):tag is always created based on master for Gitlab

---

pkg/server/router/webhook.go
pkg/worker/scm/provider/git.go

Fixes #459 
```release-note
NONE
```

fix(webhook):executing pipeline failed when the trigger is PR webhook

---

pkg/cloud/kubernetes/kubernetes.go

Fixes #540 
Reference to #
```release-note
NONE
```

fix:pod should be deleted while creating worker timeout

---

pkg/server/manager/pipeline.go
pkg/util/http/errors/format.go

Fixes #
Reference to #
```release-note
NONE
```

fix: add some prompt message when create webhook failed

---

pkg/api/v1/descriptor/pipelineRecord.go

response the right content-type header in pipelineRecord logs API
Fixes #589
Reference to #589
```release-note
NONE
```

add MIMEText Producer to pipelineRecord Api Descriptor

---

pkg/api/v1/handler/webhook.go
pkg/scm/provider/github/github.go
pkg/scm/provider/gitlab/gitlabv3.go
pkg/scm/provider/gitlab/gitlabv4.go
pkg/scm/provider/svn/svn.go
pkg/scm/scm.go
pkg/server/manager/pipeline.go

- fix can not update svn hooks
- get svn repo info by main repo url instead of svn server url
Fixes #
Reference to #
```release-note
NONE
```

fix: support update svn hooks

---

build/worker/Dockerfile
docs/api/v1/api.md
pkg/api/helper.go
pkg/api/types.go
pkg/api/v1/descriptor/cloud.go
pkg/api/v1/descriptor/descriptor.go
pkg/api/v1/descriptor/integration.go
pkg/api/v1/handler/handler.go
pkg/api/v1/handler/integration.go
pkg/event/manager.go
pkg/server/manager/integration.go
pkg/store/integration.go
pkg/store/store.go
pkg/util/http/http.go
pkg/worker/common/constant.go
pkg/worker/integrate/manager.go
pkg/worker/integrate/provider/sonar.go
pkg/worker/scm/manager.go
pkg/worker/stage/helper.go
pkg/worker/stage/stage.go
pkg/worker/worker.go

Fixes #
Reference to #
/cc @ladjzero @cd1989 @supereagle @qiuxiaolian 
```release-note
NONE
```

feat: support code scan with sonarqube

---

pkg/workflow/workflowrun/timeout.go

Fix the problem when a wfr not found, but the timeout processor keeps gc it.
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

fix: timeout processor when wfr not found

---

pkg/server/handler/v1alpha1/helper.go
pkg/server/handler/v1alpha1/tenant.go

when create tenant, use default value of pvc size and resource quota if they are empty
Fixes #
Reference to #
```release-note
NONE
```

fix: use default value of pvc size and resource quota if they are empty

---

manifests/generate.sh

make deploy may return error
```
REGISTRIES=xxx AUTH=admin:adminadmin PVC=xxxx make deploy 
./manifests/generate.sh --registry=xxx --auth=admin:adminadmin --version=v0.9.2 --pvc=xxxx
sed: -e expression #2, char 96: unterminated `s' command
make: *** [Makefile:186: deploy] Error 1
```
Fixes #
Reference to #
/cc @cd1989 @zhujian7 
```release-note
NONE
```

add arg -w0 to base64, fix make deploy error

---

pkg/server/handler/v1alpha1/workflowrun.go
pkg/workflow/controller/handlers/workflowrun/handler.go

Workflow-Controller crashed as workflowRef nil 
```
/Users/zhujian/code/src/github.com/caicloud/cyclone/pkg/workflow/controller/controllers/controller.go:57
/usr/local/Cellar/go/1.11.4/libexec/src/runtime/asm_amd64.s:1333
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf8cd3a]
goroutine 65 [running]:
github.com/caicloud/cyclone/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
/Users/zhujian/code/src/github.com/caicloud/cyclone/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x108
panic(0x10c73e0, 0x1da7ef0) …
```

fix: controller crash as workflowRef nil when create workflowrun

---

pkg/server/apis/v1alpha1/descriptors/workflowrun.go

Fixes #
Reference to #
```release-note
NONE
```

fix: correct produce content type of workflowrun logs

---

pkg/server/apis/v1alpha1/descriptors/workload.go
pkg/server/common/const.go
pkg/server/handler/v1alpha1/workload.go

Add api to list all working pods for one tenant to let users knows about the workload of their workflows.
Fixes #
Reference to #
```release-note
NONE
```

feat(server): add api to list all pods for one tenant

---

pkg/workflow/workflowrun/name.go
pkg/workflow/workflowrun/pod.go

Set default container name if not set.
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

feat: generate default container name if not set

---

Makefile
build/watcher/Dockerfile
build/watcher/pvc-watcher.sh
cmd/server/main.go
manifests/cyclone.yaml.template
pkg/server/apis/v1alpha1/descriptors/usage.go
pkg/server/apis/v1alpha1/types.go
pkg/server/biz/statistic/usage.go
pkg/server/biz/templates/templates.go
pkg/server/common/const.go
pkg/server/config/config.go
pkg/server/handler/v1alpha1/integration.go
pkg/server/handler/v1alpha1/usage.go
pkg/util/http/http.go
release/cyclone-server.yaml

Deploy a PVC usage watcher pod for each execution namespace to collect PVC usage information.
PVC usage info would be set in namespace annotation:
```
storage.cyclone.io/usage: '{"total":"10.0G","used":"0","items":{"caches":"4.5K","workflowruns":"4.5K"}}'
```
Fixes #
Reference to #
```release-note
NONE
```

Pvc usage collect

---

pkg/apis/cyclone/v1alpha1/workflow.go
pkg/workflow/workflowrun/utils.go
pkg/workflow/workflowrun/utils_test.go

Add field 'trivial' to stages in Workflow, to indicate whether workflow can tolerate failure of the stage.
If a stage is trivial to a workflow, failure of the stage won't affect the overall stage of the workflow.
Fixes #
Reference to #
```release-note
NONE
```

feat: whether a stage in workflow is trivial

---

pkg/workflow/workload/pod/builder.go

Fixes #
Reference to #
```release-note
NONE
```

fix: use args instead of command for dind

---

build/resolver/git/Dockerfile
build/resolver/git/entrypoint.sh

When NFS PV is used, git resolver would fail due to `flock` failed to lock file. This problem can 
be solved by a new version of `flock`.
Fixes #878
Reference to #
```release-note
NONE
```

fix: use ubuntu for git resolve to address flock problem in nfs

---

pkg/meta/labels.go
pkg/server/handler/v1alpha1/template.go
pkg/server/handler/v1alpha1/workflowrun.go

we wish system admin tenant have two types of templates:
- templates shared among tenants with built-in label
- templates cannot be shared(private) without built-in label
Fixes #
Reference to #
```release-note
NONE
```

chore: list system builtin templates with builtin label

---

pkg/workflow/workflowrun/operator.go
pkg/workflow/workflowrun/utils.go

Init all stages' status to pending.
Fixes #
Reference to #
```release-note
NONE
```

fix: init stages status in wfr

---

pkg/server/handler/v1alpha1/template.go

* Rename `buildin` to `builtin` for template type query
* Add param validation for  template type query
Fixes #
Reference to #
```release-note
NONE
```

fix: rename template query type to keep consistent with label

---

build/resolver/git/entrypoint.sh
pkg/workflow/workflowrun/operator.go

Some comments in resolver entrypoint.sh is outdated.
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

fix: gc pod memory quota limit

---

pkg/workflow/workflowrun/operator.go
pkg/workflow/workflowrun/operator_test.go

The overall status of wfr may be incorrect in some cases.
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

fix: wfr overall status when still some stage pending

---

pkg/server/handler/v1alpha1/helper.go
pkg/server/handler/v1alpha1/project.go
pkg/server/handler/v1alpha1/tenant.go
pkg/server/handler/v1alpha1/workflow.go
pkg/server/handler/v1alpha1/workflowrun.go

Delete logs in PVC while deleting associated cyclone resources, including:
- tenant
- project
- workflow
- workflowrun
Fixes #
Reference to #
```release-note
NONE
```

fix: delete logs in pvc while deleting associated cyclone resources

---

pkg/meta/labels.go
pkg/workflow/controller/controllers/pod.go
pkg/workflow/workload/pod/builder.go

Pod controller missed GC pods. The label selector should be `pod.kubernetes.io/created-by=cyclone`
Fixes #
Reference to #
```release-note
NONE
```

fix: pod controller miss gc pods

---

pkg/server/handler/v1alpha1/helper.go
pkg/server/handler/v1alpha1/resource.go
pkg/server/handler/v1alpha1/stage.go
pkg/server/handler/v1alpha1/workflow.go
pkg/server/handler/v1alpha1/workflowtrigger.go

Add owner reference for project sub-resources:
- workflow
- stage
- resource
- workflow trigger
so when a project was deleted, it's sub-resources will be deleted too.
Fixes #
Reference to #
```release-note
NONE
```

fix: add project owner reference

---

pkg/server/handler/init.go

Fix bug can not stop workflowrun
Fixes #
Reference to #
```release-note
NONE
```

fix: can not stop workflowrun

---

pkg/workflow/workload/pod/builder.go
pkg/workflow/workload/pod/builder_test.go

Fix the problem that resource requirements set in wf spec is not used problem.
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

fix: apply correct resource requirements

---

pkg/workflow/coordinator/coordinator.go

Collect logs of init-containers and coordinator itself.
Partially Fixes #929 
Reference to #
```release-note
NONE
```

fix: should collect input resources logs

---

release/workflow-controller.yaml

DEVELOP_MODE for workflow controller, for the moment, it controls whether to pull resolver images always.
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

chore: add DEVELOP_MODE to release

---

pkg/server/biz/scm/gitlab/gitlab.go
pkg/server/handler/v1alpha1/webhook.go

Ref of workflow run triggered by scm tag release, shold be `refs/tags/{tagName}`, but it is `{tagName}`
Fixes #
Reference to #
```release-note
NONE
```

fix: wrong ref of wfr triggered by scm tag release

---

build/worker/start.sh
cmd/worker/options/options.go
pkg/cloud/kubernetes/kubernetes.go

Fixes #
Reference to #
```release-note
NONE
```

feat: support configure dind parameter

---

pkg/workflow/workload/pod/builder.go
pkg/workflow/workload/pod/builder_test.go

A pod maybe contains multi containers, average resource requirements to every container.
Fixes #
Reference to #
```release-note
NONE
```

fix: average resource requirements to every container

---

manifests/cyclone.yaml.template
pkg/server/config/config.go
pkg/server/handler/v1alpha1/integration.go
pkg/server/handler/v1alpha1/tenant.go
release/cyclone-server.yaml

Make it configurable to open control cluster for workflow execution. So that, we can deploy cyclone with everything ready for workflow execution.
Fixes #
Reference to #
/cc @zhujian7
```release-note
NONE
```

improve: make open control cluster configurable

---

web/config/webpack.config.prod.js

CSS won't work in production mode, caused by css models enabled for antd.
Fixes #
Reference to #
```release-note
NONE
```

fix: disable css module for antd

---

build/resolver/svn/entrypoint.sh

allow svn revision to be empty
Fixes #
Reference to #
```release-note
NONE
```

fix: allow svn revision to be empty

---

pkg/server/handler/v1alpha1/webhook.go

The `ref` of SCM triggered pipeline is in the form of `refs/head/xxx`, and it cannot match `branch`  in the form of `xxx` configured by users
Fixes #
Reference to #
```release-note
NONE
```

fix: scm push event trigger does not work

---

pkg/server/handler/v1alpha1/webhook.go

With SCM triggered pipeline, `TAG` and `SCM_REVISION` does not take effect when there is a default value,e.g. `latest` for `TAG` and `refs/heads/master` for `SCM_REVISION`.
Fixes #
Reference to #
```release-note
NONE
```

fix: tag does not take effect when there is a default value

---

pkg/workflow/common/cluster.go

Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

fix: default cluster when empty in execution context

---

pkg/server/handler/v1alpha1/integration.go
pkg/server/handler/v1alpha1/tenant.go

While close cluster we will delete some resources like `namespace`, `resource quota` an `pvc`, if k8s returns error `not found`, this should be treated as deleting success.
Fixes #
Reference to #
```release-note
NONE
```

change close cluster logic

---

cmd/workflow/controller/main.go
pkg/workflow/common/cluster.go
pkg/workflow/controller/init.go

In the case what use only workflow engine, we need to enable execution cluster for the control cluster.
Fixes #
Reference to #
```release-note
NONE
```

Create default ExecutionCluster CR for control cluster

---

pkg/common/const.go
pkg/meta/labels.go
pkg/workflow/controller/controllers/workflow_trigger.go
pkg/workflow/controller/controllers/workflowrun.go
pkg/workflow/controller/handlers/workflowtrigger/cron_job.go
pkg/workflow/workflowrun/operator.go
pkg/workflow/workload/pod/builder.go

Add controller instance id to workflow controller. If instance set, controllers for `pod`, `workflowrun`, `workflowruntrigger` will only watch resources with the correct instance label. And pod, wfr created by the workflow controller will also have controller instance label set.
To keep back-compatibility, if no instance id set, no label would be applied, and controllers would watch resources without the controller instance label.
Note: only workflow controller supports multiple instance. Cyclone sever would ignore the controller instance label.
To set instance id, set environment variable `CONTROLLER_INSTANCE_NAME`, for example: `cyclone`
Fixes #
Reference to #
**Special …

feat: support multiple workflow controller

---

pkg/server/handler/v1alpha1/integration.go

Update schedulable-cluster label of cluster integration when close/open cluster.
Fixes #
Reference to #
```release-note
NONE
```

fix: update label when open/close cluster

---

pkg/server/biz/pvc/pvc.go

ignore not found error while delete pvc watcher
Fixes #
Reference to #
```release-note
NONE
```

fix: ignore not found error while delete pvc watcher

---

web/src/api/index.js
web/src/components/integration/component/detail/index.js
web/src/locale/en-US.yaml
web/src/locale/zh-CN.yaml
web/src/store/integration.js

Open/Close cluster in integration cluster.
Fixes #
Reference to #
/cc @huxiangtao @supereagle 
```release-note
NONE
```

[Web] feat: open/close cluster in integration center

---

build/resolver/git/entrypoint.sh

Get last commit id in git resolver
Fixes #
Reference to #
```release-note
NONE
```

feat: get last commit id in git resolver

---

web/src/components/stageTemplate/add/Config.js
web/src/components/stageTemplate/add/Output.js

fix Input box loses focus problem
Fixes #
Reference to #
```release-note
NONE
```

fix(stageTemplate): fix array input blur with dynamic field key

---

pkg/server/handler/v1alpha1/helper.go
pkg/server/handler/v1alpha1/workflowrun.go
pkg/server/handler/v1alpha1/workflowtrigger.go

The list wfts API listed all workflow triggers and did not filter triggers that do not belong to the specific workflow. fix that.
Fixes #
Reference to #
```release-note
NONE
```

fix: list workflow triggers belonged to the specific workflow

---

pkg/common/values/generators.go
pkg/common/values/generators_test.go
pkg/common/values/nowtime.go
pkg/common/values/nowtime_test.go
pkg/common/values/random.go
pkg/common/values/random_test.go
pkg/workflow/workload/pod/builder.go

Support two new argument value type:
- NowTimeString
- RandomString
Fixes #
Reference to #
```release-note
NONE
```

feat: support generation type values in argument

---

build/resolver/git/entrypoint.sh

Fix git resolver clone bitbucket code error:
```
fatal: unable to access 'http://admin:NDA5NzQxOTA4MDkzOr3yF/GiJzn8sofBCW2iCKdc0qTe@192.168.21.97:7990/scm/test/devops.git/': Port number ended with 'N'
```
Fixes #
Reference to #
```release-note
NONE
```

fix(git-resolver): encode token string

---

pkg/server/handler/v1alpha1/integration.go
pkg/server/handler/v1alpha1/template.go

When tenant is system tenant, no need to list stage tempalate/integration for system again.
Fixes #1029 
Reference to #
```release-note
NONE
```

fix: list templates/integration for default template

---

pkg/server/biz/hook/hook.go
pkg/server/handler/v1alpha1/workflowtrigger.go

Fix bug that create cron type trigger failed with `unsupported trigger type: Cron`
Fixes #
Reference to #
```release-note
NONE
```

fix: create cron type trigger failed

---

web/src/components/workflow/component/stage/AddStage.js

replace stage template select options key & alias with unique key which is composed by <namespace>-<templatename>
Fixes #
Reference to #
/cc @cd1989 
```release-note
NONE
```

fix(workflow): modify stage template select options key & alias

---

web/src/components/resource/component/create/FormContent.js

resource types parameters arguments have required value , it is a controlled component, so set the value through defaultvalue props & set props of onChange function for changing form value;
Fixes #
Reference to #
```release-note
NONE
```

fix(resourceTypes): fix resource type parameters switch defaultvalue

---

pkg/meta/annotations.go
pkg/workflow/workflowrun/operator.go
pkg/workflow/workload/pod/builder.go

Add annotation to pod created by Workflow Engine to avoid istio sidecar injection
Fixes #
Reference to #
```release-note
NONE
```

fix: avoid istio sidecar injection

---

pkg/server/handler/v1alpha1/notification.go

When workflowruns have no trigger annotation, `updatePullRequestStatus()` does not need to handle it.
Fixes #
Reference to #
```release-note
NONE
```

fix: skip notifications for workflowruns without trigger

---

web/src/components/integration/component/List.js
web/src/components/project/component/detail/index.js
web/src/components/workflow/component/detail/WorkflowRuns.js
web/src/components/workflow/component/list/ListLayout.js

Order of wfr
Fixes #1082 
Reference to #
```release-note
NONE
```

fix: display list in descending order of creation

---

pkg/server/biz/pvc/pvc.go
pkg/server/biz/usage/watcher.go

Report PVC usage to metadata namespace which always stay in control cluster.
Fixes #1119
Reference to #
```release-note
NONE
```

fix: storage usage report from user cluster

---

pkg/workflow/workload/pod/builder.go

`"` escape in argument is override by mistake.
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

fix: argument escape problem

---

pkg/common/values/nowtime_test.go
pkg/util/retry/retry.go
pkg/workflow/controller/config.go
pkg/workflow/controller/handlers/pod/operation.go
pkg/workflow/workflowrun/operator.go
pkg/workflow/workflowrun/workload.go

- delete pod immediately after stage finished
- create pod retry on exceeded quota
Fixes #
Reference to #
```release-note
NONE
```

fix: resources not freed immediately after stage finished

---

pkg/util/retry/retry.go
pkg/workflow/controller/handlers/pod/operation.go
pkg/workflow/workflowrun/operator.go
pkg/workflow/workflowrun/workload.go

* fix: resources not freed immediately after stage finished
* fix: remove retry config
Fixes #
Reference to #
```release-note
NONE
```

[release-1.0] fix: resources not freed immediately after stage finished

---

build/resolver/git/entrypoint.sh

flock depends on pvc type and image os, for example, with NFS, it will fail on some old linux kernel version.
Switch to a simpler way for the lock, by using mkdir.
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

refactor: use mkdir to acquire lock in git resolver

---

build/cicd/sonarqube/entrypoint.sh

Fixes #
Reference to #
```release-note
NONE
```

fix: add auth info when get scan results

---

README.md
docs/installation.md

Add supported Kubernetes versions.
Fixes #
Reference to #
```release-note
NONE
```

chore: add supported kubernetes versions

---

pkg/server/biz/integration/cluster/cluster.go
pkg/server/biz/pvc/pvc.go

PVC usage is not used yet, and the implementation for the moments have severe performance problems.
Fixes #
Reference to #
```release-note
NONE
```

chore: disable PVC watcher

---

pkg/server/biz/scm/github/github.go
pkg/server/handler/v1alpha1/webhook.go

For GitHub release type event webhook, we should only process `created` and ignore the `published`, otherwise, one release will trigger a workflow twice.
Fixes #
Reference to #
```release-note
NONE
```

fix: github release event webhook trigger workflow twice

---

build/resolver/git/entrypoint.sh

```
RPC failed; curl 56 GnuTLS recv error (-9): Error decoding the received TLS packet
```
https://stackoverflow.com/questions/6842687/the-remote-end-hung-up-unexpectedly-while-git-cloning
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

fix: set http.postBuffer for git resolver

---

pkg/workflow/controller/handlers/pod/operation.go

Fix workflow run status check logic, it should be `Failed` when the coordinator container not ready.
Fixes #
Reference to #
```release-note
NONE
```

fix: workflow run status check logic

---

build/resolver/git/entrypoint.sh
pkg/server/biz/scm/bitbucket/server/webhooks.go

Difference of refs/pull-requests/id/merge and refs/pull-requests/id/from: https://community.atlassian.com/t5/Bitbucket-questions/Difference-of-refs-pull-requests-lt-ID-gt-merge-and-refs-pull/qaq-p/772142
https://blog.developer.atlassian.com/a-better-pull-request/
Fixes #
Reference to #
```release-note
NONE
```

fix: bitbucket pr webhook problem

---

pkg/server/biz/scm/gitlab/gitlab.go

Can not use v3 in default when response code is unnormal.
Fixes #
Reference to #
```release-note
NONE
```

fix: gitlab version detect problem

---

pkg/server/biz/scm/gitlab/gitlab.go

As the title suggested
Fixes #
Reference to #
```release-note
NONE
```

fix: GitLab tag deletion should not trigger workflow

---

pkg/server/biz/scm/bitbucket/server/server.go

use error with reason for token validation fail
Fixes #
Reference to #
```release-note
NONE
```

fix: use error with reason for token validation fail

---

pkg/server/handler/v1alpha1/webhook.go

Change pull request status to pending when WorkflowRun start running.
Fixes #
Reference to #
```release-note
NONE
```

fix: init pull request status when wfr start

---

pkg/server/biz/scm/gitlab/gitlabv3.go
pkg/server/biz/scm/gitlab/gitlabv4.go
pkg/server/biz/scm/scm.go

When a pipeline is triggered by GitLab merge-requests, the [`SCM_REVISION`](cyclone-server-server-v1-0-864b879456-ssw5v) should in the format of `refs/merge-requests/{id}/head:{target-branch}` so add target branch for GitLab while list merge requests.
Fixes #
Reference to #
```release-note
NONE
```

fix: add target branch for list pull requests api

---

build/toolbox/Dockerfile
build/toolbox/resolver-runner.sh

defer exit to collect init containers' logs
Fixes #
Reference to #
```release-note
NONE
```

fix: defer exit to collect init containers' logs

---

pkg/server/handler/v1alpha1/webhook.go

Image tag wrong when workflow triggered by bitbucket release.
Tag is in the format of `refs/heads/release/{name}`, we need to change it to `{name}`
Fixes #
Reference to #
```release-note
NONE
```

fix: image tag wrong when workflow triggered by bitbucket release

---

pkg/server/biz/scm/github/github.go
pkg/server/handler/v1alpha1/webhook.go

The `tag-release` trigger for GitHub webhook has an issue: GitHub `release creation` can trigger workflows, but `tag creation` can not. 
This PR will fix it.
Fixes #
Reference to #
```release-note
NONE
```

fix: GitHub tag trigger problem

---

pkg/workflow/workflowrun/operator.go

Fix overall status wrong when stage status is cancelled
Fixes #
Reference to #
```release-note
Fix overall status wrong when stage status is cancelled
```

fix: overall status wrong when stage status is cancelled

---

pkg/server/handler/v1alpha1/workflowrun.go
pkg/util/websocket/websocket.go

Close log stream websocket when workflow run running completed
Fixes #
Reference to #
```release-note
NONE
```

fix: close websocket when workflow run running completed

---

cmd/workflow/coordinator/main.go
pkg/common/const.go
pkg/server/biz/stream/folder.go
pkg/server/biz/stream/folder_test.go
pkg/server/handler/v1alpha1/workflowrun.go
pkg/util/websocket/websocket.go
pkg/workflow/coordinator/coordinator.go
pkg/workflow/coordinator/cycloneserver/client.go
pkg/workflow/coordinator/k8sapi/k8sapi.go

Add EOF file to stage logs folder to indicate end of stage logs, so that realtime logs can have a done signal.
Fixes #
Reference to #
```release-note
NONE
```

[CPS-2.8] fix: eof of stage logs FolderReader

---

pkg/server/biz/integration/cluster/trigger.go
pkg/server/handler/v1alpha1/integration.go
pkg/workflow/workflowrun/workload.go

The execution context of workflow triggers expire when the worker cluster of the tenant changed. 
This PR will reconcile the execution context of workflow triggers when a worker cluster is opened.
Fixes #
Reference to #
```release-note
NONE
```

fix: execution context of workflow trigger expire when cluster changed

---

pkg/apis/cyclone/v1alpha1/workflow_run.go
pkg/workflow/workflowrun/operator.go

If the topology of a workflow changed, the old workflowRun's running status can not display, So we need to record workflow topology at workflowRun running time to workflowRun status.
Fixes #
Reference to #
```release-note
NONE
```

feat: record workflow topology to workflow run

---

.golangci.yml
.travis.yml
Makefile
pkg/server/biz/integration/converter.go
pkg/server/biz/scm/gitlab/gitlab.go
pkg/util/cerr/error.go

Fixes #1315
Reference to #
/cc @zhujian7
```release-note
NONE
```

fix(1315): update golangci-lint version for memory usage

---

pkg/meta/labels.go
pkg/workflow/workflowrun/operator.go
pkg/workflow/workload/pod/builder.go

WorkflowRun GC SHOULD Wait all workflowRun related workload pods
deleting completed, then start gc pod to clean date on PV.Otherwise,
if the path which is used by workload pods in the PV is deleted
before workload pods deletion, the pod deletion process will get
stuck on Terminating status.
Fixes #
Reference to #
/cc @supereagle @pendoragon @orainxiong 
```release-note
NONE
```

fix: deleting pod stuck on Terminating status

---

web/src/components/workflow/component/stage/TemplateStage.js

- output-resource-path field  need't required validate
Fixes #
Reference to #
/cc @ladjzero 
```release-note
NONE
```

fix: fix output-resource-path required validate

---

build/resolver/git/Dockerfile

[Rebuilding git with openssl instead of gnutls](https://stackoverflow.com/questions/38378914/git-error-rpc-failed-curl-56-gnutls)
Fixes #1250
Reference to #
```release-note
NONE
```

refactor(git): use openssl for git

---

pkg/server/biz/usage/watcher.go
pkg/server/biz/usage/watcher_test.go

Fixes #
Reference to #
/cc @iawia002 
```release-note
This change will break backwards compatibility that all pvc-uaage wahcer deployments create in the previous version can not be deleted
```

fix: update deployment version to satisfy k8s 1.17

---

cmd/server/main.go
pkg/meta/labels.go
pkg/server/biz/accelerator/cleaner/clean.go
pkg/server/biz/accelerator/cleaner/clean_test.go
pkg/server/biz/pvc/pvc.go
pkg/server/biz/usage/watcher.go

-  init caches cleanup status while cyclone server startup, change all Running status of cache cleanup to Failed
- pvc deleted will not make cache cleanup failed
Fixes #
Reference to #
```release-note
NONE
```

fix: init caches cleanup status

---

build/toolbox/resolver-runner.sh
cmd/workflow/coordinator/main.go
pkg/common/signals/signal.go
pkg/server/handler/v1alpha1/workflowrun.go
pkg/util/websocket/websocket.go
pkg/workflow/coordinator/coordinator.go
pkg/workflow/coordinator/cycloneserver/client.go
pkg/workflow/coordinator/k8sapi/k8sapi.go

- Stream logs receiver sends ping message periodically to keep the
connection not idle. The reason why we need this is sender peer may
stuck on reading kubernetes stream logs and could not have a chance
to send ping message periodically.
- Add somes logs
Fixes #
Reference to #
```release-note
NONE
```

fix: sending ping message for websocket

---

build/toolbox/resolver-runner.sh
cmd/workflow/coordinator/main.go
pkg/common/signals/signal.go
pkg/server/handler/v1alpha1/workflowrun.go
pkg/util/websocket/websocket.go
pkg/workflow/coordinator/coordinator.go
pkg/workflow/coordinator/cycloneserver/client.go
pkg/workflow/coordinator/k8sapi/k8sapi.go

This is a cherry-pick of #1422
- Stream logs receiver sends ping message periodically to keep the
connection not idle. The reason why we need this is sender peer may
stuck on reading kubernetes stream logs and could not have a chance
to send ping message periodically.
- Add somes logs
Fixes #
Reference to #
```release-note
NONE
```

[cps-2.8]:fix: sending ping message for websocket

---

pkg/server/handler/v1alpha1/workflowrun.go
pkg/util/websocket/websocket.go

The cyclone server will close the web socket immediately when it watches the log completed.
But we expect to leave some seconds to sending logs before the web socket closing.
Fixes #
Reference to #
/cc @hyy0322 @qiuxiaolian 
```release-note
NONE
```

fix: delay to close websocket

---

pkg/server/handler/v1alpha1/workflowrun.go
pkg/util/util.go
pkg/util/util_test.go
pkg/workflow/controller/handlers/pod/operation.go
pkg/workflow/controller/handlers/workflowrun/handler.go
pkg/workflow/workflowrun/utils.go
pkg/workflow/workflowrun/utils_test.go
pkg/workflow/workflowrun/workload.go

If the delegation task processed in the delegation API and update the task status to Succeeded/Failed status, we should not update it to Waiting(since the task has already been processed), otherwise, the task will be stuck.
Fixes #
Reference to #
```release-note
NONE
```

fix: status wrong when task processed in the delegation api

---

build/resolver/git/entrypoint.sh

Fixes #
Reference to #
/cc @hyy0322 @supereagle @bbbmj @qianlei90 @muzi502 
```release-note
NONE
```

fix(security): filter git auth information

---

pkg/server/biz/accelerator/accelerate.go
pkg/server/biz/accelerator/accelerate_test.go

Fixes #
Reference to #
```release-note
NONE
```

feat: support sbt accelerate

---

pkg/server/biz/scm/bitbucket/bitbucket.go
pkg/server/biz/scm/bitbucket/server/server.go
pkg/server/biz/scm/bitbucket/server/webhooks.go
pkg/server/config/config.go
pkg/server/handler/v1alpha1/integration.go
pkg/server/handler/v1alpha1/tenant.go
pkg/server/handler/v1alpha1/webhook.go

BitBucket version smaller than 5.4 can not support webhooks, we
suppose these bitbucket can use hooks, like ScriptRunner, to send
a post request to cyclone server when some events happened, and
the cyclone server will handle the request and trigger workflows.
Fixes #
Reference to #
```release-note
NONE
```

feat: support bitbucket triggers workflows by hooks

---

pkg/workflow/common/const.go
pkg/workflow/common/owner.go
pkg/workflow/common/owner_test.go
pkg/workflow/workflowrun/operator.go
pkg/workflow/workload/pod/builder.go
pkg/workflow/workload/pod/builder_test.go

Add workflow name info for pods created by cyclone
Fixes #
Reference to #
```release-note
NONE
```

fix: add workflow name info for pods created by cyclone

---

pkg/workflow/common/const.go
pkg/workflow/workload/pod/builder.go
pkg/workflow/workload/pod/builder_test.go

`PROJECT_NAME` is a very likely conflict word with other systems,
like ourselves SonarQube scanner program，do not inject it as an
Env into the WorkflowRun pod.
TODO:
- change the Env key name(add a prefix like CYCLONE_PROJECT_NAME)
and inject it in the future.
`PROJECT_NAME` is in conflict with https://github.com/caicloud/cyclone/blob/cps-2.10/build/cicd/sonarqube/entrypoint.sh#L13
Fixes #
Reference to #https://github.com/caicloud/cyclone/pull/1506
```release-note
NONE
```

fix: delete project name in workflow pod env

---

pkg/workflow/controller/config.go
pkg/workflow/workload/pod/builder.go
release/workflow-controller.yaml

feat(builder): add support for dood container
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

feat(builder): add support for dood container

---

build/resolver/git/entrypoint.sh

Simplify the way we clone repos, and don't pass `-f` to `git checkout`
so that git won't fail silently.
Manual validation:
```
Trying to acquire lock and pull resource
Got the lock, start to pulling...
Clone refs/heads/master...
Initialized empty Git repository in /workspace/data/.git/
From http://<redacted>/root/golangtest
* branch            master     -> FETCH_HEAD
* [new branch]      master     -> origin/master
total 1
drwxr-xr-x 1 root root   3 Oct 27 14:30 .
drwxr-xr-x 1 root root   2 Oct 27 14:30 ..
drwxr-xr-x 1 root root  12 Oct 27 14:30 .git
-rw-r--r-- 1 root root 249 Oct 27 14:30 Dockerfile
drwxr-xr-x 1 root root   2 Oct 27 14:30 helloworld
Collect commit id to result file /__result__ ... …
```

fix(resolver::git): refine repos cloning and fix `git checkout`

---

pkg/workflow/common/const.go
pkg/workflow/controller/config.go
pkg/workflow/controller/controllers/exucution_cluster.go
pkg/workflow/controller/controllers/pod.go
pkg/workflow/controller/controllers/workflow_trigger.go
pkg/workflow/controller/controllers/workflowrun.go
pkg/workflow/workflowrun/limits.go

Make resyncPeriod configurable
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

cps-2.8: feat(controllers): make resyncPeriod configurable

---

Makefile
pkg/workflow/common/const.go
pkg/workflow/controller/config.go
pkg/workflow/controller/controllers/exucution_cluster.go
pkg/workflow/controller/controllers/pod.go
pkg/workflow/controller/controllers/workflow_trigger.go
pkg/workflow/controller/controllers/workflowrun.go
pkg/workflow/controller/handlers/workflowrun/handler.go
pkg/workflow/workflowrun/limits.go

Make resyncPeriod configurable
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

feat(controllers): make resyncPeriod configurable

---

pkg/server/biz/scm/bitbucket/server/repos_webhooks.go
pkg/server/biz/scm/bitbucket/server/server.go
pkg/server/biz/scm/bitbucket/server/webhooks.go

We actually want to trigger pipeline on `pr:from_ref_updated` event
rather than `pr:modified`.
Fixes #
Reference to #
/cc @zhujian7 
```release-note
bitbucket: fix a bug that PR commits won't trigger pipeline.
```

fix(bitbucket): correct webhook event

---

helm/cyclone/templates/service-account.yaml
pkg/apis/cyclone/v1alpha1/stage.go
pkg/workflow/workload/pod/builder.go
pkg/workflow/workload/pod/builder_test.go

Enable users to specify extra labels or annotations of pod in stage.
Fixes #
Reference to #
The reason I change the apiVersion of PSP to `policy/v1beta1` is the current apiVersion `extensions/v1beta1` has been deprecated and will be removed in k8s v1.16: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
/cc @zhujian7 
```release-note
NONE
```

Be able to specify extra labels or annotations of pod in stage

---

pkg/workflow/controller/controllers/controller.go
pkg/workflow/controller/result.go
pkg/workflow/workflowrun/operator.go
pkg/workflow/workflowrun/utils.go
pkg/workflow/workflowrun/workload.go

/kind feature
/area cicd
Retry creating pod on QuotaExceed error until timeout
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

feat(wfr): retry creating pod on QuotaExceed error until timeout

---

manifests/cyclone/templates/_helpers.tpl
manifests/cyclone/templates/controller.yaml
manifests/cyclone/templates/server.yaml
pkg/server/biz/integration/cluster/cluster.go
pkg/server/common/cluster.go
pkg/server/common/utils.go

/kind cleanup
/area cicd
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

Update the name of resourceQuota to the name of its namespace

---

.github/PULL_REQUEST_TEMPLATE.md
pkg/meta/annotations.go
pkg/meta/labels.go
pkg/server/biz/scm/bitbucket/server/webhooks.go
pkg/server/biz/scm/github/github.go
pkg/server/biz/scm/gitlab/gitlab.go
pkg/server/biz/scm/scm.go
pkg/server/handler/v1alpha1/webhook.go

/area cicd
/kind feature
* Get the update timestamp from webhook payload
* Add annotation `workflowrun.cyclone.dev/scm-pr-updated-at`  and label `workflowrun.cyclone.dev/scm-pr-ref` to wfr triggered by PR events
* When handling webhook, process all events sequentially and ignore the event that is triggered earlier, and update PR status in the background.
Complement #1541
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

feat(server): auto cancel previous builds triggered by PR events

---

pkg/meta/annotations.go
pkg/meta/labels.go
pkg/server/biz/scm/bitbucket/server/webhooks.go
pkg/server/biz/scm/github/github.go
pkg/server/biz/scm/gitlab/gitlab.go
pkg/server/biz/scm/scm.go
pkg/server/handler/v1alpha1/webhook.go
pkg/util/util.go

/kind feature
/area cicd
Manually backport #1552 to cps-2.10-infra.
Fixes #
Reference to #
/cc @zhujian7 
```release-note
NONE
```

[cps-2.10-infra] feat(server): auto cancel previous builds triggered by PR

---

pkg/workflow/controller/controllers/controller.go
pkg/workflow/controller/handlers/configmap/handler.go
pkg/workflow/controller/handlers/executioncluster/handler.go
pkg/workflow/controller/handlers/interface.go
pkg/workflow/controller/handlers/pod/handler.go
pkg/workflow/controller/handlers/workflowrun/handler.go
pkg/workflow/controller/handlers/workflowtrigger/handler.go
pkg/workflow/workflowrun/operator.go
pkg/workflow/workflowrun/workload.go

/area cicd
/kind bug
Currently a workflowRun could be updated 3 times during reconciliation, which causes subtle bug, for instance the operator begins to reconcile before receiving the 3rd update from the API server.
This PR makes sure the workflowRun controller return immediately after updating the workflowRun object.
Fixes #
Reference to #
/cc @zhujian7 
```release-note
fix: ensure workflowRun controller return immediately after updating
```

Ensure workflowRun controller return immediately after updating
